fedspendingtransparency/fiscal-data

src/layouts/explainer/sections/national-debt/national-debt.jsx

No change in coverage.
Note: The font size had already been corrected and equals that displayed in the mocks (14px / 0.875rem) so I only adjusted the legend spacing. Since the legend spacing is matrix based and dependent on the size of the parent nivo chart, I couldn't really put down an exact pixel amount for the margin, so I adjusted the positioning of the legends with the aid of a pixel ruler to approximate the 24px of top margin.

FDG-4998 Adjust bar chart legend font and spacing above legend

---

src/layouts/explainer/sections/national-debt/national-debt.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-5557
No change to code coverage

FDG-5557 Debt Explainer page - chart axis labels display very small upon entry to the page/refresh

---

src/layouts/explainer/sections/national-debt/national-debt.jsx
src/layouts/explainer/sections/national-debt/national-debt.module.scss

Here are the specific design review comments addressed in this PR: 
1. Let’s close the gap a bit between the data headline (2022 and 135%) and the chart itself, and aim for balance between what’s above and below. A suggestion would be 2rem/32px.
2. To reduce chart clutter, we’ll take out the intermediate lines between the increments on the y-axis.
3. Increase the spacing between the footer text and the background to be about 2 rem/32px. Right now it’s a more narrow gap compared to the top
.

FDG 5405 Padding and spacing adjustments, grid line adjustments

---

src/layouts/explainer/sections/national-debt/national-debt.jsx

This PR satisfies the following design points: 
1. Can we also have the horizontal increment lines go behind the dark y-axis line? This should go for the same on the x-axis too. It creates little noticeable notches in the current order.
2. For the x-axis line color, are we able to match it to the deeper y-axis color? It’s currently much lighter in comparison and difficult to see.

FDG-5405 changed loading order of grid lines

---

src/layouts/explainer/sections/national-debt/national-debt.module.scss

Addresses the following design comments: 
1. Currently the data points at the top “headline” are spaced farther apart and would like to see if they can connected a little closer together like in the Zeplin mock
.

FDG-5405 adjusted header item spacing

---

src/components/site-header/site-header.module.scss

Addresses the following: 
The hex color of “topics” was 555555 instead of 666666 to match the rest of the navigation label colors (and Zeplin)
.

FDG-5246 Changed color of un highlighted topics header (Design Review)

---

src/layouts/explainer/sections/national-debt/national-debt.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-5724

FDG-5724 US National debt over 100 years chart should display highlighted year data element as 'Fiscal Year'

---

src/layouts/explainer/explainer-components/chart-container/chart-container.spec.js
src/layouts/explainer/sections/national-deficit/understanding/deficit-comparison-bar-chart/deficit-comparison-bar-chart.jsx
src/layouts/explainer/sections/national-deficit/understanding/deficit-comparison-bar-chart/deficit-comparison-bar-chart.spec.js

First attempt . . .
https://federal-spending-transparency.atlassian.net/browse/FDG-5891
unit test line coverage: 89.49%

FDG-5891 fix time zone adjustments that break the build

---

gatsby-config.js

https://federal-spending-transparency.atlassian.net/browse/FDG-5866
Turn off experimental gatsby build flag that optimizes for speed but locally consumes more memory.

FDG-5866 Troubleshoot build memory

---

documentation/Spending Explainer Data Sources & Methodologies.md

FDG-5663 added the spending explainer data source & methodologies read me
https://federal-spending-transparency.atlassian.net/browse/FDG-5663
Code coverage 89.47%

FDG-5663 Spending Explainer: Upload relevant documentation in FDG Dev Public GitHub repository

---

src/components/site-header/mobile-menu/mobile-menu.jsx
src/components/site-header/mobile-menu/mobile-menu.spec.js
src/components/site-header/site-header.jsx
src/components/site-header/site-header.spec.js
src/transform/explainer-pages-config.js

The Spending explainer is included in the navigation header under the 'AMERICA'S FINANCE GUIDE' heading with the following title: 'Spending'. The URL for the page should be:  https://fiscaldata.treasury.gov/federal-spending/
The order of AFG pages under the Topics > America’s Finance Guide' heading should be set as follows: Spending, Deficit, Debt.
The Spending explainer site navigation should display as expected on both desktop and mobile. 
Code Coverage: 89.48

Fdg 5801 - Add Spending Explainer to Site Nav

---

src/layouts/explainer/sections/federal-spending/spending-trends/spending-trends.jsx

Changed chapter to section in the spending trends sections
https://federal-spending-transparency.atlassian.net/browse/FDG-6037

FDG-6037 Copy should say 'section' and not 'chapter'

---

src/components/topics-section/explainer-tile/explainer-tile-helper.js
src/components/topics-section/explainer-tile/explainer-tile.spec.js

FDG-6045
With the Support of Tom
-Added the api calls to the explainer tile helper.
-Added a test to make sure the data populates.
https://federal-spending-transparency.atlassian.net/browse/FDG-6045
Test Coverage: 89.44

FDG-6045 Populate data variables from API in homepage tile promoting Spending explainer

---

env/uat.js
src/transform/endpointConfig.js

https://federal-spending-transparency.atlassian.net/browse/FDG-5695
Line coverage: 89.5%
Note: to see dataset page, site will need to be built as for the UAT env.

FDG-5695 Add new dataset to UAT: Federal Credit Similar Maturity Rates

---

src/layouts/explainer/sections/government-revenue/government-revenue.jsx

Added comingSoon flag to the revenue page
https://federal-spending-transparency.atlassian.net/browse/FDG-5951
AC:
The 'Coming Soon' flag is added to the Table of Contents (ToC) for the 'Federal Revenue Trends and the U.S. Economy' section.
The flag font and stylings match the design in Zeplin.
The flag is responsive and displays as expected on desktop and mobile.
CC: 89.69

FDG-5951 Add the 'Coming Soon' design to the Table of Contents (ToC) section of the Revenue Explainer page

---

src/layouts/explainer/heros/government-revenue/government-revenue-hero.spec.js
src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx

Changed abbrv in hero to match data feedback (https://data-transparency-bfs.slack.com/archives/CKM2LCAF6/p1663616161308949)
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6001

FDG-6001 Hook in the Data for Variable Data Elements on the Revenue Explainer page

---

src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx

Per data review, as detailed in #fdg-data slack channel by Jesse here: https://data-transparency-bfs.slack.com/archives/CKM2LCAF6/p1664204127364059?thread_ts=1663966622.079259&cid=CKM2LCAF6
https://federal-spending-transparency.atlassian.net/browse/FDG-6065
relates to logic for FDG-5942 : https://federal-spending-transparency.atlassian.net/browse/FDG-5942
Test coverage by lines: 89.73%

FDG-6065 use raw values to calculate percentages for tooltips

---

gatsby-config.js
gatsby-node.js
package-lock.json
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-6112
Line coverage: 89.45%
For dev localhost testing: This adds a new packaged dependency which needs to be installed. To test, run `build-dev` (or `build-prod`), then `npm run serve`. The redirects will work at localhost:9000. For example, http://localhost:9000/national-debt/ should redirect to `http://localhost:9000/americas-finance-guide/national-debt/`

FDG-6112 AFG URL Redirects

---

src/layouts/explainer/quote-box/quote-box.tsx
src/layouts/explainer/sections/federal-spending/overview/spending-overview.jsx
src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.jsx
src/layouts/explainer/sections/national-debt/national-debt.jsx

- Note: During my work I noticed every other quote box had incorrect top margin vs the mocks, so I readjusted those as well.
- I would encourage the reviewer to check the margin for the boxes vs the mocks to double to re affirm
- Coverage: 89.32%
- Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6174

FDG-6174 Debt Explainer - quote box margin disappear

---

src/layouts/explainer/sections/federal-spending/overview/spending-overview.jsx
src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-6196
The deleted code was no longer necessary after some refactoring that happened in an earlier defect, and was the cause of external links not working

FDG-6196 AFG Explainer pages - Links issue on Explainer pages

---

src/components/info-tip/info-tip.jsx

Design Changes
Added Scrolling handle close to the popover
Fixes styling issue on mobile title not creating second line
Removed onMouseLeave. User can click close or scroll close.
Code Coverage 89.19 
https://federal-spending-transparency.atlassian.net/browse/FDG-5762

FDG-5762 Debt Explainer - Update the interactions for the Glossary Terms tool tip for desktop and mobile

---

src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.module.scss

1. The width of the chart is more narrow than expected on desktop — can we widen the span of it to better match Zeplin?
2. There is a tighter gap than expected between the labels on the x-axis and the footer statement on mobile — can we review to make sure there’s a 1rem/16px spacing between them?
3. Curious to see if we can fit in a change with the type color of the headline labels: ‘Fiscal Year’, Total spending’, and ‘GDP’ — I overlooked the hex color and saw that it was not 666666 on my Zeplin mock :upside_down_face:, but if it can’t be included then we can address it later
https://federal-spending-transparency.atlassian.net/browse/FDG-5818

FDG-5818 Design feedback

---

src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx

CC: No Change
https://federal-spending-transparency.atlassian.net/browse/FDG-5820
Checking if BEA Notes is not null before extracting the date.

FDG-5820 Fixed issue with checking BEA data results

---

src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.js
src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx

Coverage: 89.13%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5863

FDG-5863 Spending Explainer - Add 'Percentage of GDP' section to the 'Government Spending and the U.S. Economy (GDP), FY YYYY-YYYY' line chart

---

src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.module.scss

Addresses design review: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1666799533530549
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5863

FDG 5863 Spending Explainer - Add 'Percentage of GDP' section to the 'Government Spending and the U.S. Economy (GDP), FY YYYY-YYYY' line chart

---

src/components/__build-tests__/postbuild-static-pages.ft.js

Attempt to overcome post-build test failures by setting longer puppeteer page navigation timeouts and jest test timeouts.
Also, remove obsolete test for legacy "topic" pages.

Attempt to fix test failures with longer timeouts

---

src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx
src/layouts/explainer/heros/national-debt/national-debt-hero.tsx
src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx

CC: 89
https://federal-spending-transparency.atlassian.net/browse/FDG-6311
Added logic to pass precision of 2 if deficit was greater than 999,999,999,999.
Passes all tests locally.
Builds locally.

FDG-6311 Deficit Explainer- hero section flip counter issue on mobile

---

src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/federal-revenue-trends-and-us-economy.jsx
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-6057
no change in coverage 
Design Review:
Some design spacing adjustments needed for the toggle placement, since it is wider than expected:
Desktop: The spacing between the copy and the top of the toggle should be 2rem/32px.
Mobile: The spacing between the copy and the top of the toggle is 1rem/16px.

FDG-6057 Update from design review

---

src/layouts/explainer/sections/federal-spending/overview/spending-overview-deficit-data.spec.js
src/layouts/explainer/sections/federal-spending/overview/spending-overview.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6361
- Tests were separated to prevent improperly matched / failed network responses
- Was tested locally around 30 times, no failures detected.
When testing locally for review, I'd ask that the review also run the test suite for however many times they believe to be appropriate.

FDG-6361 Intermittent network failure on unit test during build

---

src/components/published-reports/filter-section/filter-section.jsx
src/helpers/constants.js
src/helpers/published-reports/published-reports.js
src/transform/metadata-transform.js

Add text tip following the pattern of MTS reports explaining that older reports are aggregated into annual files. Update logic for switching from non-daily to daily type reports.
https://federal-spending-transparency.atlassian.net/browse/FDG-6157
Line coverage: 88.96%

FDG-6157 Whitelist reports for Daily Treasury Statement

---

src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.js
src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart-helper.js
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx

CC: No change
https://federal-spending-transparency.atlassian.net/browse/FDG-6415
Added logic for switching alt text depending on toggle view for both Spending and Revenue Chart.
Builds locally

FDG-6415 Missing Data visualization alt text – Percentage of GDP view

---

src/components/accordion/accordion.jsx
src/layouts/explainer/data-sources-methodologies/data-sources-methodologies.tsx
src/layouts/explainer/sections/national-debt/national-debt.jsx
src/layouts/explainer/sections/national-deficit/debt-deficit-difference/debt-deficit-difference.jsx

CC: 89.19
https://federal-spending-transparency.atlassian.net/browse/FDG-5495
Added logic to Accordion Component to determine which explainer page the GA event should be tied to.
Builds locally

FDG-5495 GA Event Tracking - Accordions

---

env/dev.js
env/stg.js
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-6520
Configuration change only.
Only dev and stg envs needed changes. UAT already points to UAT backend. QAT is a front-end development sandbox and tentatively continues to point at DEV backend as before.  Prod remains unchanged.

FDG-6520 Update environment mappings

---

src/components/topics-section/homepage-tile/homepage-tile.jsx
src/components/topics-section/homepage-tile/homepage-tile.module.scss
src/components/topics-section/homepage-tile/homepage-tile.spec.js
src/components/topics-section/topics-section.module.scss

1. Change styling around AFG logo so it appears correctly spaced in relation to header and maintains natural aspect ratio
2. remove paragraph spacing after main content feature tile to ensure consistent tile spacing
3. Increase spacing above dataset search link to match zeplin desktop-width mock, which is set to 81px/~5rem (not 4 rem as misstated in Bonnie's slack notes).
4. Add unit tests for the AFG logo icon.
line cov in branch: 89.58%

FDG-6374 Update styling per design review

---

src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx
src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx

Removed 'in trillions USD.' per data review
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5917

FDG-5917 Add tool tips to the 'compared to...' pills on select explainer pages

---

src/components/filter-download-container/user-filter/user-filter.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-6824
Remove widened right margin on info box when page is viewed in mobile width.
per design review comment here:
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1675700305737889
line cov: 89.64%

FDG-6824 TRRE country-currency Filter interface: minor tweak to css

---

src/layouts/explainer/explainer-components/chart-container/chart-container.module.scss
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.module.scss
src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.module.scss
src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6741
Since removing global overrides adjusted some styling on revenue charts, tweaks were made to ensure those charts also kept close to the mocks.

FDG-6741 Make Deficit Trends Bar Chart last bar coloring dynamic

---

src/components/dataset-data/dataset-data-helper/dataset-data-helper.js
src/components/dataset-data/test-helper.js

https://federal-spending-transparency.atlassian.net/browse/FDG-7097

FDG-7097 Date range filter is showing more years than expected in the Preview section for Treasury Certified Interest Rates: Annual dataset.

---

package-lock.json
src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.module.scss

re-center image by narrowing img style application. revert latest changes to caniuse dependencies that had been made as advised by warning when unit-tests run.
live coverage: 90.27%

troubleshoot sparkles for release 2023-08

---

src/layouts/explainer/explainer-components/chart-container/chart-container.jsx
src/layouts/explainer/explainer-helpers/explainer-charting-helper.js
src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.module.scss.d.ts

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6807

FDG-6807 508 Compliance - Remove 'img' label from chart container for Debt over 100 years chart

---

src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.jsx
src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart-helper.js
src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-5403 Re-enable accidentally skipped unit test, add logic to ensure chart headers are updated on animation effect.
Line Cov: 90.29%

FDG-5403 Debt 100y chart animation - fix chart header updates

---

src/components/page-helmet/page-helmet.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7005
This PR is to merge in the code added the GA4 tag that is attached to the new property to the page-helmet. Data collection has been verified in the analytics dashboard.

FDG-7005 Create a new GA4 property in the USAs non-DAP GA Account

---

src/components/glossary/glossary-header/glossary-header.tsx
src/components/glossary/glossary-term/glossary-popover-definition.jsx
src/components/glossary/glossary-term/glossary-popover-definition.spec.js
src/components/glossary/glossary.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-6999
Keyboard accessibility has been enhanced so you can now tab into the glossary panel and close out of the panel. The focus will still reset to the top of the page after the panel has closed, a follow up ticket has been created to save the tab location within the page prior to opening the panel.

FDG-6999 Update Glossary Definition Popover and Term Buttons within the Explainer Pages

---

src/layouts/explainer/sections/federal-spending/federal-spending.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-7376

FDG-7376 Spending explainer glossary panel is not sliding open when clicking button

---

src/components/dataset-card/dataset-card.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-7478
No change in coverage 
Citation clicks should now fire for the related dataset cards on all explainer pages

FDG-7478 "Spending - Related Datasets" are not displaying "Citation Click - Spending"

---

src/components/data-table/data-table-header/data-table-header.module.scss

Because the default sort arrow is rotated 90 deg, the original icon padding was applying before the rotation 
https://federal-spending-transparency.atlassian.net/browse/FDG-7525

FDG-7525 Design Review 

---

src/components/banner-callout/banner-callout-helper.js
src/components/masthead/masthead.jsx
src/components/masthead/masthead.spec.js
src/transform/static-metadata/datasets.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8183
test coverage: 90.07

FDG-8183 - Put up banner on dataset detail page for Securities Issued in TreasuryDirect

---

src/components/data-table/data-table.module.scss

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8413
NOTE: The column select did not used to have an enforced width. Now a width is enforced that tracks to within a % of the generated width on mobile from the previous iteration.

FDG-8413 Dataset Detail Page TRRE Select Columns Overlay Should Be Wider on Mobile

---

src/components/pageError/page-error-text.jsx
src/components/site-header/banner-types/content-unavailable.jsx
src/components/site-header/banner-types/content-unavailable.spec.js
src/components/site-header/banner-types/dataset-unavailable.jsx
src/components/site-header/banner-types/datatset-unavailable.spec.js
src/components/site-header/site-header.jsx
src/layouts/experimental/experimental.jsx

[FDG-8292](https://federal-spending-transparency.atlassian.net/browse/FDG-8292)
Test: 90.00 yikes. 
I choose not to wrap the banner component with Announcement Banner for two reason. 
- First Announcement Banner is already being called and in one place. Easier to control the true false state if its in one place
- Second and really the only reason  is because if I put Announcement Banner in the individual components 11 test fail in the site-header. 
Let me know if you think this should change.

Fdg 8292 site error messages

---

src/layouts/explainer/sections/national-debt/breaking-down-the-debt/breaking-down-the-debt.jsx

[FDG-8415](https://federal-spending-transparency.atlassian.net/browse/FDG-8415)
Test: no change in coverage
We can pull the current year of 2024 down with the same useEffect as the debt %. I assume thats what it means by current fiscal year. and the math adds up to 15.94%. so slightly under 16%.

FDG-8415 Update Debt Cost Call Out

---

src/layouts/explainer/heros/national-deficit/national-deficit-hero.spec.js
src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8391
TEST: no coverage change. 
This PR was made per the request of Lindsey for an error in the Mac. 
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1705002562285659

FDG-8391 added back the ()

---

src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/circle-chart-label.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8650
Coverage: 90.23%
Note: relevant thread here -> https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1706543496815899

FDG-8650 User is unable to navigate through tabbing on Update Revenue Explainer "Sources of Revenue..." chart

---

src/components/data-table/data-table.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8741
Coverage: 90.77%
This bug was present on small tables on large datasets. So please feel free to test multiples of those (DTS Op Cash Balance, 120 Day Delinquent Debt Referral Compliance Report, etc)

FDG-8741 DTS Dataset Date Selections Don't Update Data Table

---

src/layouts/explainer/sections/treasury-savings-bonds/learn-more/learn-more.tsx

[FDG-8829](https://federal-spending-transparency.atlassian.net/browse/FDG-8829)
Correcting link:
TreasuyDirect.gov -> TreasuryDirect
- removing .gov
- adding "r" to "treasury"

FDG-8829 In Learn More section TreasuryDirect spelled wrong

---

src/components/dataset-data/table-section-container/summary-table/summary-table.module.scss

[**Jira**](https://federal-spending-transparency.atlassian.net/browse/FDG-8799)
**Test Coverage** 
All files (line %): 90.36%

FDG-8799 update summary header font size to 14px/0.875rem

---

src/components/links/custom-link/custom-link.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8988
Note: XML Files should download like pdfs from the custom link

FDG-8988 When user clicks on the XML file it is opening the file

---

src/components/glossary/glossary-definition/glossary-definition.tsx
src/helpers/glossary-helper/glossary-lookup.js

[Jira](https://federal-spending-transparency.atlassian.net/browse/FDG-8904)
All files (% lines): 90.27% 
glossary-lookup.js: 93.93%
glossary-definition.tsx: 100%

FDG 8904 Links in Glossary Slideout Are Not Displaying as Clickable Links

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/savings-bonds-sold-by-type-chart/inflation-toogle/inflation-toggle.tsx

[FDG-8970](https://federal-spending-transparency.atlassian.net/jira/software/c/projects/FDG/boards/44?quickFilter=414&selectedIssue=FDG-8970)
There were no change in the test coverage all MUI styling updates. 
The issue was mostly the position changing to relative for some reason. So I set it to absolute !important. I also had to change around the the styling a little bit to get the color to stay #fff. Noticed that changed as well.

FDG-8970- Inflation toggle not appearing as expected for the Savings Bonds Sold by Type Over Time chart

---

src/utils/api-utils-helper.js
src/utils/api-utils-helper.spec.js
src/utils/api-utils.js

Increasing test coverage around downloads and download param building. 
Previous coverage: 42.34%
[**Jira Story**](https://federal-spending-transparency.atlassian.net/browse/FDG-8985)
All files (% lines): 90.66% 
api-utils-helper.js: 100%
**Note to devs:** deleted unused code from api-utils-helper.js. This was caught while writing tests for the file.

FDG-8985 Improve api-utils-helper.js test coverage related to downloads / download params building

---

src/components/data-table/data-table-header/date-range-filter/date-range-text-input/date-range-text-input.spec.js
src/components/nivo/chart-toggle/chart-toggle.jsx
src/layouts/explainer/explainer-test-helper.js
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.spec.js

Increasing unit test coverage on files where it may be lacking to create a more robust well tested product.
Current tackle: 
- total-revenue-chart.jsx - 83.58%
- total-revenue-chart-helper.js - 85.71%
[**Jira Story**](https://federal-spending-transparency.atlassian.net/browse/FDG-8084)
All files (% lines): 90.88%
total-revenue-chart-helper.js: 100%
total-revenue-chart.jsx: 99.2%

FDG-8084 Improve Code Coverage - total revenue chart

---

src/components/data-table/data-table-footer/data-table-footer.tsx
src/components/download-wrapper/download-wrapper.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9279

FDG-9279 When downloading a file, direct download should not apply to this table because it is a large data table

---

src/components/select-control/select-control.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9308

FDG-9308 Hover tooltip is not working on the Published Date drop down arrow

---

env/uat.js
src/components/data-table/data-table-helper.tsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-8682
all files (% lines): 90.86

FDG-8682 New Dataset Created in UAT - Treasury Securities Buybacks Announcements/Results

---

src/transform/endpointConfig.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8648

FDG-8648 Remove Specific Columns from Default View on the Historical Debt Outstanding Dataset

---

src/components/data-table/data-table-header/data-table-header.tsx
src/components/data-table/data-table-header/date-range-filter/date-range-filter.module.scss
src/components/data-table/data-table.module.scss

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9521
Notes:
- After conversation with Kylon, date columns with short column titles can have a minimum width that matches the filter placeholder text so as to not obscure the filter, this means adding 5px of right padding to the filter to ensure the icon isn’t squished with the smaller column size. 
- Columns that have titles shorter then the column width remain as is
- Per 10/1/24 standup conversation, based on the limited solutions, we’ll move forward with setting it so you have the columns default to the width of the titles. Users won’t be able to resize smaller than that but can resize bigger. We’ll potentially explore future options on how to add the ability for a user to resize smaller.

FDG-9521 General Site Updates - Set data table column width to be length of column title

---

src/components/data-preview/data-preview-datatable-banner/data-preview-datatable-banner.module.scss
src/components/data-preview/data-preview-datatable-banner/data-preview-datatable-banner.spec.tsx
src/components/data-preview/data-preview-datatable-banner/data-preview-datatable-banner.tsx
src/components/data-preview/data-preview.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9867
Coverage: 89.96

FDG-9867 New Data Table section that holds the dataset name, filters, and any notes for any data table (Purple outline) should be above the filters.

---

src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart-helper.tsx
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.module.scss

[FDG-10017](https://federal-spending-transparency.atlassian.net/browse/FDG-10017)
No change in test: 90.09
interest-expense-chart and chart helper: 100%

FDG-10017 Interest Expense Insight - Split color swatch for "Interest Expense" to display both solid color and stripes

---

src/layouts/insight/sections/interest-expense/useGetInterestExpenseData.ts

https://federal-spending-transparency.atlassian.net/browse/FDG-10095
no change in testing

FDG-10095 Interest Expense Insight chart is displaying label for the current year 2025. It should only display label for every 2 years

---

src/pages/api-documentation/index.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10080
No change to test coverage

FDG-10080 API documentation page has Pivoting on the side navigation, but the Pivoting section is deleted on the page

---

src/components/data-preview/data-preview-data-table/data-preview-data-table.spec.js
src/components/data-preview/data-preview-data-table/data-preview-data-table.tsx
src/components/data-preview/data-preview-section-container/data-preview-section-container.tsx
src/components/data-preview/data-preview-table/data-preview-table.tsx
src/components/data-table/data-table-helper.tsx
src/components/data-table/data-table-test-helper.js
src/components/data-table/data-table.spec.js
src/components/data-table/data-table.tsx
src/components/download-wrapper/download-item-button/download-item-button.jsx
src/models/IDataTableProps.ts
src/utils/test-utils.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10029
Test coverage: 90.15%
Note: I noticed code for the hasTimestamp download was missing from the now table so I moved that over

FDG-10029 Add Quotes Text Qualifiers to CSV Downloads

---

src/components/glossary/glossary-term/glossary-popover-definition.spec.js
src/helpers/dates/date-helpers.js
src/helpers/dates/date-helpers.spec.js
src/helpers/glossary-helper/glossary-lookup.js

[FDG-9114 Jira](https://federal-spending-transparency.atlassian.net/browse/FDG-9114)
Description: The Fiscal Year definition in the glossary (**Resources -> Glossary -> Fiscal Year**) should now use the last-completed fiscal year, regardless of the year in the original definition.
Note: This was done using Date() logic rather than the API originally requested in the ticket. (Approved by ticket writer and the data team.)
To Validate:
The Fiscal Year definition in the glossary should return:
> "...For example, Fiscal Year 2024 (FY 2024) started October 1, 2023, and ended September 30, 2024..."
On October 1, 2025, that should update to:
> "...For example, Fiscal Year 2025 (FY 2025) started October 1, 2024, and ended September 30, 2025..."

FDG-9114 G-Hook in the Data for the Glossary File

---

src/components/date-picker/date-text-input/date-text-input.tsx

… Num Lock enter on the keyboard it is not displaying the error msg
[FDG-10565](https://federal-spending-transparency.atlassian.net/browse/FDG-10565)

FDG-10565 When user typed ‘May 23, 2029’ into the input box and press Num Lock enter on the keyboard it is not displaying the error msg
