fedspendingtransparency/fiscal-data

- src/layouts/explainer/explainer-related-datasets/explainer-related-datasets.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5440
> FDG-5440 Fixed tablet spacing

- src/components/accordion/accordion.jsx
- src/layouts/explainer/data-sources-methodologies/data-sources-methodologies.module.scss
- src/layouts/explainer/data-sources-methodologies/data-sources-methodologies.tsx
- src/layouts/explainer/explainer.spec.js
- src/layouts/explainer/explainer.tsx
- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.spec.js
- src/layouts/explainer/sections/sections.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-5313
unit test line coverage: 89.35
> FDG-5313 add data sources and methodologies component to debt explainer.

- src/components/split-flap-display/split-flap-character/split-flap-character.module.scss
- src/layouts/explainer/hero-image/hero-image.module.scss
- src/layouts/explainer/hero-image/hero-image.tsx
- src/variables.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-5442
No updates to code coverage as this ticket only focused on styling
> FDG-5442: Update Hero Section Styling and Spacing

- src/layouts/explainer/sections/national-debt/national-debt.module.scss
Quick spacing fix for design review
> FDG-4873 Added proper spacing for toggle icon on mobile accordion

- src/layouts/explainer/sections/national-debt/national-debt.module.scss
Changed to left padding instead of right
> FDG-4873 changing padding direction to proper

- src/markdown/about-us/faq.mdx
- src/pages/about-us/faq-section/faq-section.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5462
> FDG-5462 Added copy to FAQ page

- src/components/visualization-callout/visualization-callout.module.scss
- src/layouts/explainer/sections/national-debt/national-debt.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5444
> FDG-5444 Update Coloring/Styling Across Charts

- src/layouts/explainer/sections/national-debt/national-debt.jsx
Adjusted spacing for design review comment. 
No change in coverage.
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-4998
> FDG-4998 Adjusted spacing between legend items

- src/layouts/explainer/sections/national-debt/national-debt.jsx
> FDG-4998 Readjusted centering for legends

- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.spec.js
Coverage: 89.26%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-4984
> FDG-4984 Use dynamic values for "How much is a trillion?" accordion title/contents

- src/layouts/explainer/explainer-helpers/explainer-helpers.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5443
> FDG-5443 Update Table of Contents Bold Font for Selected Section

- src/layouts/explainer/explainer-helpers/explainer-helpers.module.scss
> FDG-5443 Using pseudo bold to get around position shifting bug

- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.module.scss
> FDG 5405 Styling changes for design review - Debt Trend Chart

- src/layouts/explainer/sections/national-debt/national-debt.module.scss
> FDG-5405 Defined mobile height

- src/layouts/explainer/hero-image/hero-image.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-5521
No updates to code coverage
> FDG-5521 Mobile view icon size - Updates from design review

- src/layouts/explainer/sections/national-debt/national-debt.jsx
For design review, made chart margins dynamic for better mobile rendering
> FDG-5405 Made chart margins dynamic 

- src/layouts/explainer/sections/national-debt/national-debt.jsx
> FDG-5405 Axis adjustments

- src/components/split-flap-display/split-flap-display.tsx
- src/layouts/explainer/heros/national-debt/national-debt-hero.tsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5638
> FDG-5638 Hero Flip Card Bug

- src/layouts/explainer/hero-image/hero-image.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-5635
No changes to code coverage
> FDG-5635 AFG callout alignment

- src/layouts/explainer/hero-image/hero-image.module.scss
PR based on design review 
resolve the tight gap between the icon and left edge
> FDG-5635 Adjust icon spacing

- src/layouts/explainer/sections/national-debt/national-debt.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-5472
unit test line coverage: 89.19
> FDG-5472 Add Interactions to 'Debt Trends Over Time GDP' Chart

- src/layouts/explainer/sections/national-debt/national-debt.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5653
> FDG-5653 On load, the Fiscal Year and Debt to GDP data points not displaying.

- src/components/announcement-banner/announcement-banner.jsx
- src/components/announcement-banner/announcement-banner.module.scss
- src/components/announcement-banner/announcement-banner.spec.js
- src/components/site-header/mobile-menu/mobile-menu.module.scss
- src/components/site-header/site-header.jsx
- src/pages/__tests__/index.spec.js
- src/pages/index.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-5523
Code Coverage: 89.25%
> FDG 5523 Create Banner Component and Implement DL Sunset Announcement Banner on Homepage

- src/components/site-header/site-header.jsx
- src/components/site-header/site-header.module.scss
No changes in coverage
Changes relate to the following design feedback: 
- A small adjustment to make is that “Debt” should be hex color 666666. Sending it back for this small edit.
> FDG-5246 Changed link color (Design Review) 

- src/layouts/explainer/explainer-helpers/explainer-helpers.js
- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-5449
unit test line coverage: 89.08
> FDG-5449 Update API to FY for Interest-Debt chart

- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-4704
No change to coverage
All other data comments will be address in other tickets
> FDG-4704 Data Review update

- src/layouts/explainer/explainer-test-helper.js
- src/layouts/explainer/multichart/multichart.spec.tsx
- src/layouts/explainer/sections/national-debt/national-debt.jsx
Per Data Review
https://federal-spending-transparency.atlassian.net/browse/FDG-5449
unit test line coverage: 89.08
> FDG-5449 Fix for interest amount rounding

- src/components/site-header/menu-button/menu-button.module.scss
- src/components/site-header/mobile-menu/mobile-menu.module.scss
Addresses the following comments made in design review: 
- The “menu” label is color 000000 and should be 666666.
- The height of each menu label should be about 3rem/48px tall. The labels “Debt” and “Coming soon…” are correct, but the remainder selections are at 50px and need to reduce a bit for visual consistency.
> FDG-5246 Design review adjustments

- documentation/Debt Explainer Data Sources & Methodologies.md
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5657
> FDG-5657 Added documentation folder and Debt Explainer file

- src/components/charts/chart-primary/multichart-renderer.ts
- src/layouts/explainer/multichart/multichart.spec.tsx
- src/layouts/explainer/multichart/multichart.tsx
- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.module.scss
- src/layouts/explainer/sections/national-debt/national-debt.module.scss.d.ts
https://federal-spending-transparency.atlassian.net/browse/FDG-4933
unit test line coverage: 88.94
> FDG-4933 Design Review corrections for mobile

- src/layouts/explainer/sections/national-debt/national-debt.jsx
Addressing the change in how the fiscal year was calculated post 1976
> FDG-5652 GDP Calc Changes

- src/layouts/explainer/sections/national-debt/national-debt.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-4933
unit test line coverage: 88.94
> FDG-4933 Design Review corrections on footer padding

- src/components/split-flap-display/split-flap-display.tsx
- src/layouts/explainer/heros/national-debt/national-debt-hero.tsx
> Flip reload fix 

- env/dev.js
- env/qat.js
- src/components/published-reports/preview/preview.jsx
Correct list of matching topics.  Add duplicate of configuration to QAT.
> FDG-5718 Data Review Revisions

- package-lock.json
- src/layouts/explainer/explainer-test-helper.js
- src/layouts/explainer/explainer.spec.js
- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.spec.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5720
Coverage: 88.97%
> FDG-5720 Update 'Maintaining Nat Debt' Copy to Connect Variable Values to API Fields"

- src/helpers/inflation-adjust/inflation-adjust.ts
- src/layouts/explainer/sections/national-debt/national-debt.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-5725
No updates to coverage
> FDG 5725 Update inflation adjustment 

- src/layouts/explainer/sections/national-debt/national-debt.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5728
> FDG 5728 Updating the copy for the Debt Explainer Page

- src/layouts/explainer/sections/national-debt/national-debt.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5774
> FDG-5774 Mismatch between expense amount and spending amount data updates

- src/components/page-helmet/page-helmet.jsx
- src/components/page-helmet/page-helmet.spec.js
- src/layouts/explainer/explainer.tsx
- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.spec.js
- src/layouts/explainer/sections/sections.jsx
- src/models/ISEOConfig.ts
- src/transform/explainer-pages-config.js
https://federal-spending-transparency.atlassian.net/browse/FDG-5727
unit test line coverage: 89.06%
> FDG-5727 Populate SEO page description variable

- src/components/topics-section/explainer-tile/explainer-tile-helper.js
https://federal-spending-transparency.atlassian.net/browse/FDG-5789
No change to coverage
> FDG-5789 Add alt text for deficit image

- env/dev.js
- gatsby-node.js
https://federal-spending-transparency.atlassian.net/browse/FDG-5651
coverage: 88.41%
> 5651 - Explainer Page to Prod

- src/helpers/simplify-number/simplifyNumber.js
- src/helpers/simplify-number/simplifyNumber.spec.js
> Testing Regex

- src/helpers/simplify-number/simplifyNumber.spec.js
Update unit tests to reflect changes in comma functionality
> update unit tests

- src/transform/explainer-pages-config.js
https://federal-spending-transparency.atlassian.net/browse/FDG-5822
No changes to code coverage
> FDG-5822 Update seo title

- src/layouts/explainer/explainer-helpers/explainer-helpers.js
- src/layouts/explainer/hero-image/hero-image.module.scss
- src/layouts/explainer/hero-image/hero-image.module.scss.d.ts
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-5823
> FDG-5823 Add footnotes placeholder

- package-lock.json
- src/pages/index.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5782
> FDG-5782 Update the DL Sunset banner verbiage on the homepage

- gatsby-node.js
- src/transform/explainer-pages-config.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5830
> FDG-5380 Configure individual explainer pages for prod visibility

- src/layouts/explainer/hero-image/hero-image.module.scss
- src/layouts/explainer/hero-image/hero-image.module.scss.d.ts
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.spec.js
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5333
Coverage: 89.14%
> FDG-5333 Add Hero Image Section

- package-lock.json
- src/components/split-flap-display/split-flap-display.tsx
- src/layouts/explainer/hero-image/hero-image.module.scss
- src/layouts/explainer/hero-image/hero-image.module.scss.d.ts
- src/layouts/explainer/hero-image/hero-image.tsx
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.spec.js
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
- src/transform/explainer-pages-config.js
https://federal-spending-transparency.atlassian.net/browse/FDG-5370
unit test line coverage: 89.23%
> FDG-5370 flipcard display for deficit explainer

- src/layouts/explainer/explainer-components/chart-container/chart-container.jsx
- src/layouts/explainer/explainer-components/chart-container/chart-container.spec.js
- src/layouts/explainer/explainer-helpers/explainer-helpers.js
- src/layouts/explainer/explainer-helpers/national-deficit/national-deficit-helper.js
- src/layouts/explainer/explainer-helpers/national-deficit/national-deficit-test-helper.js
- src/layouts/explainer/explainer.spec.js
- src/layouts/explainer/sections/national-deficit/debt-deficit-difference/debt-deficit-difference.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-by-year.jsx
- src/layouts/explainer/sections/national-deficit/national-deficit.jsx
- src/layouts/explainer/sections/national-deficit/understanding/deficit-comparison-bar-chart/deficit-comparison-bar-chart-helper.js
- src/layouts/explainer/sections/national-deficit/understanding/deficit-comparison-bar-chart/deficit-comparison-bar-chart.jsx
- src/layouts/explainer/sections/national-deficit/understanding/deficit-comparison-bar-chart/deficit-comparison-bar-chart.spec.js
- src/layouts/explainer/sections/national-deficit/understanding/understanding-deficit.jsx
- src/layouts/explainer/sections/national-deficit/understanding/understanding-deficit.spec.js
- src/layouts/explainer/sections/sections.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-5507
Code Coverage: 89.28%
> FDG-5507  Hook in Data for the ‘Deficit Compared to Rev/Spending’ Bar Chart

- documentation/Deficit Explainer Data Sources & Methodologies.md
https://federal-spending-transparency.atlassian.net/browse/FDG-5662
Uploaded 'Deficit Explainer Data Source & Methodologies' doc to the document folder.
Code Coverage: 89.3 %
> FDG-4652 Upload relevant documentation in FDG Dev Public GitHub repository

- src/layouts/explainer/explainer-components/chart-container/chart-container.jsx
- src/layouts/explainer/explainer-components/chart-container/chart-container.module.scss
- src/layouts/explainer/explainer-components/chart-container/chart-container.module.scss.d.ts
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-by-year.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-by-year.spec.js
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5454
Coverage: 89.26%
> FDG-5454 Add Deficit Trend's Bar Chart

- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart-helpers.js
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5605
Coverage: 89.36%
- Also fixed number formatting and chart scaling in this PR
> FDG-5605 Add Interactions to the Deficit Trend Bar Chart

- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart-helpers.js
> FDG-5578 Corrected rounded values

- src/components/secondary-nav/secondary-nav.spec.js
- src/components/secondary-nav/secondary-nav.tsx
- src/components/site-header/mobile-menu/mobile-menu.jsx
- src/components/site-header/site-header.jsx
- src/components/site-header/site-header.spec.js
- src/layouts/explainer/explainer-helpers/explainer-helpers.js
- src/layouts/explainer/explainer.tsx
- src/layouts/explainer/heros/national-debt/national-debt-hero.spec.js
- src/layouts/explainer/heros/national-debt/national-debt-hero.tsx
- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.spec.js
- src/layouts/explainer/social-share/social-share.jsx
- src/layouts/explainer/social-share/social-share.spec.js
- src/models/ISecondaryNav.ts
https://federal-spending-transparency.atlassian.net/browse/FDG-5487
Code coverage: 89.18%
> FDG-5487 Nav & Link Tracking GA Events - Debt Explainer Page

- src/layouts/explainer/social-share/social-share.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-5909
> FDG-5909 Update social share google analytics calls

- src/transform/explainer-pages-config.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5885
> FDG-5885 Populate Related Datasets - Deficit Explainer

- src/layouts/explainer/heros/national-debt/national-debt-hero.tsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5843
> FDG-5843 Added deficit link

- src/transform/endpointConfig.js
Remove pivot view By From for Time Deposit Rates
https://federal-spending-transparency.atlassian.net/browse/FDG-5686
> FDG-5686 New Dataset: SLGS Daily Rate Table build and promote to QAT for Business Review.

- gatsby-node.js
Update bls api call to fix build failures
> Update bls api call

- src/layouts/explainer/heros/national-deficit/national-deficit-hero.spec.js
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-5908
Unit test line coverage: 89.41%
> FDG-5908 Fix start year of previous fiscal year comparison

- src/transform/explainer-pages-config.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5649
> FDG-5649 Make the Deficit Explainer page available in Production

- src/layouts/explainer/sections/national-deficit/understanding/understanding-deficit.jsx
- src/layouts/explainer/sections/national-deficit/understanding/understanding-deficit.spec.js
FDG- 5848
Added API fetch call to dynamically change wording under the Understanding Deficit page (Year, spending, revenue, deficit).
Code coverage 89.35%
> FDG-5848 Add data connection for all evergreen values

- src/layouts/explainer/sections/federal-spending/federal-spending.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-5980
no change to coverage
> FDG-5980 Spending Explainer - callout too close to the accordion

- src/layouts/explainer/hero-image/hero-image.module.scss
- src/layouts/explainer/hero-image/hero-image.module.scss.d.ts
- src/layouts/explainer/heros/federal-spending/federal-spending-hero.spec.js
- src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
Coverage: 89.48%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5698
> FDG-5698 Implement Flip Card Display Counter Component

- src/layouts/explainer/explainer-helpers/national-deficit/national-deficit-helper.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6010
> FDG-6010 Update Copy to Change Link in Learn More Section

- src/transform/endpointConfig.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6012
> FDG-6012 Remove Charts from SLGS Daily Rate Table Dataset

- src/layouts/explainer/heros/national-deficit/national-deficit-hero.spec.js
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6014
> FDG-6014 Deficit Explainer - Hero section copy not matching MAC changes

- src/components/dtg-table/dtg-table-row/dtg-table-row.jsx
- src/components/dtg-table/dtg-table-row/dtg-table-row.spec.js
- src/components/dtg-table/dtg-table.jsx
- src/utils/api-utils.js
https://federal-spending-transparency.atlassian.net/browse/FDG-5993
Code coverage: 89.5%
Master will need to be deployed to qat after this PR is approved and merged
> Fdg 5993 SLGS Daily Rates - Demand Deposit table is displaying '0' value for Daily factor

- src/components/dataset-data/dataset-data.jsx
- src/components/filter-download-container/range-presets/helpers/helper.js
- src/components/filter-download-container/range-presets/helpers/helper.spec.js
- src/components/filter-download-container/range-presets/helpers/test-helper.js
- src/components/filter-download-container/range-presets/range-presets.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6019
Code coverage: 89.52%
Note: will need to be deployed to QAT after approval
> FDG-6019 Daily Rates - Aug 2022 pre-set date displaying just the latest record

- src/layouts/explainer/sections/federal-spending/spending-difference/spending-difference.jsx
FDG-5816
Removed console.log statement
> FDG-5816Add Discretionary Spending illustration to the 'Difference between 'Mandatory, Discretionary and Supplemental Spending' Section

- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5847
> FDG-5847 Update the copy in the hero section for the Deficit Page

- src/transform/explainer-pages-config.js
No changes to coverage
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5650
> FDG-5650 Make the Spending Explainer page available in production

- src/layouts/explainer/sections/federal-spending/overview/spending-overview.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6027
Test coverage lines: 89.48%
> FDG-6027 fix flag color on Spending quote box

- env/dev.js
- env/qat.js
- src/transform/static-metadata/datasets.json
https://federal-spending-transparency.atlassian.net/browse/FDG-5531
Test coverage (lines): 89.47%
> FDG-5531 promote FBP: General Ledger to Prod

- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
- src/layouts/explainer/sections/federal-spending/spending-categories/spending-categories.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6046
> FDG-6046 Alt Text and link missing on US Gov Spending chart

- src/layouts/explainer/sections/federal-spending/overview/spending-overview.jsx
- src/layouts/explainer/sections/federal-spending/overview/spending-overview.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6063
Code coverage: 89.63%
> FDG-6063 Spending Explainer - Incorrect verbiage on Federal Spending Overview section

- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/federal-revenue-trends-over-time.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
No changes to coverage
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6077
> FDG-6077 Revenue Explainer Trends Chart - Design and Copy issues

- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.module.scss
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.module.scss.d.ts
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6058
> FDG-6058 Revenue Explainer Page spacing issue on mobile

- src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6076
Line coverage: 89.68%
> FDG-6076 Fix Hero Pill color for Revenue Explainer

- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6041
I was very confused by the wording in the second bullet point in the above JIRA ticket, hopped on a phone call with Ritesh to verify. Just needed to swap the font sizes for mobile and desktop.
Test coverage: 89%
> swap styles after verifying with Ritesh

- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6041
89%
> add back change

- src/layouts/explainer/hero-image/hero-image.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-5922
89% coverage
> revert custom css changes

- src/components/filter-download-container/range-presets/helpers/helper.js
- src/components/filter-download-container/range-presets/helpers/helper.spec.js
- src/components/filter-download-container/range-presets/range-presets.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6088
reverting changes from: https://federal-spending-transparency.atlassian.net/browse/FDG-6019
> FDG-6088 Monthly datasets displaying blank chart

- src/pages/americas-finance-guide/afg-overview.module.scss
Code Coverage: 89.48, Added more margin to middleHeader
https://federal-spending-transparency.atlassian.net/browse/FDG-5920?atlOrigin=eyJpIjoiMzhlM2Y3NjhmNmQ0NDVkM2E0ZjIyYzA5YTdjNWQzM2MiLCJwIjoiaiJ9
> FDG-5920 Develop Initial AFG Overview Page

- src/transform/explainer-pages-config.js
CC: 89.73
https://federal-spending-transparency.atlassian.net/browse/FDG-5949?atlOrigin=eyJpIjoiYWM3NWQ2MjJhZjEwNDcyYjk3MTBmMDU0ZmYwOTJlNWMiLCJwIjoiaiJ9
> FDG-5949 Make the Revenue Explainer page available in production

- src/components/site-header/mobile-menu/mobile-menu.jsx
- src/components/site-header/mobile-menu/mobile-menu.spec.js
- src/components/site-header/site-header.jsx
- src/components/site-header/site-header.spec.js
- src/transform/explainer-pages-config.js
CC: 89.65
https://federal-spending-transparency.atlassian.net/browse/FDG-5950?atlOrigin=eyJpIjoiYTVhNmViYjk3OTMxNGFlMDhmZDA4Zjc3MTg2NzdmNTgiLCJwIjoiaiJ9
> FDG-5950 Add the Revenue Explainer to Site Nav

- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/federal-revenue-trends-over-time.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-over-time.spec.js
- src/layouts/explainer/sections/government-revenue/government-revenue.jsx
- src/layouts/explainer/sections/government-revenue/key-takeaways/revenue-key-takeaways.jsx
- src/layouts/explainer/sections/government-revenue/key-takeaways/revenue-key-takeaways.spec.js
- src/layouts/explainer/sections/government-revenue/overview/federal-revenue-overview.jsx
- src/layouts/explainer/sections/government-revenue/overview/federal-revenue-overview.spec.js
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.spec.js
Coverage: 89.8%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6001
> FDG-6001 Hook in the Data for Variable Data Elements on the Revenue Explainer page

- src/components/site-header/mobile-menu/mobile-menu.jsx
- src/components/site-header/site-header.jsx
- src/components/topics-section/explainer-tile/explainer-tile-helper.js
- src/layouts/explainer/explainer-helpers/explainer-helpers.js
- src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
- src/layouts/explainer/heros/national-debt/national-debt-hero.tsx
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
- src/layouts/explainer/sections/national-deficit/debt-deficit-difference/debt-deficit-difference.jsx
- src/transform/explainer-pages-config.js
Code Coverage: CC: 89.65
https://federal-spending-transparency.atlassian.net/browse/FDG-5574?atlOrigin=eyJpIjoiNjhmYTZkNzUwMjhjNGM5YWJjN2VmZGE2ZmQ1OTUyNGUiLCJwIjoiaiJ9
> FDG-5574 Change AFG URLs

- src/layouts/explainer/explainer.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-5967?atlOrigin=eyJpIjoiOGNiNjQ3MDllOTdmNDFmMTg2NjJkOGY1NjczZDMzMTYiLCJwIjoiaiJ9
> FDG-5967 Fixed issue with window.location

- src/layouts/explainer/explainer-components/explainer-sub-nav/explainer-sub-nav.module.scss
CC: 89.67 
build-dev ran successfully locally.
https://federal-spending-transparency.atlassian.net/browse/FDG-5926?atlOrigin=eyJpIjoiMmNhMDc4NTZjZmNhNGM2ODk3NTEyODZmZjZjZjM4ZGMiLCJwIjoiaiJ9
link to Slack comments by design: https://federal-spending-transparency.atlassian.net/browse/FDG-5926?atlOrigin=eyJpIjoiMmNhMDc4NTZjZmNhNGM2ODk3NTEyODZmZjZjZjM4ZGMiLCJwIjoiaiJ9
> FDG 5926 Create AFG Sub-Nav Desktop Component - fixed size of overview button

- src/components/site-header/mobile-menu/mobile-menu.jsx
- src/components/site-header/mobile-menu/mobile-menu.spec.js
- src/components/site-header/site-header.jsx
- src/components/site-header/site-header.spec.js
CC: 89.67 
build-dev ran successfully with  up-to-date merge with master.
https://federal-spending-transparency.atlassian.net/browse/FDG-5960?atlOrigin=eyJpIjoiZTAzZDMyM2EyYzdmNGRlOGFmZjAyZTdiMTRiMTZjZjciLCJwIjoiaiJ9
> FDG-5960 Add AFG Overview Page to Site Nav

- src/layouts/explainer/explainer-components/explainer-sub-nav/explainer-sub-nav.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/federal-revenue-trends-and-us-economy.jsx
- src/layouts/explainer/sections/government-revenue/key-takeaways/revenue-key-takeaways.jsx
Added coming soon copy back in from https://github.com/fedspendingtransparency/fiscal-data/pull/199/files
and corrected key takeaway color
> Correct overwritten code

- src/components/topics-section/explainer-tile/explainer-tile.jsx
- src/components/topics-section/topics-section.jsx
resolves the issue reported here:
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1663787624509789
> add back spacing and resolve console error

- src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.jsx
- src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.module.scss
- src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.module.scss.d.ts
Fixed sub nav bar not showing up onload. 
CC: 89.67
> FDG-6000 Create AFG Sub-Nav Component Mobile Version and Add Desktop/Mobile to AFG Overview Page

- src/components/topics-section/explainer-tile/explainer-tile-helper.js
- src/components/topics-section/explainer-tile/explainer-tile.jsx
resolves:
https://federal-spending-transparency.atlassian.net/browse/FDG-6144
> add slashes to end of URL - home page tiles

- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6065
Covers data review ask here: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1664292094327949
> FDG-6065 Added '<1%' language for rounding

- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.jsx
Addressed this data review: https://data-transparency-bfs.slack.com/archives/CKM2LCAF6/p1664224751489779
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5936
> FDG-5936 Hook in the data to the ‘Source of Revenue’ bubble Chart

- src/pages/americas-finance-guide/afg-components/afg-hero/afg-hero.module.scss
CC: 89.44 
All test passes locally
build runs locally
https://federal-spending-transparency.atlassian.net/browse/FDG-6159
> FDG-6101 AFG Hero Fix sizing issue and italic

- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
Coverage: 89.55%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6162
> FDG-6162 Federal Revenue Trends Over Time not keyboard accessible

- src/layouts/explainer/explainer.module.scss
- src/layouts/explainer/explainer.module.scss.d.ts
- src/layouts/explainer/explainer.tsx
CC: 89.63 
Build runs locally
All test passes locally 
https://federal-spending-transparency.atlassian.net/browse/FDG-5967
> FDG-5967 Sub-Nav Component is added to the Explainer

- src/pages/americas-finance-guide/index.jsx
resolves:
https://federal-spending-transparency.atlassian.net/browse/FDG-6160
test coverage 89%
> https://federal-spending-transparency.atlassian.net/browse/FDG-6160

- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6163
> FDG-6163 Federal Revenue Trends Over Time chart tooltip value

- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.module.scss
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.module.scss.d.ts
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6169
> FDG-6169 ''Federal Trends Over Time'' chart on the Revenue Page font styling

- src/layouts/explainer/explainer-helpers/government-revenue/government-revenue-helper.js
- src/layouts/explainer/sections/government-revenue/overview/federal-revenue-overview.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart-helper.js
- src/pages/americas-finance-guide/index.jsx
resolves: https://federal-spending-transparency.atlassian.net/browse/FDG-6171
> fix: fix links

- src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.jsx
- src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.module.scss
- src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.module.scss.d.ts
Everything looks good.
Test passed
> Fdg 6000 Create AFG Sub-Nav Component Mobile Version and Add Desktop/Mobile to AFG Overview Page

- src/pages/americas-finance-guide/afg-components/afg-hero/afg-hero.module.scss
- src/pages/americas-finance-guide/afg-overview.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-6176
> FDG-6176 AFG Overview Screen size issue

- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart-helper.js
fix: update link per slack convo
https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1664480728344209
> fix: update link per slack convo

- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/circle-chart-label.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6136
> fix: revert changes for selecting the next label on enter press

- src/components/site-header/mobile-menu/mobile-menu.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6180
> FDG-6180 Homepage Mobile unreachable links

- src/layouts/explainer/explainer-components/afg-components/compare-section/compare-section.jsx
- src/layouts/explainer/sections/federal-spending/overview/spending-overview.jsx
- src/pages/americas-finance-guide/index.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6190
code coverage: 89.26%
> FDG-6190 AFG Overview and Spending final copy revisions

- src/layouts/explainer/sections/national-debt/national-debt.jsx
Coverage: 89%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6199
> FDG-6199 Debt Explainer page - 'Federal Debt Over Time" not displaying default point

- src/layouts/explainer/sections/national-debt/national-debt.jsx
per discussion here: https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1664917933202719
> FDG-6198 adjust last updated date to reflect latest available chartale date

- src/layouts/explainer/explainer.tsx
- src/layouts/explainer/hero-image/hero-image.tsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.jsx
- src/models/IHeroImage.ts
- src/transform/explainer-pages-config.js
resolves:
https://federal-spending-transparency.atlassian.net/browse/FDG-5918
> FDG-5918: add amount to national debt

- src/components/info-tip/info-tip.jsx
- src/components/info-tip/info-tip.module.scss
- src/components/info-tip/info-tip.module.scss.d.ts
https://federal-spending-transparency.atlassian.net/browse/FDG-5762
cc: 89.24 |
> Fdg 5762  Debt Explainer - Update the interactions for the Glossary Terms tool tip for desktop and mobile

- env/qat.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6115
> FDG-6115 Change SLGS view option to display the current date

- env/qat.js
- src/transform/static-metadata/datasets.json
https://federal-spending-transparency.atlassian.net/browse/FDG-5687
> FDG-5687 Promote New Dataset to Prod: SLGS Daily Rate Table

- src/transform/endpointConfig.js
https://federal-spending-transparency.atlassian.net/browse/FDG-5695
Line coverage: 89.2%
> FDG-5695 Add new dataset: Federal Credit Similar Maturity Rates

- src/components/links/custom-link/custom-link.tsx
Code Coverage: 89.16
Builds locally
analytics.js prefixes each post with "Fiscal Data - ", I just did a hack to remove that in my call.
> FDG-5494 for bug ticket FDG-6228 Fixed duplicate event category

- src/components/charts/chart-primary/multichart-renderer.ts
- src/components/split-flap-display/split-flap-display.spec.js
- src/components/split-flap-display/split-flap-display.tsx
- src/helpers/simplify-number/simplifyNumber.js
- src/helpers/simplify-number/simplifyNumber.spec.js
- src/layouts/explainer/explainer-test-helper.js
- src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
- src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx
- src/layouts/explainer/heros/national-debt/national-debt-hero.tsx
- src/layouts/explainer/multichart/multichart.spec.tsx
- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
- src/layouts/explainer/sections/federal-spending/key-takeaways/spending-key-takeaways.jsx
- src/layouts/explainer/sections/federal-spending/key-takeaways/spending-key-takeaways.spec.js
- src/layouts/explainer/sections/federal-spending/overview/spending-overview.jsx
- src/layouts/explainer/sections/federal-spending/overview/spending-overview.spec.js
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.spec.js
- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart-helpers.js
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
Coverage: 89.21%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6087
Quick note:
- There are a few copy-based values that do not follow our rounding standards. That will require a follow up with data and communications to adjust since there is no data source for those values.
> FDG 6087 Update explainer pages to reflect best practices for rounding

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-6233
> FDG-6233 Spending Explainer - Color issue on Spending Trends Over Time chart - Mobile size

- src/helpers/simplify-number/simplifyNumber.js
- src/layouts/explainer/sections/national-debt/national-debt.jsx
- Fixed two data points on the debt chart where the '.00' was not being appended
> FDG-6087 Data review changes

- src/components/charts/chart-primary/utils.js
- src/helpers/simplify-number/simplifyNumber.js
Reverted back axis change to normal
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6243
> FDG-6243 Debt Explainer - Dollar ($) signs cut off on y-axis

- src/layouts/explainer/sections/national-debt/national-debt.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-5655
Line coverage: 89.15%
> FDG-5655 Improve cursor tracking for Debt Trends Over Time chart

- src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6085
CC: 89.12
Used HexCode hack for opacity for the pill
added fontWeight to span styles for toggle
Builds Locally
All tests passes locally.
> FDG-6085 G-Spending Explainer - Design issues

- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-5778
> FDG-5778 Debt Explainer: Update the 'Federal Debt Trends Over Time, FY 1948 - 2021' chart

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
CC: Same
https://federal-spending-transparency.atlassian.net/browse/FDG-5820
> FDG-5820 Removed bracket notation

- src/layouts/explainer/sections/national-debt/national-debt.jsx
Address Firefox issue identified in qa
https://federal-spending-transparency.atlassian.net/browse/FDG-5655
> FDG-5655 Debt explainer cursor movement fix

- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.spec.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6307
> FDG-6307 U.S. Government Spending, FY 2021 incorrect header

- src/components/accordion/accordion.jsx
- src/layouts/explainer/sections/national-debt/national-debt.jsx
resolves issue reported here:
https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1666364331865449
> fix issue on accordion collapse

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.js
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
CC: 88.99
https://federal-spending-transparency.atlassian.net/browse/FDG-6332
Applied position of line labels with last value of each graph line and add 1 to each to act as a "bottom padding"
Builds locally.
Passes all tests locally.
> FDG-6332 Incorrect position of GDP

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.spec.js
Fixed issue with calculating for inflation, fixed Last updated Date.
https://federal-spending-transparency.atlassian.net/browse/FDG-6300
https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1666722005113209
CC: No change
Builds locally
> FDG-6300 Government Spending and the U.S. Economy" chart/data incorrect

- src/pages/index.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5555
> FDG-5555 Update Verbiage of DL Sunset Banner Post-Nov 1

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.js
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.spec.js
CC: 88.9
https://data-transparency-bfs.slack.com/archives/CKM2LCAF6/p1666991309806239?thread_ts=1666989897.583539&cid=CKM2LCAF6
Added evergreen value to chart header and added tests to make sure they render correctly. 
Builds locally.
Passes all tests locally.
> FDG-5819 Added evergreen value with tests

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.js
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
CC: No Change
Edits per Slack: https://data-transparency-bfs.slack.com/archives/CPA4LFGMC/p1667226308225939
Builds locally
All tests pass locally
> FDG-6353 GDP label falling out of range from view

- src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/folder-illustration-svgs/mobile/folder-tab-edge-right-last-mobile.jsx
- src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.jsx
- src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.module.scss
Adjustment via design feedback: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1667330971829869
> FDG-5479 Deficit Explainer - Update the Surplus Folder Illustration to Include Interactions

- env/uat.js
- src/transform/static-metadata/datasets.json
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5696
> FDG-5696 Promote New Dataset to Prod: Federal Credit Similar Maturity Rates

- src/components/dataset-data/current-report-toggle/current-report-toggle.jsx
- src/components/dataset-data/current-report-toggle/current-report-toggle.spec.js
- src/components/published-reports/download-report/download-report.jsx
- src/components/published-reports/filter-section/filter-section.jsx
- src/components/published-reports/filter-section/filter-section.module.scss
- src/components/published-reports/filter-section/filter-section.module.scss.d.ts
- src/components/published-reports/filter-section/filter-section.spec.js
- src/components/published-reports/test-helper.js
- src/components/published-reports/util/util.js
- src/helpers/dataset-detail/report-helpers.js
- src/helpers/dataset-detail/report-helpers.spec.js
- src/helpers/published-reports/published-reports.js
- src/utils/date-utils.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6236
Line coverage: 88.81%
> FDG-6236 Add day value filter for daily Reports

- src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.jsx
- src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.module.scss
- src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.module.scss.d.ts
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6368
> FDG-6368 Deficit Explainer active and inactive tabbed cards incorrect font

- src/markdown/quick-hits/quick-hits.md
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5327
> FDG-5327 Update URL for Insights Template

- src/pages/americas-finance-guide/americas-finance-guide.spec.tsx
- src/pages/americas-finance-guide/index.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6421
> FDG-6421 Remove comma from between Month and Year

- src/components/published-reports/filter-section/filter-section.jsx
- src/components/published-reports/filter-section/filter-section.spec.js
- src/components/published-reports/preview/preview.jsx
- src/components/published-reports/preview/preview.spec.js
- src/components/published-reports/test-helper.js
- src/components/published-reports/util/util.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6157
Code coverage: 89.19%
> FDG-6157 Whitelist reports for DTS, resolve some issues

- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart-helper.js
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
CC: No Change
https://federal-spending-transparency.atlassian.net/browse/FDG-6420
Builds locally
> FDG-6420 Total Revenue chart design issues

- src/transform/metadata-transform.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6157
Code coverage: 89.19%
> FDG-6157 Minor tweak

- src/pages/americas-finance-guide/index.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6424
No update to coverage
> FDG-6424 AFG Overview -Incorrect text in Dev compared to MAC

- src/layouts/explainer/sections/government-revenue/government-revenue.jsx
CC: No Change
https://federal-spending-transparency.atlassian.net/browse/FDG-6426
Fixed index on Federal Trends section
Builds locally
> FDG-6426 Highlighting issue over Key takeaways or Federal Revenue Trends

- src/layouts/explainer/sections/federal-spending/federal-spending.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/spending-trends.jsx
Coverage: 89.19%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6239
> FDG-6239 Spending Explainer - Update Spending Trends ToC and Section to Remove Coming Soon and Add Final Copy

- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart-helper.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6103
> FDG-6103 Revenue Explainer - Update Sources of Revenue Bubble Chart Footer Copy

- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/federal-revenue-trends-and-us-economy.jsx
- src/layouts/explainer/sections/government-revenue/government-revenue.jsx
CC: 89.19
https://federal-spending-transparency.atlassian.net/browse/FDG-6240
Builds locally
> FDG-6240 Update Revenue Trends ToC and Section

- src/layouts/explainer/explainer.spec.js
- src/layouts/explainer/sections/federal-spending/federal-spending.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/spending-trends.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.js
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.spec.js
Coverage: 89.2%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6256
> FDG-6256 Spending Explainer - Update Spending Trends Section Copy to Connect Data Elements and Remove Experimental Tag

- src/components/accordion/accordion.jsx
- src/components/links/custom-link/custom-link.tsx
- src/hooks/useGAEventTracking.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
- src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.jsx
- src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.spec.js
CC: 89.09
https://federal-spending-transparency.atlassian.net/browse/FDG-5493
Edited useGAEventTracking hook, by adding function to get GA event at any time.
Builds locally
> FDG-5493 GA Event Tracking - Charts

- src/layouts/explainer/hero-image/hero-image.module.scss
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.spec.js
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
Coverage: 89.21%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5906
> FDG-5906 Deficit Explainer - Update Hero Section 'Compared to' Copy/Data

- src/components/site-header/mobile-menu/mobile-menu.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6182
NOTE: The mobile menu is not yet long enough for this functionality to be tested by default, new items will need to added to the menu in mobile-menu.jsx in order to test.
> FDG-6182 Add Scroll to Site Nav on Mobile

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.js
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/federal-revenue-trends-and-us-economy.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.spec.js
CC: 89.05
https://federal-spending-transparency.atlassian.net/browse/FDG-6257
Builds locally
> FDG-6257 Update Revenue Trends Section Copy to Connect Data Elements and Remove Experimental Tag

- src/layouts/explainer/explainer-test-helper.js
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.spec.js
CC: 89.27
https://federal-spending-transparency.atlassian.net/browse/FDG-6382
Added MouseOver and MouseLeave tests for testing chart interactions. Went from 57.26% to 97.46% Line coverage.
Builds locally
> FDG-6382 G-Increase coverage for Deficit Trends bar chart

- src/components/site-header/mobile-menu/mobile-menu.module.scss
No change to coverage
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6182
> FDG-6182 Site Nav - Add Scroll to Site Nav on Mobile

- src/components/home-highlight-cards/highlighted-datasets-config.ts
- src/components/home-highlight-cards/test-helpers.js
CC: 88.77
https://federal-spending-transparency.atlassian.net/browse/FDG-5957
Edited API call, Transformer, and Unit Test.
Builds locally
> FDG-5957 Homepage Card Line Chart

- src/components/anchor-text/anchor-text.tsx
- src/markdown/quick-hits/quick-hits.mdx
CC: No change
https://federal-spending-transparency.atlassian.net/browse/FDG-5314
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1670366107631799
Builds locally
> FDG 5314 Changed anchor to superscript

- src/components/anchor-text/anchor-text.tsx
- src/markdown/quick-hits/quick-hits.mdx
CC: No change
https://federal-spending-transparency.atlassian.net/browse/FDG-5314
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1670366107631799
Builds locally
> FDG-5314 changed anchor to superscript

- src/pages/index.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5689
> FDG-5689 Removed Announcement Banner from homepage

- src/pages/__tests__/index.spec.js
Fixed failing test behind build failure
> FDG-5689 Fixed test

- src/layouts/explainer/social-share/social-share.jsx
CC: 89.39
https://federal-spending-transparency.atlassian.net/browse/FDG-5607
Builds locally
> FDG-5607 LinkedIn SocialShare

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
- src/layouts/explainer/sections/national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
CC: 89.38
https://federal-spending-transparency.atlassian.net/browse/FDG-6530
using helper function "getDateWithoutTimeZoneAdjust" to calculate date.
Builds locally
> FDG-6530 iPhone Safari loading a blank white page

- src/helpers/constants.js
- src/helpers/published-reports/published-reports.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6335
configuration change only.
CC: 89.39%
> FDG-6335 whitelist pub reports for FIP: Interest Cost by Fund

- src/helpers/constants.js
- src/helpers/published-reports/published-reports.js
CC: 89.38
Dataset shows up in search for: "Interest on Uninvested Funds"
https://federal-spending-transparency.atlassian.net/browse/FDG-6336
Builds locally
> FDG-6336 Whitelist FBP: Interest on Uninvested Funds

- src/components/insights-download/insights-download.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-5094
Addresses design review: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1670360799675509
> FDG-5094 Fixed text alignment

- src/transform/endpointConfig.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6463
> FDG-6463 DTS Charting Fix Table 1

- src/markdown/insights/who-owns-the-debt.mdx
> FDG-5302 Removed brackets from Insight Copy

- gatsby-node.js
- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
- src/layouts/explainer/sections/federal-spending/spending-categories/spending-categories.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- static/data/ga-event-tracking/spendingExplainerEventTracking.csv
https://federal-spending-transparency.atlassian.net/browse/FDG-5581
Coverage: 89.22%
> FDG-5581 Spending Explainer - GA Event Tracking - Charts

- static/data/insights-data/who-owns-debt/Allocation_Debt_Held.csv
CC: 89.38
https://federal-spending-transparency.atlassian.net/browse/FDG-6294
Added CSV to "static/data/insights-data/who-owns-the-debt"
Builds locally
> FDG-6294 Add Final Download File to 'Allocation of Held Debt'

- src/components/insights-download/insights-download.module.scss
- src/components/insights-image/insights-image.module.scss
Addressing design review: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1671467517953079
> FDG-5309 Add 'Top 10 Owners' SVG's 

- src/components/footnote/footnote.module.scss
cc: no change
Changes via slack: 
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1671465556567599
Ticket: 
https://federal-spending-transparency.atlassian.net/browse/FDG-6408
Builds Locally
> FDG-6408 Spacing fixed for bottom margin

- src/layouts/feature/dsm/dsm.module.scss
- src/layouts/feature/feature.spec.tsx
- src/layouts/feature/feature.tsx
- src/markdown/insights/who-owns-the-debt.mdx
https://federal-spending-transparency.atlassian.net/browse/FDG-5324
Coverage: 89.23%
> Fdg 5324 Add Final Copy and SEO/Alt Text

- src/components/insights-download/insights-download.module.scss
- src/components/insights-image/insights-image.module.scss
Addresses Design comments: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1671483552629029?thread_ts=1671467517.953079&cid=CRFQA2DM1
> FDG-5309 download padding and image width change

- src/components/insights-download/insights-download.spec.js
- src/components/insights-download/insights-download.tsx
CC: 89.26
https://federal-spending-transparency.atlassian.net/browse/FDG-6559
Builds locally
> FDG-6559 changed button to anchor for hover hint

- src/layouts/explainer/heros/national-deficit/national-deficit-hero.spec.js
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6246
> FDG-6246 Update Deficit Explainer page for rounding issue

- documentation/Debt Explainer Data Sources & Methodologies.md
- documentation/Deficit Explainer Data Sources & Methodologies.md
- documentation/Revenue Explainer Data Sources & Methodologies.md
- documentation/Spending Explainer Data Sources & Methodologies.md
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6483
> FDG-6483 Update DS&M Files on Github

- src/components/insights-download/insights-download.module.scss
- src/components/insights-image/insights-image.module.scss
- src/layouts/feature/feature.module.scss
- static/images/insights-images/who-owns-data/2022-11-23_WOTD_Allocation-of-Held-Debt_desktop.svg
- static/images/insights-images/who-owns-data/2022-11-23_WOTD_Allocation-of-Held-Debt_mobile.svg
- static/images/insights-images/who-owns-data/2022-11-23_WOTD_Top-10-Owners-US-Debt_desktop.svg
- static/images/insights-images/who-owns-data/2022-11-23_WOTD_Top-10-Owners-US-Debt_mobile.svg
- Margin on download and image components made to match text elements
- Images cropped to make margin calc easier / more accurate
- Alignment consistent across device sizes
> FDG-5309 Margin and Image position / crop adjustments

- src/layouts/explainer/explainer-helpers/federal-spending/federal-spending-helper.js
- src/layouts/explainer/explainer-helpers/government-revenue/government-revenue-helper.js
CC: 89.46
https://federal-spending-transparency.atlassian.net/browse/FDG-6289
Builds locally
> FDG-6289 Revenue/Spending - Copy Update - Update BLS link in DS&Ms

- src/components/calendar-entries/calendar-entries-live-data-tests.spec.js
- src/components/calendar-entries/calendar-entries.jsx
- src/components/calendar-entries/calendar-entries.spec.js
No changes in coverage
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6454
> FDG-6454 Load Release calendar data dynamically

- src/layouts/explainer/sections/national-debt/national-debt.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6248
> FDG-6248 Debt Explainer - On desktop illustration's "Year 1" and "Year 2" are wrapping to the next line

- src/components/insights-download/insights-download.spec.js
- src/components/insights-download/insights-download.tsx
CC: No change
https://federal-spending-transparency.atlassian.net/browse/FDG-6578
Builds locally
> FDG-6578 'Top 10 Owners' SVG's capitalization of ".csv" issue

- src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.jsx
- src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.spec.js
- src/layouts/explainer/explainer.tsx
CC: 89.87
https://federal-spending-transparency.atlassian.net/browse/FDG-6488
Builds locally
> FDG-6488 Increase coverage for the mobile explainer sub nav

- src/components/site-header/mobile-menu/mobile-menu.jsx
- src/components/site-header/mobile-menu/mobile-menu.spec.js
CC: 89.61
https://federal-spending-transparency.atlassian.net/browse/FDG-6489
Added click events to buttons that didn't have any coverage
Builds locally
> FDG-6489 Increase coverage for the site header mobile menu

- src/layouts/explainer/sections/national-debt/national-debt.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6497
New link: /americas-finance-guide/national-debt/#interest-rate-and-total-debt-chart
> FDG-6497 Debt Explainer - Create Anchor Point for Maintaining the National Debt Section

- .eslintrc.js
- src/transform/endpointConfig.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6601
> FDG-6601 Update sort for Daily Activity table of Sched of Fed Debt by Day

- src/layouts/explainer/sections/national-debt/national-debt.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6635
> FDG-6635 Anchor Point for Maintaining the National Debt Section is not working correctly from other pages like Overview etc

- env/dev.js
- env/prod.js
- env/qat.js
- env/stg.js
- env/uat.js
- src/layouts/explainer/explainer-helpers/explainer-helpers.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6605
> FDG-6605 Update Social Share Urls

- src/layouts/explainer/sections/national-debt/key-takeaways/national-debt-key-takeaways.jsx
- src/layouts/explainer/sections/national-debt/key-takeaways/national-debt-key-takeaways.spec.js
- src/layouts/explainer/sections/national-debt/national-debt.jsx
Coverage: 89.94%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6272
> FDG-6272 Refactor National Debt - Key Takeaways Section

- gatsby-node.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6723
> FDG-6723 New Inflation Data is Fetched from the BLS API

- src/layouts/explainer/explainer-helpers/explainer-charting-helper.js
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart-helper.js
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
Coverage: 90.08%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6717
> FDG-6717 Federal Revenue and the U.S. Economy (GDP) Percentage on y-axis not showing %

- src/components/api-documentation/getting-started/getting-started.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6523
> FDG-6523 API Documentation - Update Page based on MAC Changes

- src/components/site-footer/site-footer.jsx
- src/components/site-footer/site-footer.spec.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6616
> FDG-6616 Site Footer - Remove Data Lab Link

- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart-helper.js
- src/layouts/explainer/sections/national-debt/national-debt.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6465
> FDG-6465 AFG Debt Explainer - Apply Copy Updates

- env/qat.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6737
> FDG-6737 Update QAT environment configurations

- src/components/api-documentation/getting-started/getting-started.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6769
> FDG-6769 API Documentation - Update Page has discrepancies when compared with the API Documentation MAC.

- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.spec.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6466
> FDG-6466 Changed FYTD -> FY, Spending Explainer Copy Updates

- src/components/site-header/site-header.jsx
- src/layouts/explainer/explainer-components/explainer-sub-nav/explainer-sub-nav.jsx
- src/layouts/explainer/explainer-helpers/government-revenue/government-revenue-helper.js
- src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/federal-revenue-trends-and-us-economy.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart-helper.js
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
- src/layouts/explainer/sections/government-revenue/overview/federal-revenue-overview.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart-helper.js
- static/data/ga-event-tracking/revenueExplainerEventTracking.csv
Coverage: 90.04%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6153
> FDG-6153 Revenue Explainer - GA Event Tracking - Nav & Links

- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.jsx
Added event to irs link per data review
No changes to coverage
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6153
> FDG-6152 Added event - Revenue Explainer GA Events

- src/components/combo-select/combo-select-test-helper.js
- src/components/combo-select/combo-select.jsx
- src/components/combo-select/combo-select.module.scss
- src/components/combo-select/combo-select.spec.js
- src/components/download-wrapper/download-wrapper.jsx
- src/components/download-wrapper/download-wrapper.module.scss
- src/components/download-wrapper/download-wrapper.module.scss.d.ts
- src/components/download-wrapper/download-wrapper.spec.js
- src/components/filter-download-container/user-filter/user-filter.module.scss
- src/components/filter-download-container/user-filter/user-filter.module.scss.d.ts
- src/components/filter-download-container/user-filter/user-filter.spec.tsx
- src/components/filter-download-container/user-filter/user-filter.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6824
Fix design defects noted in ticket.
Increase line coverage for combo-select control.
Move some test data into separate helper file.
live cov: 89.62%
> FDG-6824 Fix design issues with TRRE user filter

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart-helper.js
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.jsx
Coverage: 89.51%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6155
> FDG-6155 Revenue Explainer - GA Event Tracking - Charts

- gatsby-config.js
- src/components/links/custom-link/custom-link.tsx
- src/hooks/useGAEventTracking.jsx
- src/layouts/explainer/data-sources-methodologies/data-sources-methodologies.tsx
- src/layouts/explainer/explainer-components/afg-components/afg-topic-section/afg-topic-section.jsx
- src/layouts/explainer/explainer-components/explainer-sub-nav/explainer-sub-nav.jsx
- src/pages/americas-finance-guide/index.jsx
- static/data/ga-event-tracking/AFGOverviewEventTracking.csv
Coverage: 89.55%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6449
> FDG-6449 AFG Overview - GA Event Tracking

- .eslintrc.js
- package-lock.json
- package.json
- src/components/buttons/buttons.spec.ts
- src/components/charts/bar/bar.jsx
- src/components/checkbox/checkbox.jsx
- src/components/combo-select/combo-select.jsx
- src/components/dataset-data/dataset-chart/dataset-chart.spec.js
- src/components/dataset-data/table-section-container/dynamic-config/dynamicConfig.jsx
- src/components/home-highlight-cards/home-highlight-card/home-highlight-card.tsx
- src/components/home-highlight-cards/home-highlight-card/sparkler/sparkler.tsx
- src/components/info-tip/info-tip.jsx
- src/components/links/custom-link/custom-link.tsx
- src/components/pagination/paging-options-menu.bypass.js
- src/components/secondary-nav/secondary-nav.tsx
- src/components/select-control/select-control.jsx
- src/components/site-header/site-header.jsx
- src/helpers/simplify-number/simplifyNumber.spec.js
- src/html.js
- src/layouts/explainer/multichart/multichart.tsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.jsx
- src/layouts/explainer/sections/national-debt/national-debt.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
- src/layouts/explainer/social-share/social-share.jsx
- src/pages/datasets/datasets.spec.js
Coverage: 89.61%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6615
> FDG-6615 Address existing 508 compliance / accessibility linting errors

- gatsby-node.js
- src/components/dataset-data/dataset-data.jsx
- src/components/filter-download-container/range-presets/range-presets.jsx
- src/components/filter-download-container/range-presets/range-presets.spec.js
- src/models/IDatasetConfig.ts
- src/transform/metadata-transform.js
- src/transform/static-metadata/datasets.json
https://federal-spending-transparency.atlassian.net/browse/FDG-6735
Coverage: 89.52%
> FDG-6735 SLGS Daily Rate Table - Update Default Date Range to Latest Available Date

- src/components/combo-select/combo-select.jsx
- src/components/combo-select/combo-select.module.scss
- src/components/select-control/select-control.module.scss
- src/components/select-control/select-control.module.scss.d.ts
https://federal-spending-transparency.atlassian.net/browse/FDG-6824
Styling changes only. Test coverage not impacted.
> FDG-6824 TRRE filter match styling: fix inconsistencies with iOS

- src/components/select-control/select-control.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6855
> FDG-6855 Fix DDP unclickable buttons issue

- src/components/charts/chart-primary/multichart-renderer.ts
- src/components/charts/chart-primary/mutichart-renderer.spec.ts
- src/layouts/explainer/multichart/multichart.tsx
- src/layouts/explainer/sections/national-debt/national-debt.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-6303
Slow down the timeout intervals and css animation timings for chart area transition animation and left-to-right selection demonstration.
MISC:
Remove superfluous code block for a condition which there is no intention to meet. Creates a small increase in code coverage. Fix several typescript warnings and errors for incorrectly typed variables in multichart-renderer.ts
Line coverage: 89.58%
> FDG-6303 Update 'Interest Rate and Total Debt' Animation Interaction

- package-lock.json
- src/hooks/hookDataMocks/mockBEAGDPData.js
- src/hooks/hooks.spec.js
> Improved BEA data hook coverage

- src/layouts/explainer/explainer-components/afg-components/afg-topic-section/afg-topic-section.jsx
- src/pages/americas-finance-guide/index.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6874
> FDG-6974 AFG Overview -Incorrect GA Event Tracking for "Click on the link" explainer pages

- src/components/info-tip/info-tip.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6354
> FDG-6354 Dataset Search info icons functionality disabled

- src/components/exchange-rates-converter/exchange-rates-banner/exchange-rates-banner.module.scss
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss.d.ts
- src/layouts/currency-exchange-rates-converter/index.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6630
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1676671327375609
> FDG-6630 Design changes

- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6853
> FDG-6853 Debt Explainer - Update X-Axis Behaviors for Federal Debt Trends Over Time (GDP) Chart

- src/components/topics-section/homepage-tile/homepage-tile-helper.js
- src/layouts/explainer/explainer-components/afg-components/compare-section/compare-section.jsx
- src/layouts/explainer/hero-image/hero-image.tsx
- src/layouts/explainer/heros/federal-spending/federal-spending-hero.spec.js
- src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
- src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx
- src/layouts/explainer/heros/hero-helper.tsx
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
- src/layouts/explainer/sections/federal-spending/key-takeaways/spending-key-takeaways.jsx
- src/layouts/explainer/sections/federal-spending/overview/spending-overview.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/federal-revenue-trends-over-time.jsx
- src/layouts/explainer/sections/government-revenue/overview/federal-revenue-overview.jsx
- src/layouts/explainer/sections/government-revenue/overview/federal-revenue-overview.spec.js
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart-helper.js
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.jsx
- src/pages/americas-finance-guide/index.jsx
- src/utils/rounding-utils.spec.js
- src/utils/rounding-utils.ts
Test Coverage: 90.1%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6617
> FDG-6617 Reference getShortForm() from util file instead of hero helper, introduce dynamic rounding

- gatsby-node.js
- src/components/dataset-data/dataset-data.jsx
- src/components/filter-download-container/range-presets/range-presets.jsx
- src/components/filter-download-container/range-presets/range-presets.spec.js
- src/models/IDatasetConfig.ts
- src/transform/metadata-transform.js
- src/transform/static-metadata/datasets.json
https://federal-spending-transparency.atlassian.net/browse/FDG-6840
Test coverage: 90.11%
> FDG-6840 TRRE - Update Default Date Range to Latest Available Date

- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.module.scss
- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.module.scss.d.ts
- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.tsx
- src/components/exchange-rates-converter/quarter-selection-box/quarter-selection-box.tsx
- src/components/select-control/select-control.jsx
- src/components/select-control/select-control.module.scss
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter-helper.js
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss.d.ts
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.spec.js
- src/layouts/currency-exchange-rates-converter/index.tsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-over-time.spec.js
Coverage: 90.14%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6631
> FDG-6631 Add Data/Interactions for Year/Quarter/Effective Date Fields

- src/pages/americas-finance-guide/americas-finance-guide.spec.tsx
- src/pages/americas-finance-guide/index.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6886
Use getShortForm(). Update unit test.
Line coverage: 90.11%
> FDG-6886 AFG Overview - Update Debt Header Section

- src/components/exchange-rates-converter/exchange-rates-banner/exchange-rates-banner.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-6891
> FDG-6891 Missed requirements for Develop Initial Exch Rates Converter Tool Page ticket

- gatsby-node.js
- src/components/dataset-data/chart-table-toggle/chart-table-toggle.jsx
- src/components/dataset-data/table-section-container/set-no-chart-message.jsx
- src/components/dataset-data/table-section-container/set-no-chart-message.spec.js
- src/components/dataset-data/table-section-container/table-section-container.jsx
- src/components/dataset-data/table-section-container/table-section-container.spec.js
- src/components/dataset-data/table-section-container/testHelpers.js
- src/components/dtg-table/test-data.js
- src/components/filter-download-container/user-filter/user-filter.spec.tsx
- src/components/filter-download-container/user-filter/user-filter.tsx
- src/components/metadata-tab/metadata-tab.jsx
- src/models/IDatasetApi.ts
- src/transform/endpointConfig.js
- src/transform/metadata-transform.js
- src/transform/metadata-transform.spec.js
- src/transform/transform-mock-data.json
https://federal-spending-transparency.atlassian.net/browse/FDG-6827
Load options for user filter at build time. Add logic for detecting when no rows are available and for relaying configurable message. MISC: minor code cleanup
Line coverage: 90.14% (previously 90.09)
> FDG-6827 Add Error Text to Table/Chart tabs for No Filtered Data Scenario

- gatsby-node.js
Explicitly specify customRangePreset on Datasets node type. Fix a warning related to looping over asynchronous code. Line coverage: 90.24
> Troubleshoot GraphQL Build issue

- src/components/site-header/site-header.jsx
- src/components/site-header/site-header.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6931
Test coverage: 90.26%
> FDG-6931 Site Navigation (Desktop) - Tabbing Out of Last Mega Menu Site Nav Element Dismisses Mega Menu

- src/layouts/explainer/explainer.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-6699
Test coverage: 90.28
> FDG-6699 Across Explainer Pages - Ensure Table of Contents Button Remains Visible on Mobile

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6363
Code coverage: 90.19%
> FDG-6363 Spending Explainer - Add Enhanced Keyboard Accessibility Interactions to GDP Chart > Total Spending View

- env/uat.js
- src/transform/endpointConfig.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6661
No change in coverage 
The related datasets listed in the provided file currently do not exist yet on our site which caused build errors, so I removed them from the config
> FDG-6661 New Dataset Created in UAT - TCIR: Annual

- gatsby-node.js
- src/transform/metadata-transform.js
- src/transform/metadata-transform.spec.js
Coverage: 90.21%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6950
> FDG-6950 Add Topic Filter to Exchange Rates Dataset

- src/components/topics-section/homepage-tile/homepage-tile-helper.js
- src/components/topics-section/homepage-tile/homepage-tile.jsx
**PR for FDG-6639 should be completed and merged first**
https://federal-spending-transparency.atlassian.net/browse/FDG-6640
> FDG-6640 Add XR Converter Tile to Homepage New Tools Section

- src/components/api-documentation/getting-started/getting-started.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6825
> FDG-6825 API Documentation - Update Copy to Correct 'What is an API?' Verbiage

- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.tsx
- src/layouts/currency-exchange-rates-converter/index.tsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6632
Refer to ticket comments for further info
Addressed Concerns:
- The data entry for a given currency in a given year / quarter with the latest effective date is shown
- Pop up message from input component when entering number with decimals no longer appears
> FDG-6632 Exchange Rates Data Review

- src/layouts/currency-exchange-rates-converter/index.tsx
Thread: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1679943277055169
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6632
> FDG-6632 Data review 

- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6927
Thread: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1679944230407479
> FDG-6927 Design Review

- gatsby-node.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6781
> FDG-6781 Make Page Available in Production

- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.module.scss
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6632
Thread: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1680014564127669
> FDG-6632 Design Review

- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.tsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7067
> FDG-7067 US Dollar field on the Exchange Rates Converter tool is accepting char "e"

- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.spec.js
- src/layouts/currency-exchange-rates-converter/index.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6634
> FDG-6634 Update U.S. Dollar text

- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7082
> FDG-7082 Legal Disclaimer title font color issue

- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter-helper.js
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.spec.js
- src/layouts/currency-exchange-rates-converter/index.tsx
Coverage: 90.20%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7051
> FDG-7051 Correct Number of Decimal Places for Tool

- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.spec.js
- src/layouts/currency-exchange-rates-converter/index.tsx
Coverage: 90.21%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7080
> FDG-7080 Clear Foreign Currency Entry Field when User Clears US Dollar Entry Field and Vice Versa

- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter-helper.js
- src/layouts/currency-exchange-rates-converter/index.tsx
Coverage: 90.20%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7051
> FDG-7051 Correct Number of Decimal Places for Tool 

- src/components/combo-select/combo-select.jsx
- src/components/combo-select/combo-select.spec.js
- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-7026
Test Coverage: 90.14
> FDG-7026 Ensure Foreign Currency Selection Drop-down Dismisses when Tabbing into Foreign Currency Entry Field

- src/transform/endpointConfig.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7098
> FDG-7098 TCIR Annual - update sort for all tables

- env/uat.js
- src/transform/static-metadata/datasets.json
https://federal-spending-transparency.atlassian.net/browse/FDG-6675
> FDG-6675 Promote New Dataset to Prod - TCIR: Semi-Annual

- src/components/site-header/mobile-menu/mobile-menu.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-7024
> FDG-7024 Table of Contents and Overview are covering up the mobile site navigation bar.

- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter-helper.js
- src/layouts/currency-exchange-rates-converter/index.tsx
…ailable
(cherry picked from commit 2100f3d0103461115dbc9c88a937990068ac725d)
> merging cherry picked changes from xr-tool-fix (FDG-7112)

- env/uat.js
- src/transform/endpointConfig.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6696
> FDG-6696 New Dataset Created in UAT - TCIR: Quarterly

- env/uat.js
- src/transform/endpointConfig.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6709
> FDG-6709 New Dataset Created in UAT - TCIR: Monthly

- src/components/secondary-nav/secondary-nav.spec.js
- src/components/secondary-nav/secondary-nav.tsx
- src/components/table-of-contents/toc-button/toc-button.jsx
- src/components/table-of-contents/toc-button/toc-button.module.scss
- src/layouts/explainer/explainer.tsx
- src/models/ISecondaryNav.ts
https://federal-spending-transparency.atlassian.net/browse/FDG-6988
Line coverage: 90.18%
> FDG-6988 Explainers should scroll to TOC in mobile

- src/components/combo-select/combo-select.jsx
- src/components/combo-select/combo-select.module.scss
- src/components/combo-select/combo-select.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7103
Coverage: 90.15%
> FDG-7103 Foreign currency field scroll bar is not working.

- src/components/secondary-nav/secondary-nav.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7126
Line coverage: 90.19%
> FDG-7126 Explainers should scroll to TOC even in iOS

- src/transform/endpointConfig.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7145
> FDG-7145 TCIR Quarterly - Update Sort for All Tables

- src/components/site-footer/site-footer.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6797
> FDG-6797 508 Compliance - Add aria label to Fiscal Data logo in site footer

- src/components/charts/chart-primary/multichart-renderer.ts
- src/layouts/explainer/multichart/multichart.tsx
- src/layouts/explainer/sections/national-debt/national-debt.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6890
> FDG-6890 Debt Explainer - Update 'Interest Rate and Total Debt' Chart to Pare Back Animation to Only Dot/Line

- src/components/calendar-entries/calendar-entry/calendar-entry.jsx
- src/components/calendar-entries/calendar-entry/calendar-entry.module.scss
This PR covers both release calendar tickets 
https://federal-spending-transparency.atlassian.net/browse/FDG-6937
https://federal-spending-transparency.atlassian.net/browse/FDG-6808
> FDG-6937 Release Calendar - Apply Stylings to Button and FDG-6808 508 Compliance - Refactor release calendar entry component

- src/components/calendar-entries/calendar-entries.jsx
- src/components/calendar-entries/release-calendar-service.ts
- src/components/calendar-entries/use-release-calendar-entries-updater-hook.ts
Please refer to the comment I left on the ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7095 for the background of this PR
> FDG 7095 Removed non functional Release Calendar code, minor tweaks / improvements

- src/components/calendar-entries/release-calendar-service.ts
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7212
> FDG-7212 Remove a console log from appearing in the console in QAT

- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.module.scss
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-6276
Failed data review
Line coverage: 90.22%
> FDG-6276 refactor debt trends - add dotted line

- package-lock.json
- src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.module.scss
Issue arose and was resolved after smoke testing in the prod-inactive env and before route-swing to prod-active.
> Merge FDG-7237 changes into release branch

- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/chart-toggle-switch.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6806
> FDG-6806 508 Compliance - Add explicit or implicit label to U.S Government Spending Chart

- src/components/datasets/filters/filterPublisherWrapper/filterPublisher.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6810
> FDG-6810 508 Compliance - Adjust color contrast on 'publisher' labels on dataset search page

- src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
- src/layouts/explainer/sections/federal-spending/spending-difference/spending-difference.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.module.scss.d.ts
https://federal-spending-transparency.atlassian.net/browse/FDG-6883
> FDG-6883 AFG Spending Explainer - Apply Copy Updates

- src/components/pagination/paging-options-menu.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.module.scss.d.ts
https://federal-spending-transparency.atlassian.net/browse/FDG-6811
not test coverage change
> Fdg 6811 508 Compliance - Replace button's aria-controls value or remove it - API Documentation Page

- src/components/download-modal/download-modal.spec.js
- src/components/persist/download-persist/downloads-persist.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7138
Line coverage: 90.23%
> FDG-7138 fix Cancel Download button

- src/layouts/explainer/explainer-helpers/explainer-charting-helper.js
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-over-time.spec.js
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.jsx
- src/layouts/explainer/sections/national-debt/breaking-down-the-debt/intragovernmental-holdings-chart/intragovernmental-holdings-chart.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
- src/layouts/explainer/sections/national-deficit/understanding/deficit-comparison-bar-chart/deficit-comparison-bar-chart.jsx
Coverage: 90.23%
Ticket: Add appropriate aria labels to generated chart parent svgs
> FDG-7234 Add appropriate aria labels to generated chart parent svgs

- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.jsx
https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1683663168553949
> Update glossary term

- src/components/datasets/filters/filters.jsx
- src/components/datasets/filters/filters.spec.js
- src/components/datasets/filters/searchFilterSummary/searchFilterSummary.jsx
- src/components/datasets/filters/searchFilterSummary/searchFilterSummary.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7147
test coverage: 90.33
> Fdg 7147 Always pass id into onGroupReset instead of object

- src/layouts/explainer/explainer-helpers/national-deficit/national-deficit-helper.js
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-by-year.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-by-year.spec.js
- src/layouts/explainer/sections/national-deficit/deficit-key-takeaways/deficit-key-takeaways.jsx
- src/layouts/explainer/sections/national-deficit/deficit-key-takeaways/deficit-key-takeaways.spec.js
- src/layouts/explainer/sections/national-deficit/national-deficit.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6881
Code coverage: 90.34
Also did refactoring of Deficit Key Takeaways
> Fdg 6881 AFG Deficit Explainer - Apply Copy Updates

- src/components/glossary/glossary-definition/glossary-definition.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-7298
no test changes
> FDG-7298 - Hide Official Definition Text

- src/components/page-helmet/page-helmet.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7006
> FDG-7006 Set up GA4 to begin data collection

- src/components/glossary/glossary-list/glossary-list-container.module.scss
- src/components/glossary/glossary-term/glossary-popover-definition.jsx
- src/components/glossary/glossary-term/glossary-popover-definition.module.scss
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1684871233096699
https://federal-spending-transparency.atlassian.net/browse/FDG-6999
> FDG-6999 Design Review Updates

- env/qat.js
- env/uat.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7266
No change in coverage 
Experimental tag was removed in an earlier pr
> FDG-7266 Experimental tag is removed from Glossary feature

- src/components/dtg-table/dtg-table-row/dtg-table-row.jsx
- src/components/dtg-table/dtg-table-row/dtg-table-row.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7381
Coverage: 90.33%
> FDG-7381 Modify Column Spacing in TCIR Monthly Interest Rates in UAT

- src/transform/endpointConfig.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7387
> FDG-7387 Adjust the Custom Sort Order - TCIR Semi Annual

- src/components/datasets/search-results/search-results-helper.js
- src/components/datasets/search-results/search-results-helper.spec.js
- src/components/datasets/search-results/search-results.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7319
> FDG-7319 - Update default sort on Dataset Search page

- env/uat.js
- src/transform/static-metadata/datasets.json
https://federal-spending-transparency.atlassian.net/browse/FDG-6698
> FDG- 6698 Promote New Dataset to Prod - TCIR: Quarterly

- src/transform/endpointConfig.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7447
no testing changes
> FDG-7387-7447 TCIR Semi-Annual Adjust Custom Sort Order in All Environments

- src/components/dataset-card/dataset-card.module.scss
- src/components/dataset-card/dataset-card.module.scss.d.ts
- src/components/dataset-card/dataset-card.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7250
> FDG-7250 Add styling for focused dataset cards

- env/uat.js
- src/transform/static-metadata/datasets.json
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6673
> FDG-6673 Promote New Dataset to Prod - TCIR: Annual

- src/components/accordion/accordion.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7414
> FDG-7414 Create GA4 events for Explainer - accordions

- src/components/links/custom-link/custom-link.tsx
- src/components/links/external-link/external-link.tsx
- src/layouts/explainer/explainer-components/learn-more/learn-more-section.jsx
- src/layouts/explainer/explainer-helpers/national-deficit/national-deficit-helper.js
- src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
- src/layouts/explainer/sections/national-deficit/debt-deficit-difference/debt-deficit-difference.jsx
- src/layouts/explainer/sections/national-deficit/deficit-and-surplus-causes/deficit-and-surplus-causes.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-by-year.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
- src/layouts/explainer/sections/national-deficit/deficit-key-takeaways/deficit-key-takeaways.jsx
- src/layouts/explainer/sections/national-deficit/understanding/deficit-comparison-bar-chart/deficit-comparison-bar-chart.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7418
> FDG-7418 Create GA4 events for Explainer - Deficit

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.jsx
- src/layouts/explainer/sections/national-debt/breaking-down-the-debt/breaking-down-the-debt.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7416
Coverage: 90.08%
> FDG-7416 Create GA4 events for Explainer - chart hover

- src/layouts/currency-exchange-rates-converter/index.tsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7408
> FDG-7408 Create GA4 events for XR tool - hover

- src/layouts/explainer/explainer-helpers/national-debt-helper.js
- src/layouts/explainer/heros/national-debt/national-debt-hero.tsx
- src/layouts/explainer/sections/national-debt/breaking-down-the-debt/breaking-down-the-debt.jsx
- src/layouts/explainer/sections/national-debt/breaking-down-the-debt/intragovernmental-holdings-chart/intragovernmental-holdings-chart.jsx
- src/layouts/explainer/sections/national-debt/funding-programs-and-services/funding-programs-and-services.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart-helper.js
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.jsx
- src/layouts/explainer/sections/national-debt/national-debt.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7417
Code coverage: 90.31
> FDG-7417 Create GA4 events for Explainer - Debt

- src/layouts/explainer/explainer-helpers/government-revenue/government-revenue-helper.js
- src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart-helper.js
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
- src/layouts/explainer/sections/government-revenue/overview/federal-revenue-overview.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart-helper.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7419
> FDG 7419 Create GA4 events for Explainer - Revenue

- src/layouts/explainer/explainer-helpers/federal-spending/federal-spending-helper.js
- src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
- src/layouts/explainer/sections/federal-spending/overview/spending-overview.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7420
> FDG-7420 Create GA4 events for Explainer - Spending

- src/components/dataset-card/dataset-card.tsx
- src/components/dataset-data/chart-table-toggle/chart-table-toggle.jsx
- src/components/dataset-data/report-data-toggle/report-data-toggle.jsx
- src/components/datatable-select/datatable-select.jsx
- src/components/download-modal/download-modal-item/download-modal-item.jsx
- src/components/download-modal/download-modal.jsx
- src/components/download-sticky/download-sticky.jsx
- src/components/filter-download-container/range-presets/helpers/helper.js
- src/components/published-reports/preview/preview.jsx
- src/components/select-control/select-control.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7401
no changes in test coverage
> Fdg 7401 - Create GA4 events for DDP 

- src/components/datasets/filters/dateFilterTabs/dateFilterTabs.jsx
- src/components/datasets/filters/filterRow/filterRow.jsx
- src/components/datasets/filters/filterTimeRange/filterTimeRange.jsx
- src/components/datasets/filters/filters.jsx
- src/components/datasets/search-field/search-field.jsx
- src/components/datasets/search-results/search-results.jsx
- src/components/datasets/topics/topic/topic.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7402
> FDG-7402 - Create GA4 events for Dataset Search

- env/qat.js
- package-lock.json
- package.json
- src/components/data-table/data-table.tsx
- src/components/dataset-data/table-section-container/table-section-container.jsx
- src/components/dtg-table/dtg-table.jsx
- src/components/dtg-table/dtg-table.module.scss
- src/components/dtg-table/dtg-table.module.scss.d.ts
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7299
Coverage: 90.31%
> FDG-7299 Implement experimental DDP table display using react-table

- src/layouts/explainer/explainer-components/afg-components/afg-topic-section/afg-topic-section.jsx
- src/pages/americas-finance-guide/index.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7422
no changes in testing coverage
> FDG-7422 Create GA4 events for AFG Overview

- src/components/site-footer/site-footer.jsx
- src/components/site-header/menu-dropdown/menu-dropdown.jsx
- src/components/site-header/mobile-menu/mobile-menu-dropdown/mobile-menu-dropdown.jsx
- src/components/site-header/mobile-menu/mobile-menu.jsx
- src/components/site-header/site-header.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7406]
Coverage: 90%
> FDG-7406 Create GA4 events for Sitewide Nav

- src/components/site-header/mobile-menu/mobile-menu-dropdown/mobile-menu-dropdown.jsx
- src/components/site-header/mobile-menu/mobile-menu-dropdown/mobile-menu-dropdown.spec.js
> FDG-7406 fixed test

- src/helpers/download-service/download-service.ts
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7504
> FDG-7504 Create GA4 event for dataset download

- src/components/charts/bar/bar.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7423
> Fdg 7423 Fix failing unit test

- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.module.scss
- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.spec.js
- src/layouts/explainer/sections/federal-spending/spending-categories/spending-categories.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-6624
Coverage: 90%
> FDG-6624 Spending - Update Spend by Agency/Category to FYTD

- src/helpers/constants.js
- src/helpers/published-reports/published-reports.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7453
> FDG-7453 Published Reports - Whitelist - Auctions Query Dataset

- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7459
code coverage: 89.83
> Fdg 7459 Update animation for 'Federal Deficit Trends Over Time' chart

- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
- src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.spec.js
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1688569299772599
> FDG 7459 Update Animation timing 

- src/components/checkbox/checkbox.jsx
- src/components/dataset-data/chart-table-toggle/chart-table-toggle.jsx
- src/components/dataset-data/chart-table-toggle/chart-table-toggle.spec.js
- src/components/dataset-data/table-section-container/table-section-container.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7560
> FDG-7151 fix sort order

- src/layouts/explainer/explainer-helpers/CustomSlice/custom-slice.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart-helper.js
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.spec.js
Code coverage: 89.91
https://federal-spending-transparency.atlassian.net/browse/FDG-6348
> FDG-6348 Spending Explainer - Add Animation Interactions to the GDP Chart > Total Spending View

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart-helper.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6346
Coverage: 89.94
> FDG-6346 - Revenue Explainer - Add Animation Interactions to the GDP Chart > Total Revenue View 

- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-6346
no changes in test
> FDG-6346 fix animation

- src/layouts/experimental/charts/afgOverviewDeficitChartPOC.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7330
Made a couple additional styling updates
> FDG-7330 AFG Overview Deficit Chart POC

- src/components/page-helmet/page-helmet.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7570
> FDG-7570 Investigate insecure frame vulnerability from SA&A report

- src/components/dataset-data/hide-legend-toggle/hideLegendToggle.jsx
- src/components/dataset-data/hide-legend-toggle/hideLegendToggle.module.scss
- src/components/dataset-data/hide-legend-toggle/hideLegendToggle.module.scss.d.ts
https://federal-spending-transparency.atlassian.net/browse/FDG-7564
test coverage: 89.91
> FDG-7564 - Select Columns toggle focus border

- src/components/announcement-banner/announcement-banner.jsx
- src/components/announcement-banner/announcement-banner.module.scss
- src/components/announcement-banner/announcement-banner.module.scss.d.ts
- src/components/announcement-banner/announcement-banner.spec.js
- src/components/site-header/site-header.jsx
- src/components/site-header/site-header.module.scss
- src/components/site-header/site-header.module.scss.d.ts
- src/components/site-header/site-header.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7397
test coverage: 89.91
> FDG-7397 - Update style for Site Notification Banner

- package-lock.json
- package.json
https://federal-spending-transparency.atlassian.net/browse/FDG-7542
> FDG-7542 Upgrade developer node version to 16

- gatsby-config.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7481
> FDG-7481 Add Delay to Axe Core plugin to prevent local server errors

- src/components/banner-callout/banner-callout.jsx
- src/components/masthead/masthead.jsx
- src/transform/static-metadata/datasets.json
**Do not merge until the deployment has been completed**
https://federal-spending-transparency.atlassian.net/browse/FDG-7581
> FDG-7581 DTS Updates - Create Ribbon on DTS page

- src/layouts/explainer/multichart/multichart.tsx
- src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
- src/layouts/explainer/sections/national-debt/breaking-down-the-debt/intragovernmental-holdings-chart/custom-bar/customBar.jsx
- src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7587
> FDG-7587 AFG Explainer Pages - Adjust animation start point

- src/components/banner-callout/banner-callout.jsx
- src/components/banner-callout/banner-callout.module.scss
- src/components/banner-callout/banner-callout.module.scss.d.ts
https://federal-spending-transparency.atlassian.net/browse/FDG-7581
Slack Conversation: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1691160686792399
> FDG-7581 Design Change: DTS Updates - Create Ribbon on DTS page

- package-lock.json
- package.json
https://federal-spending-transparency.atlassian.net/browse/FDG-7698
> FDG-7698 Upgrade node version to 16 and node-sass to 6 in Jenkins

- src/helpers/constants.js
- src/helpers/published-reports/published-reports.js
Code coverage: 89.76
https://federal-spending-transparency.atlassian.net/browse/FDG-7737
> FDG-7737 removed auctions query dataset from published whitelist

- src/components/combo-select/combo-currency-select/combo-currency-select.jsx
- src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx
- src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.module.scss
- src/components/published-reports/filter-section/filter-section.jsx
- src/components/published-reports/filter-section/filter-section.spec.js
- src/zIndex.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-7540
Coverage: 89.73%
> FDG-7540 DDP KUI - Update published reports dropdown with dropdown search component

- src/components/secondary-nav/secondary-nav.tsx
- src/components/social-share/share-button-content/share-button-content.tsx
Code coverage: 86.74
https://federal-spending-transparency.atlassian.net/browse/FDG-7594
> FDG-7594 Tabbing issues on the Currency Exchange Rates Converter tool page

- src/components/data-table/data-table.spec.js
- src/components/data-table/data-table.tsx
- src/components/dataset-data/dataset-data.spec.js
- src/components/dataset-data/table-section-container/table-section-container.jsx
- src/components/dataset-data/table-section-container/table-section-container.spec.js
- src/components/dtg-table/dtg-table.jsx
Coverage: 89.78%
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7573
> FDG-7573 Default Column Select in react-table

- src/components/published-reports/filter-section/filter-section.jsx
- src/components/published-reports/published-reports.jsx
- src/helpers/constants.js
- src/helpers/published-reports/published-reports.js
Ticket(s): 
- https://federal-spending-transparency.atlassian.net/browse/FDG-7746
- https://federal-spending-transparency.atlassian.net/browse/FDG-7453
DO NOT MERGE before release on 8/17/2023
> FDG-7746 Update Published Report Dropdown to Display Unique Reports, FDG-7453 Published Reports - Whitelist - Auctions Query Dataset

- src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.jsx
- src/layouts/explainer/sections/national-deficit/understanding/understanding-deficit.jsx
- src/transform/dates.js
Ticket: https://federal-spending-transparency.atlassian.net/jira/software/c/projects/FDG/boards/44?modal=detail&selectedIssue=FDG-7713&search=7713
Coverage:89.76
> FDG-7713 On Deficit page "Balanced Budget" item is not navigating to the Glossary when user clicks on it.

- src/components/combo-select/combo-select.jsx
- src/components/combo-select/combo-select.spec.js
- src/components/published-reports/filter-section/filter-section.jsx
- src/components/published-reports/util/util.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7727
> FDG-7727 Auction Dataset Published reports is not displaying the full list of years that are available for this report.

- env/uat.js
- src/components/dataset-data/dataset-chart/dataset-chart.jsx
- src/components/dtg-table/dtg-table-heading/dtg-table-heading.jsx
- src/components/dtg-table/dtg-table-heading/dtg-table-heading.spec.js
- src/components/dtg-table/dtg-table-row/dtg-table-row.jsx
- src/components/dtg-table/dtg-table-row/dtg-table-row.spec.js
- src/components/dtg-table/test-data.js
- src/helpers/text-format/text-format.jsx
- src/models/fdg-types.ts
- src/utils/api-utils.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7189
Coverage: 89.75
> FDG-7189 New Dataset Created in UAT - Treasury Bulletin

- src/components/combo-select/combo-select.spec.js
- src/components/published-reports/util/util.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7727
Thread: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1692659283439119
> FDG-7727 (Data Review) Removed filter limit to 10 results

- src/layouts/explainer/explainer-components/explainer-sub-nav/explainer-sub-nav.jsx
- src/layouts/explainer/explainer-components/explainer-sub-nav/explainer-sub-nav.spec.tsx
- src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.jsx
- src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7697
coverage: 89.91
> FDG-7697 Create AFG/Explainer GA Subnavigation Events

- src/components/datasets/filters/mobileFilterToggle/mobileFilterToggle.jsx
- src/components/datasets/filters/mobileFilterToggle/mobileFilterToggle.module.scss
- src/components/datasets/filters/mobileFilterToggle/mobileFilterToggle.module.scss.d.ts
Ticket:https://federal-spending-transparency.atlassian.net/browse/FDG-7302?atlOrigin=eyJpIjoiZTgyMTk2NmMxZjJlNGIwYjlkMGQ4NDQ1NjBmZTBmMDQiLCJwIjoiaiJ9
Coverage:89.83
> FDG-7302 Add styling to "Filter Your Results" and "View Your Results" for Dataset Search on mobile

- src/components/data-table/data-table-header/data-table-header.module.scss
- src/components/data-table/data-table-header/data-table-header.tsx
Design Feedback: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1692984070500379
No change in coverage 
https://federal-spending-transparency.atlassian.net/browse/FDG-7525
> FDG-7525 Design Review

- gatsby-node.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7391
> FDG-7391 Update BLS API call - testing

- gatsby-node.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7391
> FDG-7391 Update BLS API call - remove testing output

- src/helpers/constants.js
- src/helpers/published-reports/published-reports.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7799
> FDG-7799 Whitelist Published Reports - Treasury Bulletin

- .github/workflows/main.yml
- src/components/calendar-entries/calendar-entries.spec.js
- src/components/calendar-entries/calendar-entry/calendar-entry.spec.js
- src/components/combo-select/combo-currency-select/combo-currency-select.jsx
- src/components/combo-select/combo-currency-select/combo-currency-select.spec.js
- src/components/combo-select/combo-select.spec.js
- src/components/dataset-card/dataset-card.spec.js
- src/components/datasets/filters/filterRow/filterRow.spec.js
- src/components/datasets/filters/filterTimeRange/filterTimeRange.jsx
- src/components/datasets/filters/filterTimeRange/filterTimeRange.spec.js
- src/components/datasets/filters/filters.spec.js
- src/components/datasets/search-field/search-field.spec.js
- src/components/datasets/search-results/search-results.jsx
- src/components/datasets/search-results/search-results.spec.js
- src/components/datasets/topics/topic/topic.spec.js
- src/components/filter-download-container/range-presets/helpers/helper.spec.js
- src/components/home-highlight-cards/home-highlight-card/home-highlight-card.spec.js
- src/components/published-reports/preview/preview.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7585?atlOrigin=eyJpIjoiNjMxZGUxNjY1Y2Y5NGYxM2FkM2YyOTZhMmRkMDg1NzQiLCJwIjoiaiJ9
Coverage:90.11
> FDG 7585 Add test coverage for new GA4 related code

- .github/workflows/main.yml
- src/components/datasets/filters/filterTimeRange/filterTimeRange.spec.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7585
------------
Don't merge right away, looking for test results from github action job.
> FDG-7585 Adjusted timezone 

- src/components/dataset-data/table-section-container/table-section-container.jsx
- src/components/dtg-table/dtg-table.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7831
> FDG-7831 Auctions Dataset is not displaying the correct rows for Aug 2023 Date Rage

- gatsby-node.js
- src/components/banner-callout/banner-callout.jsx
- src/components/banner-callout/banner-callout.spec.js
- src/layouts/currency-exchange-rates-converter/index.tsx
- src/layouts/dataset-detail/dataset-detail.spec.js
- src/models/IDatasetConfig.ts
- src/transform/static-metadata/datasets.json
https://federal-spending-transparency.atlassian.net/browse/FDG-7719
Test coverage: 90.06
> FDG-7719 DTS Updates - Remove Ribbon on DTS page

- src/layouts/experimental/charts/lineGraph.jsx
- src/layouts/experimental/charts/lineGraphAnimation.jsx
- src/layouts/experimental/experimental.jsx
Ticket number: 
[DEV-7678](https://federal-spending-transparency.atlassian.net/browse/FDG-7678)
Test Coverage:
89.99
Research ticket for chart.
> FDG-7678 Research Line Chart Micro-interaction

- .github/workflows/codeql.yml
This job will perform a static code analysis of master every time a PR is merged into it. From there, we can address any potential security risks.
> Added CodeQL static code analysis job

- src/models/IDatasetData.ts
- src/models/IDatasetFields.ts
https://federal-spending-transparency.atlassian.net/browse/FDG-7800
> FDG-7800 Remove or change reference(s) to table_name in FDG

- src/components/combo-select/combo-currency-select/combo-currency-select.jsx
- src/components/combo-select/combo-currency-select/combo-currency-select.module.scss
- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.module.scss
- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.spec.js
- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.tsx
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.spec.js
- src/layouts/currency-exchange-rates-converter/index.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7441
> FDG-7441 Update XR Converter Tool page with new layout and design

- src/components/data-table/data-table.module.scss
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1694464515682789
> FDG-7794 Design Review 

- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.module.scss
- src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1694554617864419
> FDG-7441 Design Review

- src/layouts/experimental/charts/afgOverviewDeficitChartPOC.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7676
no change to test coverage
> Fdg 7676 - AFG Overview - Research Deficit chart animation implementation

- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.module.scss
- src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7907
> FDG-7907 Converter Tool Change Data unavailable dashes placement

- src/components/data-table/column-select/data-table-column-selector.module.scss
- src/components/dtg-table/dtg-table-column-selector.module.scss
- src/components/glossary/glossary-header/glossary-header.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-7913
> FDG-7913 With the deployment to PROD Glossary Close button is not displaying in the correct place.

- src/components/data-table/data-table-helper.tsx
- src/components/data-table/data-table.spec.js
- src/components/data-table/data-table.tsx
- src/components/dtg-table/dtg-table-row/dtg-table-row.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7840
Coverage: 90.07%
> FDG-7840 Enforce proper formatting on react table

- src/components/dataset-data/chart-table-toggle/chart-table-toggle.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7883?atlOrigin=eyJpIjoiODE5NTgzNDk0ZTliNGY5OThkODZjNjNjNWFmYzJhOWUiLCJwIjoiaiJ9
Testcoverage: 90%
> FDG-7883 Hide Reset Filters Button on Table Chart View

- gatsby-node.js
Testing if / how the env variables from jenkins can be grabbed in gatsby-node
> FDG 7295 Env variable log test

- env/dev.js
[FDG-7836](https://federal-spending-transparency.atlassian.net/browse/FDG-7836)
> FDG-7836 Remove authentication

- src/components/site-header/mobile-menu/mobile-menu.jsx
- src/components/site-header/mobile-menu/mobile-menu.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7914
> FDG-7914 Mobile menu navigation issue in Prod

- src/components/site-header/mobile-menu/mobile-menu.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7914
> FDG-7914 Adjust padding on bottom most link

- src/layouts/experimental/charts/afgOverviewDeficitChartPOC.js
- src/layouts/experimental/charts/rechartsLine.jsx
- src/layouts/experimental/experimental.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-7735
I would recommend running build/serve to test this
> FDG-7735  AFG Overview - Research Debt and Deficit chart hover interaction

- src/components/published-reports/preview/preview.jsx
Reverting ticket back to the original status. 
More conversation will need to be had with EDI to find a solution
> Fdg 7836 Revert changes

- package-lock.json
- src/layouts/explainer/heros/hero-helper.tsx
TEST COVERAGE 90.04 
https://federal-spending-transparency.atlassian.net/browse/FDG-6511
> Fdg 6511 Verbiage for Only One Month

- src/layouts/currency-exchange-rates-converter/index.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7909?atlOrigin=eyJpIjoiNDMxNmRlMDZhNDJiNGZiN2EwZjVjZmQ5OWUxZDg5YTEiLCJwIjoiaiJ9
testcoverage:90.05
> FDG-7909 Updating the verbiage on the XR Converter Tool.

- src/components/site-header/official-banner/official-banner.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7584?atlOrigin=eyJpIjoiYzczMjk3NTBhNDk3NDE3NDhmODMxOWQ5MGUyNTcyOTUiLCJwIjoiaiJ9
testcoverage:90.05
> FDG-7584 - Remove COVID-19 copy from the site header

- src/components/data-table/data-table-header/date-range-filter/date-range-filter.jsx
- src/components/data-table/data-table-header/date-range-filter/date-range-filter.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7958
Coverage: 90.13%
> FDG-7958 Update blur handlers

- src/components/data-table/data-table-footer/data-table-footer.tsx
- src/components/data-table/data-table-helper.tsx
- src/components/data-table/data-table.tsx
- src/components/dataset-data/dataset-data.spec.js
- src/components/dataset-data/table-section-container/table-section-container.spec.js
- src/components/dtg-table/dtg-table.jsx
- src/components/dtg-table/dtg-table.spec.js
- src/components/dtg-table/test-data.js
- src/components/filter-download-container/filter-download-container.jsx
- src/components/filter-download-container/filter-download-container.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7830
Coverage: 90.04%
Also made a fix to the paging "memory" that was missed when the paging controls were originally implemented. When you change the date range filter the page size should now stay consistent.
> FDG-7830 Remove experimental flag from react-table

- env/uat.js
- gatsby-node.js
- src/components/data-table/data-table-header/data-table-header.tsx
- src/components/data-table/data-table-helper.tsx
- src/components/data-table/data-table.spec.js
- src/components/data-table/data-table.tsx
- src/components/dataset-data/table-section-container/table-section-container.jsx
- src/components/dtg-table/dtg-table.jsx
- src/models/IDatasetConfig.ts
- src/transform/metadata-transform.js
- src/transform/static-metadata/datasets.json
https://federal-spending-transparency.atlassian.net/browse/FDG-8002
Coverage: 90.14%
> FDG-8002 Exclude FDG Standard Date Fields from Upcoming Auctions dataset

- env/uat.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8003
> FDG-8003 Exclude FDG Standard Date Fields from FRN Daily Indexes dataset

- env/uat.js
- src/helpers/constants.js
- src/helpers/published-reports/published-reports.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8007
> FDG-8007 Published Reports - Whitelist - Upcoming Auctions Dataset

- src/components/charts/chart-primary/index.js
- src/components/dataset-data/dataset-chart/dataset-chart.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7932
Coverage: 90.16%
> FDG-7932 Treasury Reporting Rates of Exchange chart tab throwing blank page and errors

- src/components/data-table/data-table-helper.tsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8008
Coverage: 90.15%
> FDG-8008 Fix CUSIP sorting on react table

- src/components/dataset-data/chart-table-toggle/chart-table-toggle.jsx
- src/components/dataset-data/dataset-data.spec.js
- src/components/dataset-data/table-section-container/table-section-container.spec.js
- src/components/dtg-table/dtg-table.jsx
- src/components/dtg-table/dtg-table.spec.js
- src/components/dtg-table/test-data.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7830
> FDG-7830 Rollback changes

- src/components/dtg-table/dtg-table.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-8002
> FDG-8002 Apply functionality to DTG Table

- src/components/banner-callout/banner-callout-helper.js
- src/components/masthead/masthead.jsx
- src/components/masthead/masthead.spec.js
- src/transform/static-metadata/datasets.json
https://federal-spending-transparency.atlassian.net/browse/FDG-8094
test coverage: 90.08
> Fdg 8094 - Put up banner on dataset detail page for U.S. Treasury Savings Bonds: Issues, Redemptions, and Maturities by Series

- src/pages/about-us/faq-section/faq-section.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-4841
90.08%
> fixed email subject

- src/layouts/explainer/sections/overview/deficit-chart/custom-tooltip/custom-tooltip.spec.js
- src/layouts/explainer/sections/overview/deficit-chart/custom-tooltip/custom-tooltip.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7668
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1697554655274909
> FDG-7668 Design review

- src/components/dataset-card/dataset-card.module.scss
- src/components/datasets/search-results/search-result-cards/search-result-cards.jsx
- src/components/datasets/search-results/search-result-cards/search-result-cards.spec.js
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1697558976993319
> FDG-7398 Design feedback

- src/components/datasets/search-results/search-result-cards/search-result-cards.jsx
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1697653558325589
> FDG-7398 Design review

- src/components/data-table/data-table-footer/data-table-footer.tsx
- src/components/data-table/data-table.spec.js
- src/components/data-table/data-table.tsx
- src/components/dataset-data/table-section-container/table-section-container.jsx
- src/components/dtg-table/dtg-table.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-8031
Coverage: 90.05%
> FDG-8031 React Table - Large Datasets (up to 20,000 rows)

- src/components/combo-select/combo-select.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7804
https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1697664045841439
> FDG-7804 Auction Dataset Published reports year dropdown overlapping reports

- src/layouts/explainer/explainer-components/afg-components/afg-topic-section/afg-topic-section.jsx
- src/pages/americas-finance-guide/index.jsx
flip the rev and spending
https://federal-spending-transparency.atlassian.net/browse/FDG-7666
> FDG-7666 flip rev and spending

- src/layouts/explainer/sections/overview/chart-components/chart-legend.jsx
- src/layouts/explainer/sections/overview/chart-components/chart-legend.module.scss
- src/layouts/explainer/sections/overview/deficit-chart/deficit-chart.module.scss
- src/layouts/explainer/sections/overview/deficit-chart/deficit-chart.tsx
- src/layouts/explainer/sections/overview/revenue-chart/revenue-chart.tsx
- src/layouts/explainer/sections/overview/spending-chart/spending-chart.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-8178
> FDG-8178 AFG Overview - Decrease Spacing Between Swatch & Text in Revenue Chart

- src/layouts/explainer/explainer-components/afg-components/afg-topic-section/afg-topic-section.jsx
- src/layouts/explainer/explainer-components/afg-components/afg-topic-section/afg-topic-section.module.scss
- src/layouts/explainer/explainer-components/afg-components/afg-topic-section/afg-topic-section.spec.tsx
- src/layouts/explainer/explainer-helpers/explainer-helpers.js
- src/layouts/explainer/sections/overview/components/header-chip/header-chip.jsx
- src/layouts/explainer/sections/overview/components/header-chip/header-chip.module.scss
- src/layouts/explainer/sections/overview/components/header-chip/header-chip.spec.js
- src/pages/americas-finance-guide/index.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-8015
Coverage: 90.05%
> FDG-8015 AFG Overview - Add topic headers

- src/components/announcement-banner/announcement-banner.module.scss
- src/components/site-header/site-header.jsx
- src/components/site-header/site-header.module.scss
- src/layouts/experimental/experimental.jsx
[…color convention.  It looks like the content text was already defaulting to #666666.](https://federal-spending-transparency.atlassian.net/browse/FDG-7672?atlOrigin=eyJpIjoiYjZjNjE0ODU3ZjNjNDY2NTg4NjdiMjUxYzNmN2E4YTgiLCJwIjoiaiJ9)
Test Coverage: 90.09
> FDG-7672.  General Site Update - Change font color in notification banner

- env/uat.js
[FDG-8206](https://federal-spending-transparency.atlassian.net/browse/FDG-8206)
Updated UAT info. 
TEST: 90.1%
> FDG-8206-UPDATE THE UAT BASE

- src/layouts/explainer/explainer-components/afg-components/topic-section/topic-section.jsx
- src/layouts/explainer/sections/overview/spending-chart/spending-chart.jsx
[FDG-8207](https://federal-spending-transparency.atlassian.net/browse/FDG-8207)
Pointer was the issue.... 
TEST: 90.11%
> Fdg 8207 spedning chart blue

- src/pages/about-us/about-section/about-section.jsx
- src/pages/about-us/about-section/about-section.spec.js
- src/pages/about-us/toc-data.json
[FDG-7263](https://federal-spending-transparency.atlassian.net/browse/FDG-7263)
TEST: 90.1
The only thing I find weird about this is the XML links. might bring up in 16th min
EDIT:: It is suppose to go to the xml page
> FDG-7263-about us update

- env/uat.js
[FDG-8205](https://federal-spending-transparency.atlassian.net/browse/FDG-8205)
Updated UAT only
TEST: 90.09%
> FDG 8205 updated UAT

- src/pages/about-us/about-section/about-section.jsx
- src/pages/about-us/about-section/about-section.spec.js
[FDG-7942](https://federal-spending-transparency.atlassian.net/browse/FDG-7942)
Test: 90.1
> FDG-7942-update about us mission

- src/layouts/explainer/explainer-components/afg-components/topic-section/topic-section.jsx
- src/layouts/explainer/sections/overview/revenue-chart/revenue-chart.tsx
[FDG-8213](https://federal-spending-transparency.atlassian.net/browse/FDG-8213)
TEST: 90.09%
> FDG-8213 Update text

- src/layouts/explainer/explainer-components/afg-components/afg-topic-card/afg-topic-card.jsx
- src/layouts/explainer/explainer-components/afg-components/topic-section/topic-section.jsx
- src/layouts/explainer/explainer-helpers/afg-overview-test-helper.ts
- src/layouts/explainer/sections/overview/chart-components/chart-legend.jsx
- src/layouts/explainer/sections/overview/chart-components/chart-legend.module.scss
- src/layouts/explainer/sections/overview/debt-chart/debt-chart.spec.js
- src/layouts/explainer/sections/overview/debt-chart/debt-chart.tsx
- src/layouts/explainer/sections/overview/debt-chart/debt-chat.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-7669
Coverage: 90.16%
debt-chart.tsx coverage: 98.73%
> FDG-7669 AFG Overview - Implement Debt Chart visual design

- src/layouts/explainer/sections/overview/debt-chart/debt-chart.tsx
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1698862525378009
https://federal-spending-transparency.atlassian.net/browse/FDG-7669
> FDG-7669 Data Review

- src/layouts/explainer/explainer-components/afg-components/afg-hero/afg-hero.module.scss
This has to be it.. It has to be.
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1698692387322669
https://federal-spending-transparency.atlassian.net/browse/FDG-8016
test 90.09%
> FDG-8016 final Kylon revisions

- src/layouts/explainer/explainer-helpers/federal-spending/federal-spending-test-helper.js
- src/layouts/explainer/explainer-test-helper.js
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.spec.js
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8236
> FDG-8236 The text to the right of the Federal Revenue and the US Economy (GDP) chart on the Revenue page didn't update correctly.

- src/layouts/explainer/explainer-helpers/federal-spending/federal-spending-test-helper.js
- src/layouts/explainer/explainer-test-helper.js
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
- src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.spec.js
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
- src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8236
> FDG 8236 Hotfix 

- src/components/banner-callout/banner-callout-helper.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8288
no testing changes
> FDG-8288 - Securities Issued in TD and Treasury Savings Bonds: Issues, Redemptions, Maturities

- src/components/data-table/column-select/data-table-column-selector.module.scss
- src/components/select-all/select-all.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-7714
no change in test
> FDG-7714 - DDP KUI - Align 'Select All' with other checkboxes

- src/components/datatables-tab/__snapshots__/datatables-tab-helpers.spec.js.snap
- src/components/datatables-tab/__snapshots__/datatables-tab.spec.js.snap
- src/components/datatables-tab/datatables-tab-helpers.js
- src/components/datatables-tab/datatables-tab.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-8200
Coverage: 90.03%
> FDG-8200 DDP - Remove 'File Sizes' Field

- src/transform/static-metadata/datasets.json
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8010
> FDG-8010 Add Auctions Topic to Treasury Bulletin dataset

- src/components/combo-select/combo-currency-select/combo-currency-select.jsx
- src/components/combo-select/combo-currency-select/combo-currency-select.module.scss
- src/components/combo-select/combo-currency-select/combo-currency-select.spec.js
- src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx
- src/components/dataset-data/dataset-data.spec.js
- src/components/datatable-select/datatable-select.jsx
- src/components/datatable-select/datatable-select.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7846
Coverage: 90.01%
> FDG-7846 DDP KUI - Swap out data table selection control for combo box component

- src/components/dtg-table/dtg-table.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-8318
> FDG-8318 Upcoming Auctions dataset functionality of the metadata table looks off.

- src/layouts/explainer/sections/national-debt/growing-national-debt/growing-national-debt.jsx
- src/layouts/explainer/sections/national-debt/national-debt.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-8156
> FDG-8156 AFG Debt Copy Updates - History of the Debt

- src/components/dataset-detail-nav/dataset-detail-nav.jsx
- src/components/dataset-section-container/dataset-section-container.module.scss
- src/layouts/dataset-detail/dataset-detail.jsx
- src/styles.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-7890
no change in tests
> FDG-7890 - DDP KUI - Reorder 'Preview & Download' and 'Dataset Properties'

- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/circle-chart-label.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.jsx
- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8330
> FDG-8330 Circle Chart Update

- src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/circle-chart-label.jsx
Fixed mobile view
https://federal-spending-transparency.atlassian.net/browse/FDG-8330
test: no change
> Fdg 8330 circle chart adjustment

- src/components/pageError/page-error-graphic.jsx
- src/components/pageError/page-error-text.jsx
- src/components/site-footer/site-footer.jsx
- src/components/site-footer/site-footer.module.scss
- src/components/site-header/menu-button/menu-button.jsx
- src/components/site-header/mobile-menu/mobile-menu.jsx
- src/components/site-header/official-banner/official-banner.jsx
- src/components/site-header/site-header.jsx
- src/pages/404/index.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-4360
> FDG 4360 Update CSS module imports - Header, Footer, and 404 page

- src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-8126
> FDG-8126 Currency Exchange Rates Converter Country-Currency: croatia-euro is grayed out but able to type in for year: 2022 4th quarter

- src/components/home-highlight-cards/home-highlight-card/sparkler/sparkler.module.scss
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8125
No change in coverage.
> FDG-8125 Homepage U.S. Treasury-owned gold Gold card sparkle animation is not working

- src/components/banner-callout/banner-callout-helper.js
- src/components/banner-callout/banner-callout.jsx
- src/components/banner-callout/banner-callout.module.scss
- src/components/banner-callout/banner-callout.spec.js
- src/components/data-table/column-select/data-table-column-selector.module.scss
- src/components/data-table/data-table-header/data-table-header.tsx
- src/components/data-table/data-table-header/date-range-filter/date-range-filter.module.scss
- src/components/data-table/data-table-header/text-filter/text-filter.tsx
- src/components/data-table/data-table-helper.tsx
- src/components/data-table/data-table.tsx
- src/components/data-table/reset-table-section/reset-table-section.jsx
- src/components/data-table/reset-table-section/reset-table-section.module.scss
- src/components/data-table/reset-table-section/reset-table-section.spec.js
- src/components/dataset-data/chart-table-toggle/chart-table-toggle.jsx
- src/components/dataset-data/table-section-container/table-section-container.jsx
- src/components/dtg-table/dtg-table-column-selector.module.scss
- src/components/dtg-table/dtg-table.jsx
- src/components/glossary/glossary-header/glossary-header.module.scss
- src/components/glossary/glossary-header/glossary-header.tsx
- src/components/info-tip/info-tip.jsx
- src/components/masthead/masthead.jsx
- src/components/masthead/masthead.module.scss
- src/components/search-bar/search-bar.module.scss
- src/components/search-bar/search-bar.tsx
https://federal-spending-transparency.atlassian.net/browse/FDG-8147
Coverage: 90.04%
> FDG-8147 React Table - Add Filtering / Sorting Notice to Large Datasets (greater than 20,000 rows)

- src/components/data-table/data-table-footer/data-table-footer.tsx
- src/components/data-table/data-table.tsx
- src/components/dataset-data/table-section-container/table-section-container.jsx
- src/components/dtg-table/dtg-table.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-8370
> FDG-8370 Enhance Error Handling for React Table

- src/components/banner-callout/banner-callout.jsx
- src/components/info-tip/info-tip.jsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8381
> FDG-8381 Tooltip in Notification Banner Jumps Up Page on Click

- src/components/published-reports/filter-section/filter-section.module.scss
https://federal-spending-transparency.atlassian.net/jira/software/c/projects/FDG/boards/44?quickFilter=414&selectedIssue=FDG-8386
> FDG8386update the width for the months

- src/components/detail-pills/detail-pills.jsx
- src/components/detail-pills/detail-pills.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8332
> FDG-8332 DDP KUI - Remove data format and data dictionary pills from Introduction

- src/components/data-table/data-table.module.scss
- src/transform/static-metadata/datasets.json
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8340
> FDG-8340 Apply Column Selection to Exchange Rates Dataset

- src/components/banner-callout/banner-callout-helper.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8389
> FDG-8389 - change banner for deploy

- .github/workflows/main.yml
- src/components/data-table/data-table-header/date-range-filter/date-range-filter.jsx
- src/components/data-table/data-table-header/date-range-filter/date-range-filter.module.scss
- src/components/data-table/data-table-header/date-range-filter/date-range-filter.spec.js
- src/components/data-table/data-table-header/date-range-filter/day-picker-overrides.css
- src/components/data-table/data-table.spec.js
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8060
Coverage: 90.05%
> FDG-8060 DDP KUI - Update interaction design for date range picker

- src/components/breadcrumbs/breadcrumbs.jsx
- src/components/breadcrumbs/breadcrumbs.module.scss
- src/components/breadcrumbs/breadcrumbs.spec.js
- src/components/select-control/select-control.jsx
- src/components/select-control/select-control.module.scss
- src/pages/about-us/about-section/about-section.jsx
- src/pages/about-us/contact-section/contact-section.jsx
- src/pages/about-us/faq-section/faq-section.jsx
[FDG-4361](https://federal-spending-transparency.atlassian.net/browse/FDG-4361)
Test: 90%
> FDG-4361 SCSS updates

- env/uat.js
https://federal-spending-transparency.atlassian.net/browse/FDG-7512
> FDG-7512 New Dataset Created in UAT - Treasury Bulletin: Trust Funds

- src/components/published-reports/filter-section/filter-section.jsx
- src/components/published-reports/filter-section/filter-section.module.scss
- src/components/published-reports/filter-section/filter-section.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8028
> Fdg 8028 displaying wrong report

- src/components/combo-select/combo-select.jsx
- src/components/dataset-section-container/dataset-section-container.jsx
- src/components/datatable-select/datatable-select.spec.js
- src/components/filter-download-container/datepickers/datepickers.jsx
- src/components/published-reports/filter-section/filter-section.spec.js
- src/components/select-control/select-control.jsx
- src/components/select-control/select-control.module.scss
https://federal-spending-transparency.atlassian.net/browse/FDG-4371
no change to test coverage
> FDG-4371 Update CSS module imports - Dataset Data components (Part 2) and Published Reports

- src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
- src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8435
> FDG-8345 AFG Spending Explainer - Federal Spending Should Display As Increased

- src/components/api-quick-guide/accordions/fields/fields.spec.js
- src/components/api-quick-guide/accordions/filters/filters.spec.js
- src/components/api-quick-guide/accordions/format/format.spec.js
- src/components/api-quick-guide/accordions/pagination/pagination.spec.js
- src/components/api-quick-guide/accordions/sorting/sorting.spec.js
- src/components/api-quick-guide/api-quick-guide.jsx
- src/components/api-quick-guide/dataset-detail-endpoints/dataset-detail-endpoints.jsx
- src/components/api-quick-guide/dataset-detail-examples/dataset-detail-examples.jsx
https://federal-spending-transparency.atlassian.net/browse/FDG-4364
> FDG-4364 Update CSS module imports - API Quick Guide

- src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
- src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx
Hero hotfix into new timestamp branch
> Hero Hotfix

- src/components/data-table/data-table-header/date-range-filter/date-range-filter.jsx
- src/components/data-table/data-table-header/date-range-filter/date-range-filter.module.scss
- src/components/data-table/data-table-header/date-range-filter/day-picker-overrides.css
Slack thread: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1702567141119799
- Today's date now retains circular border when inside of selected date range
- Column width for date columns reduced
- Date range displayed updates properly if date range is changed after already being selected
> FDG-8060 Design review

- src/components/dataset-data/dataset-data.spec.js
- src/components/dataset-data/table-section-container/table-section-container.jsx
- src/components/dataset-data/table-section-container/table-section-container.spec.js
- src/components/dataset-data/table-section-container/testHelpers.js
- src/components/dtg-table/dtg-table-set-react-table-data.spec.js
- src/components/dtg-table/dtg-table.jsx
- src/components/dtg-table/dtg-table.spec.js
- src/components/dtg-table/test-data.js
- src/components/pagination/paging-options-menu.jsx
- src/layouts/explainer/sections/national-debt/breaking-down-the-debt/breaking-down-the-debt.spec.js
- src/recoil/reactTableFilteredState.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8387
Notes: Test on a wide variety of table sizes and types
Testing thread: 
https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1702319696551869
> FDG-8387 DDP - Switching To Pivot Table Gives Slow Response and Progress Indicator Display Inconsistent

- src/components/dataset-detail-nav/dataset-detail-nav.jsx
- src/components/dataset-detail-nav/dataset-detail-nav.spec.js
https://federal-spending-transparency.atlassian.net/browse/FDG-8320
Kylon and I agreed to leave out the jump to part in this ticket.  I attached the thread we talked but we also had a short phone call about it.
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1703000304371689
test: 90.1%
> Fdg 8320 micro interaction 
