fedspendingtransparency/fiscal-data

src/components/dataset-data/current-report-toggle/current-report-toggle.jsx
src/components/dataset-data/current-report-toggle/current-report-toggle.spec.js
src/components/published-reports/filter-section/filter-section.jsx
src/components/published-reports/filter-section/filter-section.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8449
Coverage:

FDG-8449 DDP Published Reports - Dropdown Selection Doesn't Change Report Below

---

src/components/dataset-detail-nav/dataset-detail-nav.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8451
test no change

Fdg 8320 micor interaction 

---

env/uat.js
src/transform/endpointConfig.js
src/transform/static-metadata/datasets.json

https://federal-spending-transparency.atlassian.net/browse/FDG-7982

FDG-7982 Promote New Dataset to Prod - Treasury Bulletin: Trust Funds

---

src/components/dataset-data/dataset-data.jsx
src/components/dataset-data/table-section-container/table-section-container.jsx
src/components/filter-download-container/range-presets/range-presets.jsx
src/components/filter-download-container/user-filter/user-filter.spec.tsx
src/components/filter-download-container/user-filter/user-filter.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8412
Coverage: 89.87

FDG-8412 Selecting user filter value in TRRE Dataset resets active table filters

---

src/variables.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8315

FDG-8315 Data table selection control need to adjust to individual tabs

---

src/components/api-documentation/section-content/section-content.module.scss
src/components/secondary-nav/secondary-nav.tsx
src/pages/about-us/about-us.module.scss
src/pages/about-us/faq-section/faq-section.jsx
src/pages/about-us/index.tsx
src/pages/api-documentation/api.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8420

FDG-8420 About Us Page - TOC Blue Indicator Incorrect Placement

---

src/components/datasets/filters/filterGroupReset/filterGroupReset.jsx
src/components/datasets/filters/filterPublisherWrapper/filterPublisher.jsx
src/components/datasets/filters/filterRow/filterCount/filterCount.jsx
src/components/datasets/filters/filterRow/filterCount/filterCount.module.scss
src/components/datasets/filters/filterRow/filterRow.jsx
src/components/datasets/filters/filterTimeRange/filterTimeRange.jsx
src/components/datasets/filters/filters.jsx
src/components/datasets/filters/mobileFilterToggle/mobileFilterToggle.jsx
src/components/datasets/filters/mobileFilterToggle/mobileFilterToggle.spec.js
src/components/datasets/filters/searchFilterSummary/searchFilterSummary.jsx
src/components/datasets/search-field/search-field.jsx
src/components/datasets/search-results/search-result-cards/search-result-cards.jsx
src/components/datasets/topics/topic/topic.jsx
src/components/datasets/topics/topic/topic.module.scss
src/components/datasets/topics/topic/topic.spec.js
src/components/datasets/topics/topics.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-4372

FDG-4372 - Update CSS module imports - Datasets components

---

src/components/dataset-data/dataset-chart/chart-citation/chart-citation.jsx
src/components/dataset-data/table-section-container/aggregation-notice/aggregation-notice.jsx
src/components/dataset-data/table-section-container/dynamic-config/dynamicConfig.jsx
src/components/dataset-data/table-section-container/not-shown-message/not-shown-message.jsx
src/components/dataset-data/table-section-container/not-shown-message/not-shown-message.module.scss
src/components/dataset-data/table-section-container/pivot-options/pivot-options.jsx
src/components/dataset-data/table-section-container/pivot-toggle/pivot-toggle.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-4370
no change in tests

FDG-4370 - Update CSS module imports - Dataset Data components - Part 1

---

src/components/api-documentation/data-registry/data-registry.jsx
src/components/api-documentation/endpoints/endpoints.jsx
src/components/api-documentation/fields/fields.jsx
src/components/api-documentation/filters/filters.jsx
src/components/api-documentation/getting-started/getting-started.jsx
src/components/api-documentation/methods/methods.jsx
src/components/api-documentation/parameters/pagination/pagination.jsx
src/components/api-documentation/parameters/parameters.jsx
src/components/api-documentation/parameters/sorting/sorting.jsx
src/components/api-documentation/responses/error-object/error-object.jsx
src/components/api-documentation/responses/links-object/links-object.jsx
src/components/api-documentation/responses/meta-object/meta-object.jsx
src/components/api-documentation/responses/responses.jsx
src/components/api-documentation/section-content/section-content.jsx
src/pages/api-documentation/api-documentation.spec.js
src/pages/api-documentation/index.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-4362

FDG-4362 Update CSS module imports - API Documentation page

---

src/components/datatables-tab/datatables-tab.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-1578

FDG-1578 Dataset Detail Page - Data Tables tab - minor readability updates

---

src/components/calendar-entries/calendar-entries.jsx
src/components/calendar-entries/calendar-entry-pages/calendar-entry-pages.jsx
src/components/calendar-entries/calendar-entry-pages/calendar-entry-pages.module.scss
src/components/calendar-entries/calendar-entry/calendar-entry.jsx
src/components/calendar-entries/calendar-entry/calendar-entry.module.scss
src/components/pagination/page-buttons.jsx
src/components/pagination/pagination-controls.jsx
src/pages/datasets/index.jsx
src/pages/release-calendar/index.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-4363

FDG-4363 - Update CSS module imports - Release Calendar page, Dataset Search page, and Pagination components

---

src/components/download-modal/download-modal-item/download-modal-item.jsx
src/components/download-modal/download-modal-item/download-modal-item.module.scss
src/components/download-modal/download-modal.jsx
src/components/download-modal/resume-download-modal/resume-download-modal.jsx
src/components/download-percentage-status/download-percentage-status.jsx
src/components/download-percentage-status/download-percentage-status.module.scss
src/components/download-sticky/download-sticky.jsx
src/components/download-sticky/download-sticky.module.scss
src/components/download-sticky/download-sticky.spec.js
src/components/download-wrapper/download-item-button/download-item-button.spec.js
src/components/download-wrapper/download-toggle/download-toggle.jsx
src/components/download-wrapper/download-wrapper.jsx
src/components/download-wrapper/download-wrapper.module.scss
src/components/modal/modal.jsx
src/components/sticky-footer/sticky-footer.jsx
src/components/sticky-footer/sticky-footer.module.scss
src/components/sticky-footer/sticky-footer.spec.js
src/components/truncate/truncate.jsx
src/components/truncate/truncate.module.scss
src/components/truncate/truncate.spec.js
src/pages/downloads/index.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-4368

FDG-4368 Update CSS module imports - Download Components

---

src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx
src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.module.scss

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7769
Coverage: 89.85%

FDG-7769 General Site Updates - Make Dropdown Search height flexible for < 5 menu items

---

src/components/charts/bar/bar.jsx
src/components/charts/chart-legend/chartLegend.jsx
src/components/dataset-card/dataset-card.spec.js
src/components/dataset-card/dataset-stats/dataset-stats.jsx
src/components/dataset-card/dataset-stats/dataset-stats.module.scss
src/components/dataset-card/dataset-topics-summary/dataset-topics-summary.jsx
src/components/dataset-stats/dataset-stats.jsx
src/components/dataset-stats/dataset-stats.module.scss
src/components/dataset-topics-summary/dataset-topics-summary.jsx
src/layouts/topics/highlight-card/highlight-card.jsx
src/layouts/topics/masthead/masthead.jsx
src/layouts/topics/masthead/masthead.module.scss
src/layouts/topics/topics.jsx
src/layouts/topics/topics.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-4375
no changes in tests

FDG-4375 - Update CSS module imports - Dataset components, Charts, Layouts

---

src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.tsx
src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter-test-helper.js
src/layouts/currency-exchange-rates-converter/index.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8276

Fdg 8276 converter tool

---

src/helpers/constants.js
src/helpers/published-reports/published-reports.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8424

FDG-8424 Published Reports - Whitelist - TB: Trust Funds Reports

---

src/components/home-highlight-cards/home-highlight-card/home-highlight-card.module.scss
src/components/home-highlight-cards/home-highlight-cards.jsx
src/components/home-highlight-cards/home-highlight-cards.module.scss
src/components/home-highlight-cards/home-highlight-cards.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-7159
Coverage: 89.53%

FDG-7159 Update Interactive Data Q&A Cards Section to Always Show All Cards

---

src/components/detail-pills/detail-pills.jsx
src/components/detail-pills/detail-pills.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8397

FDG-8397 DDP KUI - Update pill icons

---

src/components/accordion/accordion.spec.js
src/components/checkbox/checkbox.jsx
src/components/checkbox/checkbox.spec.js
src/components/detail-pills/detail-pills.jsx
src/components/detail-pills/detail-pills.module.scss
src/components/detail-pills/detail-pills.spec.js
src/components/dtg-table/dtg-table-row/dtg-table-row.jsx
src/components/dtg-table/dtg-table.jsx
src/components/dtg-table/dtg-table.module.scss
src/components/experimental/experimental-switch/experimental-switch.jsx
src/components/info-tip/info-tip.jsx
src/components/info-tip/info-tip.module.scss
src/components/page-notice/page-notice.jsx
src/components/related-datasets/related-datasets.jsx
src/components/select-all/selectAll.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-4373

FDG-4373 Update CSS module imports - Common components

---

src/components/data-table/column-select/data-table-column-selector.module.scss
src/components/data-table/column-select/select-all/data-table-select-all.jsx
src/components/select-all/select-all.module.scss
src/components/select-all/selectAll.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8414

FDG-8414 "Select All" Checkbox Does Not Go In Focus Upon Tabbing

---

src/components/detail-pills/detail-pills.jsx
src/components/detail-pills/detail-pills.spec.js
src/testData/__dataConfig_for_tests.json

Thread: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1704403325823829

FDG-8397 Added 'released' language - Design Review

---

gatsby-node.js
src/components/dataset-data/dataset-data.jsx
src/components/filter-download-container/datatable-banner/datatable-banner.module.scss
src/components/filter-download-container/datatable-banner/datatable-banner.spec.tsx
src/components/filter-download-container/datatable-banner/datatable-banner.tsx
src/components/filter-download-container/range-presets/range-presets.jsx
src/components/filter-download-container/range-presets/range-presets.spec.js
src/components/filter-download-container/user-filter/user-filter.module.scss
src/components/filter-download-container/user-filter/user-filter.spec.tsx
src/components/filter-download-container/user-filter/user-filter.tsx
src/models/IDatasetConfig.ts
src/transform/metadata-transform.js
src/transform/static-metadata/datasets.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8431
all files: 89.91%
datatable-banner: 100%
user-filter: 100%

FDG 8431 - Alter DTS DDP to Include Footnote Notification

---

src/layouts/explainer/explainer-components/afg-components/topic-section/topic-section.jsx
src/layouts/explainer/explainer-components/afg-components/topic-section/topic-section.spec.js
src/layouts/explainer/explainer-helpers/afg-overview-test-helper.ts

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8393
Coverage: 89.9%

FDG-8393 AFG Overview - Update API calls

---

src/components/data-table/data-table-header/data-table-header.tsx
src/components/data-table/data-table-header/date-range-filter/date-range-filter.jsx
src/components/data-table/data-table-header/date-range-filter/date-range-filter.module.scss
src/components/data-table/data-table-helper.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8012

FDG-8012 DDP KUI - Adjust date picker position for right-most column in table

---

src/components/banner-callout/banner-callout-helper.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8503

FDG-8503 Banner Update - Securities Issued in TD and Treasury Savings Bonds: Issues, Redemptions, Maturities

---

src/components/dataset-detail-nav/dataset-detail-nav.module.scss
src/components/site-header/desktop-menu/desktop-menu.jsx
src/components/site-header/desktop-menu/desktop-menu.module.scss
src/components/site-header/menu-button/menu-button.module.scss
src/components/site-header/menu-dropdown/menu-dropdown.jsx
src/components/site-header/menu-dropdown/menu-dropdown.module.scss
src/components/site-header/site-header.jsx
src/components/site-header/site-header.module.scss
src/components/site-header/site-header.spec.js
src/layouts/explainer/explainer-components/explainer-sub-nav/explainer-sub-nav.module.scss
src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.jsx
src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.module.scss
src/pages/americas-finance-guide/index.jsx
src/zIndex.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8327
Test coverage: 89.48
Running build /serve is advised for the testing of this ticket

FDG-8327 General Site Updates - Make global navigation a sticky element

---

src/layouts/explainer/explainer-test-helper.js
src/layouts/explainer/hero-image/hero-image.module.scss
src/layouts/explainer/heros/hero-helper.tsx
src/layouts/explainer/heros/national-deficit/national-deficit-hero.spec.js
src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
src/layouts/explainer/sections/national-deficit/understanding/deficit-comparison-bar-chart/deficit-comparison-bar-chart.jsx
src/layouts/explainer/sections/national-deficit/understanding/deficit-comparison-bar-chart/deficit-comparison-bar-chart.spec.js
static/images/double-dash.svg

[FDG-8391](https://federal-spending-transparency.atlassian.net/browse/FDG-8391)
Test:

Fdg 8391 deficit explainer api call updates

---

src/components/about-us/about-section/about-section.jsx
src/components/about-us/contact-section/contact-form/contact-form.jsx
src/components/about-us/contact-section/contact-form/contact-form.spec.js
src/components/about-us/contact-section/contact-section.jsx
src/components/about-us/faq-section/faq-section.jsx
src/components/about-us/helpers/helpers.js
src/components/api-documentation/aggregation/aggregation.jsx
src/components/api-documentation/parameters/format/format.jsx
src/components/data-table/column-select/select-all/data-table-select-all.jsx
src/components/footnote/footnote.tsx
src/components/section-collapse/section-collapse-button.jsx
src/components/site-header/desktop-menu/desktop-menu.spec.js
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart-helper.js

https://federal-spending-transparency.atlassian.net/browse/FDG-7815

FDG-7815 Verify all CSS imports have been updated

---

src/components/combo-select/combo-currency-select/combo-currency-select.jsx
src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.module.scss
src/components/datatable-select/datatable-select.module.scss
src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.module.scss
src/components/filter-download-container/user-filter/user-filter.module.scss
src/components/published-reports/filter-section/filter-section.jsx
src/components/published-reports/filter-section/filter-section.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8474
testing coverage unchanged

FDG-8474 - Increase minimum width for dropdown frame and menu for table and published reports selector

---

src/utils/api-utils-helper.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8499

FDG-8499 Prevent non conforming input from reaching dataset downloader from react table

---

src/components/filter-download-container/user-filter/user-filter.module.scss

Design Review:
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1705078444633989
Original Ticket:
https://federal-spending-transparency.atlassian.net/browse/FDG-8474

FDG-8474 - Increase minimum width for dropdown frame and menu for table and published reports selector - Design review

---

src/components/dataset-detail-nav/dataset-detail-nav.jsx
src/components/dataset-detail-nav/dataset-detail-nav.module.scss
src/components/dataset-detail-nav/dataset-detail-nav.spec.js
src/components/masthead/masthead.jsx
src/components/masthead/masthead.module.scss
src/components/masthead/masthead.spec.js
src/components/site-header/site-header.jsx
src/layouts/dataset-detail/dataset-detail.jsx
src/layouts/dataset-detail/dataset-detail.spec.js
src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8327
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1705002974186749
Coverage: 89.81%

FDG-8327 Design Review

---

src/components/download-sticky/download-sticky.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8471

FDG-8471 - Download Name on Mobile Expands Width of Screen

---

src/components/banner-callout/banner-callout.jsx
src/components/banner-callout/banner-callout.module.scss
src/components/breadcrumbs/breadcrumbs.module.scss
src/components/masthead/masthead.module.scss
src/layouts/currency-exchange-rates-converter/index.tsx

Thread: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1705424884040889
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8327

FDG-8327 Design review changes 

---

src/layouts/explainer/explainer-components/explainer-sub-nav/explainer-sub-nav.module.scss
src/layouts/explainer/explainer-components/mobile-explainer-sub-nav/mobile-explainer-sub-nav.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8562

FDG-8562 General Site Updates - AFG Sticky Sub-Nav Spacing Issues

---

src/components/filter-download-container/filter-download-container.module.scss
src/components/published-reports/published-reports.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8557

FDG-8557 - Width for dropdown frame overflows when user resizes browser

---

src/components/dataset-detail-nav/dataset-detail-nav.jsx
src/components/masthead/masthead.jsx
src/components/secondary-nav/secondary-nav.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8558

FDG-8558 AFG Explainers, About us and DDP page tabbing is not working on the sub navigation.

---

src/components/dataset-data/dataset-chart/dataset-chart.jsx
src/components/dataset-data/dataset-chart/dataset-chart.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8572

FDG-8572 DDP - DTS Experiencing a 404 Page on Chart Tab

---

src/components/breadcrumbs/breadcrumbs.module.scss
src/components/masthead/masthead.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-4806
test: no coverage change

Matching left distances

---

src/components/secondary-nav/secondary-nav.tsx
src/layouts/explainer/explainer-helpers/explainer-helpers.js
src/layouts/explainer/explainer-helpers/explainer-helpers.module.scss
src/layouts/explainer/explainer.module.scss
src/layouts/explainer/explainer.spec.js
src/layouts/explainer/explainer.tsx
src/layouts/explainer/sections/sections.jsx
src/layouts/explainer/sections/treasury-savings-bonds/treasury-savings-bonds.module.scss
src/layouts/explainer/sections/treasury-savings-bonds/treasury-savings-bonds.tsx
src/transform/explainer-pages-config.js
src/transform/explainer-pages-config.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8517
Axe: no new issues introduced 
Line coverage:
All Files - 89.8
treasury-savings-bonds.tsx - 100%
sections.jsx - 100%
explainer.tsx - 100%
explainer-pages-config.js - 100%
explainer-helpers.js - 100%

FDG-8517 - Create Initial Page for Savings Bond Explainer - Pair

---

gatsby-node.js
src/layouts/explainer/explainer.spec.js
src/layouts/explainer/explainer.tsx
src/models/IExplainerPageContext.ts
src/transform/explainer-pages-config.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8621
no change in test coverage 
change for explainer page bug as well

FDG-8621 Initial Page for Savings Bond Explainer page alignment is not matching with the Figma design.

---

src/components/datasets/filters/dateFilterTabs/dateFilterTabs.jsx
src/components/datasets/filters/filterGroup/filterGroup.jsx
src/components/datasets/filters/filterGroupReset/filterGroupReset.jsx
src/components/datasets/filters/filters.jsx
src/components/datasets/filters/filters.spec.js
src/components/datasets/filters/mobileFilterToggle/mobileFilterToggle.jsx
src/components/datasets/filters/searchFilterSummary/searchFilterSummary.jsx
src/components/datasets/mockData/mockFilters.js
src/components/datasets/search-results/search-results.jsx
src/components/datasets/topics/topic/topic.jsx
src/components/datasets/topics/topics.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7308
Code coverage number (~80%) from original file remains unchanged. Ticket is in backlog to improve code coverage here later as well.

FDG-7308 Rewrite dataset filters unit tests

---

src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/circle-chart-label.jsx
src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8485

FDG-8485 General Site Updates - Update Revenue Explainer "Sources of Revenue..." chart

---

src/layouts/explainer/sections/treasury-savings-bonds/treasury-savings-bonds.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8631
no changes in tests

FDG-8631 - "How Do Savings Bonds Finance the Federal Government?" is missing "Help"

---

src/components/site-header/official-banner/official-banner.module.scss

Design review: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1706290929272159

FDG-8565 Design review

---

src/pages/about-us/about-section/about-section.jsx
src/pages/about-us/contact-section/contact-section.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-7606
TEST: no change
just added tab index's

FDG-7606-Tabbing-issues-on-About-Us-page

---

env/uat.js

https://federal-spending-transparency.atlassian.net/browse/FDG-7977

FDG-7977 Update Endpoint

---

src/transform/endpointConfig.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8642

FDG-8642 Remove Specific Columns from Default View on Schedules of Federal Debt Dataset

---

src/layouts/explainer/quote-box/quote-box.tsx
src/layouts/explainer/sections/treasury-savings-bonds/savings-bonds-overview/savings-bonds-overview.spec.js
src/layouts/explainer/sections/treasury-savings-bonds/savings-bonds-overview/savings-bonds-overview.tsx
src/layouts/explainer/sections/treasury-savings-bonds/treasury-savings-bonds.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8579
savings-bonds-overview.tsx: 100%

FDG-8579 Savings Bond Overview Section

---

src/components/data-table/data-table-header/date-range-filter/date-range-filter.jsx
src/components/data-table/data-table-header/date-range-filter/date-range-filter.spec.js
src/components/data-table/data-table-header/date-range-filter/date-range-text-input/date-range-text-input.jsx
src/components/data-table/data-table-header/date-range-filter/date-range-text-input/date-range-text-input.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8152
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1707156908591499

FDG-8152 Design Review

---

gatsby-node.js
src/components/charts/chart-primary/chartPrimary.spec.js
src/components/charts/chart-primary/index.js
src/components/charts/chart-primary/setAxes.js
src/components/charts/chart-primary/tooltip.js
src/components/charts/chart-primary/utils.js
src/components/dataset-data/dataset-chart/dataset-chart.jsx
src/components/dataset-data/dataset-chart/dataset-chart.spec.js
src/components/dataset-data/table-section-container/table-section-container.jsx
src/components/dataset-data/table-section-container/table-section-container.spec.js
src/components/dataset-data/table-section-container/testHelpers.js
src/components/dtg-table/test-data.js
src/models/IDatasetConfig.ts
src/pages/404/index.jsx
src/pages/about-us/about-section/about-section.jsx
src/pages/about-us/faq-section/faq-section.spec.js
src/transform/endpointConfig.js
src/transform/metadata-transform.js
src/transform/static-metadata/datasets.json
src/utils/analytics/analytics.jsx
src/utils/api-utils.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8633
Coverage: 90.46%
table-section-container: 87.91%
Includes some minor refactoring changes made in a few files (removing comments, string concat, etc)

FDG-8633 Apply Chart enhancements to dataset with rounded values - MSPD

---

src/transform/endpointConfig.js

Do not merge until chart enhancements for MSPD has been merged (FDG-8633).
Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8627

FDG 8627 Apply Chart enhancements to dataset with rounded values - DTS

---

src/layouts/explainer/sections/treasury-savings-bonds/savings-bonds-key-takeaway/savings-bonds-key-takeaway.spec.js
src/layouts/explainer/sections/treasury-savings-bonds/savings-bonds-key-takeaway/savings-bonds-key-takeaway.tsx
src/layouts/explainer/sections/treasury-savings-bonds/treasury-savings-bonds.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8578
test: 90.48

FDG-5878 Key Takeaways Section

---

src/components/dataset-data/dataset-data.jsx
src/layouts/explainer/heros/treasury-savings-bonds/treasury-savings-bonds-hero.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8707

FDG-8707 Savings Bond Explainer page Hero section " Securities Issued in TreasuryDirect" dataset link is incorrect.

---

src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-over-time.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8061
Coverage: 90.73%
revenue-trends-line-chart: 100%

FDG-8061  Improve Code Coverage - revenue-trends-line-chart.jsx

---

src/layouts/explainer/heros/treasury-savings-bonds/treasury-savings-bonds-hero.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8714

FDG-8714 "S" in "since" should be in lowercase.

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/savings-bonds-sold-by-type-chart/inflation-toogle/inflation-toggle.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8710
Run build / serve to test locally

FDG-8710 Savings Bonds Sold by Type Over Time Chart Toggle Misaligned

---

src/components/data-table/data-table-header/date-range-filter/date-range-filter.spec.js
src/components/data-table/data-table-header/date-range-filter/date-range-text-input/date-range-text-input.jsx

Slack discussion: https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1707335289993409
https://federal-spending-transparency.atlassian.net/browse/FDG-8708

FDG-8708 DDP KUI - Date Picker - Blue Highlight Doesn't Appear Behind End Date Once Start Date is Selected

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/savings-bonds-sold-by-type-chart/chart-legend/chart-legend.module.scss
src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/savings-bonds-sold-by-type-chart/savings-bonds-sold-by-type-chart.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8729

FDG-8729 Savings Bonds Sold by Type Over Time Chart Interaction Design Fixes

---

src/components/dataset-data/table-section-container/table-section-container.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8747
test: no change

TIPS/CPI - Add Pointer Hand on Hover of Back Button

---

src/helpers/constants.js
src/helpers/published-reports/published-reports.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8659

FDG-8659 Whitelist Published Reports - Exchange Rates Dataset

---

env/uat.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8745
TEST: no change

FDG-8745 TIPS/CPI - Update summary table field 

---

src/components/banner-callout/banner-callout-helper.js
src/transform/static-metadata/datasets.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8141

FDG-8141 Remove banner on DDP for U.S. Treasury Savings Bonds: Issues, Redemptions, and Maturities by Series & Electronic Securities Transactions

---

env/uat.js
gatsby-node.js
src/components/data-table/data-table-helper.tsx
src/components/data-table/data-table-test-helper.js
src/components/data-table/data-table.spec.js
src/components/data-table/data-table.tsx
src/components/dataset-data/dataset-data.jsx
src/components/dataset-data/table-section-container/summary-table/summary-table.jsx
src/components/dataset-data/table-section-container/table-section-container.jsx
src/components/dataset-detail-nav/dataset-detail-nav.spec.js
src/components/dtg-table/dtg-table-row/dtg-table-row.jsx
src/components/dtg-table/dtg-table-row/dtg-table-row.spec.js
src/components/dtg-table/dtg-table.jsx
src/helpers/text-format/text-format.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8751
Coverage: 90.83

FDG-8751 TIPS/CPI - Update Front-End Formatting of Fields

---

env/uat.js
src/components/dataset-data/table-section-container/table-section-container.jsx
src/components/download-wrapper/download-wrapper.jsx
src/components/download-wrapper/download-wrapper.spec.js
src/recoil/disableDownloadButtonState.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8762

FDG-8762 Disable download button for tables where no data is shown due to custom dropdown filter

---

src/hooks/hookDataMocks/mockGAEventTrackingData.js
src/hooks/hooks.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8032
Coverage: 90.82%
- useGAEventTracking: 44% -> 100%

FDG-8032 Improve Code Coverage - useGAEventTracking.jsx

---

src/helpers/constants.js
src/helpers/published-reports/published-reports.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8011

FDG-8011 Whitelist Published Reports - TIPS/CPI Data

---

src/components/social-share/share-button-content/share-button-content.spec.js
src/components/social-share/share-button-content/share-button-content.tsx
src/components/social-share/social-share.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-7621
Note: Branch is named incorrectly because of some ticket overlap

FDG-7619 508 Compliance - Explainer Pages - AFG Social Share nested interactive controls

---

package-lock.json
package.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8098
Note: Did general smoke testing on site

FDG-8098 Update or remove npm package - @material/ripple

---

src/components/published-reports/filter-section/filter-section.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8011
Thread: https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1709587217727979?thread_ts=1709566765.747779&cid=C01129TNHQU

FDG-8011 Label for Publish Reports selector change for TIPS / CPI

---

src/layouts/explainer/sections/treasury-savings-bonds/savings-bonds-are-fully-matured/savings-bonds-are-fully-matured.module.scss

Styling updates for [FDG-8593](https://federal-spending-transparency.atlassian.net/browse/FDG-8593)

FDG-8593 What Happens When Bonds Are Fully Matured Section Layout and Copy - CSS Updates 

---

src/components/secondary-nav/secondary-nav.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-7621

FDG-7621 508 Compliance - Explainer Pages - AFG Sub Nav nested interactive controls

---

src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-government.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8832

FDG-8832 Types of Savings Bond section "Series EE Bonds", the "B" should be "b" to match the MAC.

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/what-influences-purchase-of-savings-bonds.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8842
test coverage: no change

Get short from added to ticket

---

src/helpers/constants.js
src/helpers/published-reports/published-reports.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8843

FDG-8843 Remove TIPS / CPI Published Reports from Whitelist

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/what-influences-purchase-of-savings-bonds.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8842
test no change

FDG-8842 What Influences the Purchase of Savings Bonds Section Data Visualization Callout Text is displaying decimals

---

src/components/charts/bar/bar.jsx
src/components/home-highlight-cards/home-highlight-card/home-highlight-card.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7624

FDG-7624 508 Compliance - Home Page - Charts missing alt text

---

src/components/glossary/glossary-term/glossary-popover-definition.jsx
src/components/glossary/glossary-term/glossary-popover-definition.spec.js
src/helpers/glossary-helper/glossary-lookup.js
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-government.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8833
Coverage: 90.53%

FDG-8833 The "Debt Held by the Public" glossary definition should have the word "not" underlined.

---

src/utils/api-utils-helper.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8845
Coverage: 90.49%

FDG-8845 FIPS Download Default Sort Param

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/i-bond-sales-chart/i-bond-sales-chart.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8591
Design requested that the legend line be updated to 2px

FDG-8591 Update Legend Line 

---

src/components/data-table/data-table-helper.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7791

FDG-7791 Add option to add link into column cells to React Table

---

src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/chart-legend/custom-legend.module.scss
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/chart-legend/custom-legend.tsx
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/chart-tooltip/custom-tooltip.module.scss
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/chart-tooltip/custom-tooltip.tsx
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/chart-top-notch/chart-top-notch.module.scss
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/chart-top-notch/chart-top-notch.tsx
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/how-savings-bonds-sold-chart.tsx
src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/savings-bonds-sold-by-type-chart/savings-bonds-sold-by-type-chart.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8581
tst no change

Fdg 8581 savings bonds sold chart

---

src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/types-of-savings-bonds-table/types-of-savings-bonds-responsive.tsx
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/types-of-savings-bonds-table/types-of-savings-bonds.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8874

FDG-8874 Types of Savings Bonds table is missing the Alt text

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/i-bond-sales-chart/i-bond-sales-chart-helper.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8875

FDG-8875 Correlation Between Inflation and I Bond Sales is missing "FY" and "Electronic Securities Transactions" URL is incorrect.

---

src/components/data-table/data-table-helper.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7791
Note: Should now load files in new tab in auctions query

FDG-7791 Add option to add link into column cells to React Table / Loads files in new tab

---

env/uat.js
gatsby-node.js
src/components/data-table/data-table.tsx
src/components/dtg-table/dtg-table.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8876

FDG-8876 TIPS/CPI - Remove Columns from Default View

---

src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/how-savings-bonds-sold-chart.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8878
tst no change

Fdg 8878 Public Chart hyperlinks in the footnote

---

env/uat.js
src/transform/endpointConfig.js
src/transform/static-metadata/datasets.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7979

FDG-7979 Promote New Dataset to Prod - TIPS/CPI Data

---

documentation/Savings Bonds Data Sources and Methodologies.md

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8817

FDG-8817 Upload README to github

---

src/transform/explainer-pages-config.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8600

FDG-8600 Related Datasets Section

---

src/layouts/explainer/explainer-helpers/treasury-savings-bonds/treasury-savings-bonds-helper.js
src/layouts/explainer/sections/sections.jsx

Update Data Sources and Methodologies accordion with content from MAC. 
[**Jira Story**](https://federal-spending-transparency.atlassian.net/browse/FDG-8598)
All files (lines %): 90.52%
sections.jsx: 100%
treasury-savings-bonds-helper.js: 100%

FDG-8598 Data Sources and Methodologies Accordion

---

src/transform/endpointConfig.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8742

FDG-8742 Remove Specific Columns from Default View on the Exchange Rates Dataset

---

cypress.config.ts
cypress/e2e/explainer-navigation.cy.ts

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8891

FDG-8891 Cypress config changes for connecting to localhost

---

package-lock.json
package.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8108

FDG-8108 Update npm packages - date-fns

---

src/components/scroll-container/scroll-container.jsx
src/components/scroll-container/scroll-container.module.scss
src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/savings-bonds-sold-by-type-chart/savings-bonds-sold-by-type-chart-helper.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8587
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1710455665579259

FDG-8587 Design Review

---

documentation/Savings Bonds Data Sources and Methodologies.md

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8817

FDG-8817 Adjusted README Link

---

gatsby-node.js
src/components/banner-callout/banner-callout-helper.js
src/components/banner-callout/banner-callout.jsx
src/components/banner-callout/banner-callout.module.scss
src/components/banner-callout/banner-callout.spec.js
src/layouts/dataset-detail/dataset-detail.jsx
src/transform/static-metadata/datasets.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8828
Coverage: 90.71%
- banner-callout: 100%
- banner-callout-helper: 100%

FDG-8828 TOP Dataset - Add banner noting out-of-date data

---

src/components/home-features/home-features.jsx
src/components/topics-section/topics-section.jsx
src/pages/__tests__/index.spec.js
src/pages/home.module.scss
src/pages/index.jsx

Adding loading animation to the landing page so that the user is presented with a complete homepage rather than seeing the background process of loading in the content and layout.
[**Jira Story**](https://federal-spending-transparency.atlassian.net/browse/FDG-8826)
All files (% lines): 90.71% 
pages/index.jsx (% lines): 100%

FDG-8826 General Site Updates - Add loading animation for homepage layout

---

src/components/banner-callout/banner-callout-helper.js

Thread: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1710966012571149

FDG-8828 Banner copy update

---

src/transform/explainer-pages-config.js

[FDG-8606](https://federal-spending-transparency.atlassian.net/browse/FDG-8606)
Test: No change in coverage

FDG-8606 Mark Savings Bonds Explainer as Prod Ready

---

src/layouts/explainer/explainer-helpers/treasury-savings-bonds/treasury-savings-bonds-helper.js
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-government.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8940

FDG-8940 Fixed chart callout copy and DS&M Links

---

gatsby-node.js
src/layouts/explainer/explainer-components/chart-data-header/chart-data-header.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8925

FDG-8925 When screen size is reduced, Correlation Between Inflation and I Bond Sales Chart is flickering the screen.

---

src/components/site-header/mobile-menu/mobile-menu.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8945
No change in test coverage

FDG-8945 Mobile Dropdown 

---

src/components/site-header/mobile-menu/mobile-menu.jsx
src/components/site-header/site-header-helper.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8949

FDG-8949 Hovering Saving Bond site nav sub-menu item, everything shifts slightly to the left.

---

src/components/data-table/data-table-helper.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8889
Coverage: 90.35%

FDG-8889 Implement published report links on react table for TIPS / CPI in UAT

---

cypress/support/e2e.ts
jest.config.js
package-lock.json
package.json
src/components/download-wrapper/download-helpers.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8106

FDG-8106 Update npm package - csv-stringify

---

src/components/data-table/data-table-helper.tsx

Last PR introduced a final bug with conditional placement where formatted value was being overwritten. Have fixed in this PR

FDG-8888 Moved conditional back into proper place

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/what-influences-purchase-of-savings-bonds.tsx

[Jira ticket](https://federal-spending-transparency.atlassian.net/browse/FDG-8973)
All files: 90.39%

FDG-8973 The copy around JFK and the Payroll Savings Plan is inaccurate

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/what-influences-purchase-of-savings-bonds.tsx

Jira: https://federal-spending-transparency.atlassian.net/browse/FDG-8973

FDG-8973 -> Hotfix 2024.7.1

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/what-influences-purchase-of-savings-bonds.tsx
src/utils/api-utils-helper.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8977
Testing note is in ticket

FDG-8977 Treasury-reporting-rates-of-exchange dataset is downloading blank dataset when filter is applied.

---

src/utils/api-utils-helper.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8977

Hotfix Branch <- FDG-8977 & FDG-8979

---

src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter-helper.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7615

FDG-7615 508 Compliance - XR Tool - Add a label to the info tips buttons

---

src/components/datasets/filters/dateFilterTabs/dateFilterTabs.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7629

FDG-7629 508 Compliance - Dataset Search - Invalid ARIA attribute

---

src/components/accordion/accordion.jsx
src/components/api-quick-guide/accordions/accordions.jsx
src/components/api-quick-guide/accordions/fields/fields.jsx
src/components/api-quick-guide/accordions/filters/filters.jsx
src/components/api-quick-guide/accordions/format/format.jsx
src/components/api-quick-guide/accordions/pagination/pagination.jsx
src/components/api-quick-guide/accordions/sorting/sorting.jsx
src/components/api-quick-guide/api-quick-guide.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-7628

FDG-7628 508 Compliance - Dataset Detail Page - Aria-hidden elements should not be focusable

---

src/components/site-footer/site-footer.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8967

FDG-8967 Footer is covering the side navigation menu when we scroll to the bottom of the page.

---

src/components/dataset-data/table-section-container/summary-table/summary-table.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8974

FDG-8974 -TIPS/CPI Post MVP - Increase summary field width (again)

---

src/components/dataset-detail-nav/dataset-detail-nav.jsx
src/components/dataset-section-container/dataset-section-container.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8569
Kylon Conversation about removing's the related dataset form the sub nav. 
https://data-transparency-bfs.slack.com/archives/CPA4LFGMC/p1712859858239699
No change in test coverage

FDG-8569 DDP on the sub-navigation

---

src/components/api-quick-guide/accordions/fields/fields.jsx
src/components/api-quick-guide/accordions/filters/filters.jsx
src/components/api-quick-guide/accordions/format/format.jsx
src/components/api-quick-guide/accordions/pagination/pagination.jsx
src/components/api-quick-guide/accordions/sorting/sorting.jsx

[Jira](https://federal-spending-transparency.atlassian.net/browse/FDG-7613)
Test Coverage: no changes

FDG-7613 508 Compliance - Dataset Detail Page - Accordion needs unique ID

---

src/components/dataset-data/dataset-data.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9036

FDG-9036 DTS dataset download for "all tables" is failing.

---

src/components/dataset-data/dataset-data.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9036

2024.8.1 Hotfix 

---

src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/chart-tooltip/custom-tooltip.tsx
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/how-savings-bonds-sold-chart.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8965

FDG-8965 Non-Marketable in the Savings Bonds Sold as a Percentage of Total Debt Held by the Public chart is missing the "-"

---

src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
src/layouts/explainer/heros/hero-helper.tsx
src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx
src/layouts/explainer/heros/treasury-savings-bonds/treasury-savings-bonds-hero.tsx
src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8813

FDG 8813 AFG Debt Callout Update

---

env/uat.js
src/transform/endpointConfig.js
src/transform/static-metadata/datasets.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8724

FDG-8724 Promote New Dataset to Prod: Receipts by Dept.

---

src/utils/api-utils-helper.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9047

FDG-9047 Treasury Securities Auctions Data - Downloader Issue with Date Range Filters

---

src/utils/api-utils-helper.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9047

FDG-9047 Hotfix changes

---

gatsby-browser.js
react-query-client.js
src/components/dataset-data/dataset-data.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9046

FDG-9046 Remove Gatsby Browser export API error

---

src/helpers/constants.js
src/helpers/published-reports/published-reports.js

This reverts commit 0993297926c0d713204064a3eece371dc52e7c8c.

Revert "FDG-8917 whitelist"

---

src/components/data-table/data-table-helper.tsx
src/components/data-table/data-table.module.scss
src/transform/endpointConfig.js
src/transform/static-metadata/datasets.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8996

FDG-8996 DDP KUI - Add download affordance to PDF and XML links in data table

---

src/components/data-table/data-table-helper.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8939
Needs 8996 to be merged first

FDG 8939 Make published report react table links feature available in prod - TIPS / CPI

---

src/components/data-table/data-table-helper.tsx
src/components/data-table/data-table-test-helper.js
src/components/data-table/data-table.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8758
Test coverage: 90.19

FDG-8758 Filtering on NULL values on the Datasets - Pair

---

src/components/data-table/data-table-helper.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8938
NOTE: Need to merge 8939 first

FDG 8938 Make published report react table links feature available in prod - Auctions Query

---

src/components/data-table/data-table-helper.tsx

Added the accessorFn to additional data types
https://federal-spending-transparency.atlassian.net/browse/FDG-8758

FDG-8758 Filtering on NULL values on the Datasets

---

package-lock.json
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8110

FDG-8110 Update npm package - jest-runtime

---

package-lock.json
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8114

FDG-8114 Update npm package - react-google-recaptcha

---

src/components/data-table/data-table-helper.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8996
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1714165262762869?thread_ts=1714157139.582769&cid=CRFQA2DM1

FDG-8996 Design Review

---

src/components/dataset-data/table-section-container/pivot-options/pivot-options.jsx
src/components/dataset-data/table-section-container/pivot-options/pivot-options.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8704

FDG-8704 On DDP when user clicks on Pivot Value and selects N/A it is displaying data Loading spin but it is not loading the Data.

---

src/components/datasets/filters/filterRow/filterRow.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-7596

FDG-7596 Tabbing issues on the Dataset Search Page

---

package-lock.json
package.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8101

FDG-8101 G-Update npm package - @react-spring/web

---

package-lock.json
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8111
Updated make-fetch-happen from 8.0.14 to 13.0.0
I didn't notice any issue with the update that require additional changes.

FDG-8111 Update npm package - make-fetch-happen

---

package-lock.json
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8113
react-device-detect – Current Version 1.17.0 / Latest Stable Version 2.2.3 / Impacts: dataset card, site header
no change in test coverage.

FDG-8113-React Device-detection

---

src/helpers/constants.js
src/helpers/published-reports/published-reports.js

This reverts commit 33597440254eb95948e5287b5ad082d7b60c6149.

11.1: Whitelist Published Reports - Receipts by Dept.

---

src/components/api-quick-guide/api-quick-guide.jsx
src/components/api-quick-guide/api-quick-guide.module.scss

Addressing tabbing issue with expanding the api quick guide 
[**Jira Story**](https://federal-spending-transparency.atlassian.net/browse/FDG-7607)
No changes

FDG-7607 Tabbing issues on Dataset Detail page

---

src/components/api-quick-guide/accordions/accordions.jsx
src/components/api-quick-guide/api-quick-guide.jsx
src/components/api-quick-guide/dataset-detail-fields.jsx
src/components/links/custom-link/custom-link.tsx
src/components/links/page-scroll-link/page-scroll-link.jsx

Addressing issue found in:
https://federal-spending-transparency.atlassian.net/browse/FDG-7607
No test changes made

FDG-7607 add optional tabindex to custom link

---

react-query-client.js
src/layouts/explainer/hero-image/hero-image.module.scss
src/layouts/explainer/heros/federal-spending/federal-spending-hero.spec.js
src/layouts/explainer/heros/federal-spending/federal-spending-hero.tsx
src/layouts/explainer/heros/government-revenue/government-revenue-hero.spec.js
src/layouts/explainer/heros/government-revenue/government-revenue-hero.tsx
src/layouts/explainer/heros/hero-helper.tsx
src/layouts/explainer/heros/national-deficit/national-deficit-hero.spec.js
src/layouts/explainer/heros/national-deficit/national-deficit-hero.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9174
Coverage: 90.95%

FDG-9174 (Innovation Day) - Explainer Hero Data Caching / Eliminate hero content shift on flip card load

---

src/layouts/explainer/hero-image/hero-image.module.scss

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9216

FDG-9216 Savings Bonds Charts are not displaying correctly in inactive environment.

---

src/components/anchor-text/anchor-text.tsx
src/components/links/custom-link/custom-link.tsx
src/components/links/page-scroll-link/page-scroll-link.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9215

FDG-9215 Savings Bonds Charts are not displaying correctly in inactive environment.

---

gatsby-node.js
src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.spec.js
src/layouts/currency-exchange-rates-converter/index.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8811

FDG-8811 Research loading performance for XR Tool

---

src/components/site-footer/site-footer.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9127
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1716915736299889

FDG-9127 Design Review

---

src/components/info-tip/info-tip.jsx

Description: allowing to escape on the info "i" icon and not resetting the tabbing order 
Test coverage: no changes - 90.94%

FDG-9134 When tabbing on to the information icon "i" opens the dialog and after that user is unable to navigate to the next item using the tab

---

src/components/data-table/reset-table-container/reset-table-container.jsx
src/components/data-table/reset-table-section/reset-table-section.jsx
src/components/data-table/reset-table-section/reset-table-section.module.scss
src/components/dataset-data/chart-table-toggle/chart-table-toggle.jsx
src/components/dataset-data/chart-table-toggle/chart-table-toggle.module.scss
src/components/dataset-data/dataset-data.jsx
src/components/dataset-data/dataset-data.module.scss
src/components/dataset-data/dataset-data.spec.js
src/components/dataset-data/table-section-container/table-section-container.jsx
src/components/dataset-data/table-section-container/table-section-container.module.scss
src/components/datatable-select/datatable-select.jsx
src/components/datatable-select/datatable-select.module.scss
src/components/datatable-select/datatable-select.spec.js
src/components/dtg-table/dtg-table.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9029

FDG-9029 Raw Data Table Section Loading Improvements

---

src/components/banner-callout/banner-callout-helper.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9118

FDG-9118 Remove TOP Dataset Banner

---

src/components/page-glitch-graphic/page-glitch-graphic.jsx
src/components/page-glitch-graphic/page-glitch-graphic.module.scss
src/components/page-glitch-graphic/page-glitch-graphic.spec.js
src/components/page-unavailable/page-unavailable-text.spec.js
src/components/page-unavailable/page-unavailable-text.tsx
src/components/page-unavailable/page-unavailable.module.scss
src/components/page-unavailable/page-unavilable-text.tsx
src/components/pageError/page-error-text.jsx
src/components/pageError/page-error-text.spec.js
src/components/pageError/page-error.module.scss
src/components/siteLayout/siteLayout.jsx
src/pages/unavailable/index.tsx
src/pages/unavailable/unavailable.module.scss
src/pages/unavailable/unavailable.spec.js

Jira: https://federal-spending-transparency.atlassian.net/browse/FDG-9170
Test Coverage: 
all files (% lines): 90.97%
page-unavailable-text.tsx: 93.75%
unavailable/index.tsx: 100%

FDG-9170 Site Outage Messaging - Create site outage page

---

src/components/page-unavailable/page-unavailable.module.scss
src/pages/unavailable/unavailable.module.scss

Adjusting styling changes per Kylon's design feedback. 
Test coverage: no changes

FDG-9170 Adjust Styling for Site Outage Page

---

gatsby-node.js
package-lock.json
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8117

FDG-8117 Update dev dependency - @babel

---

src/components/dtg-table/dtg-table.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9301

FDG-9301 If user picks a Record Date and changes Date Range to 5 years or 10 years it is "Showing 0 rows of 0 rows".

---

src/components/select-control/select-control.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8529
no change in code coverage

FDG-8529 XR Converter Tool - Add hover state to published date frame

---

src/components/accordion/accordion.jsx
src/layouts/explainer/data-sources-methodologies/data-sources-methodologies.tsx
src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
src/layouts/explainer/sections/federal-spending/spending-categories/spending-categories.jsx
src/layouts/explainer/sections/federal-spending/spending-difference/spending-difference.jsx
src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-federal-revenue.jsx
src/layouts/explainer/sections/national-debt/breaking-down-the-debt/breaking-down-the-debt.jsx
src/layouts/explainer/sections/national-debt/debt-ceiling/debt-ceiling.jsx
src/layouts/explainer/sections/national-debt/funding-programs-and-services/spending-categories-accordion/spending-categories-accordion.jsx
src/layouts/explainer/sections/national-debt/growing-national-debt/debt-accordion/visualizing-the-debt-accordion.jsx
src/layouts/explainer/sections/national-deficit/debt-deficit-difference/debt-deficit-difference.jsx
src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
src/layouts/explainer/sections/national-deficit/understanding/surplus-illustration/surplus-illustration.jsx
src/layouts/explainer/sections/treasury-savings-bonds/savings-bonds-are-fully-matured/savings-bonds-are-fully-matured.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8615

FDG-8615 GA4 Upgrade: Create Custom Events - Explainers

---

src/components/download-wrapper/download-wrapper.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9300

FDG-9300 While downloading all files on MSPD dataset it is downloading as a CSV file instead of ZIP

---

src/components/data-table/data-table-header/date-range-filter/date-range-filter.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-8571

FDG-8571 DDP KUI - Update "Today" and "Clear" date picker controls to indicate interactivity

---

src/components/dataset-card/dataset-card.tsx
src/components/datasets/filters/filters.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8614

FDG-8614 GA4 Upgrade: Create Custom Events - Dataset Search

---

src/components/select-control/nest-select-control.jsx
src/components/select-control/select-control.jsx
src/components/select-control/select-control.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9308

FDG-9308 Hover tooltip is not working on the Published Date drop down arrow

---

src/components/dataset-data/dataset-data.spec.js
src/components/dataset-data/table-section-container/table-section-container.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9031

FDG-9031 Raw Data Table Section Caching Improvements

---

src/components/dataset-data/dataset-chart/dataset-chart.jsx
src/components/dataset-data/table-section-container/table-section-container.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9343

FDG-9343 TCIR dataset when selected chart and change the Data Table it is displaying "Oops... there's been a glitch in the data." in PROD

---

src/layouts/experimental/pdf-generator/pdf-generator.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9323
Removed pdf preview due to csp issues

FDG-9323 Remove pdf preview

---

src/components/select-control/select-control.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9375
No change on testing

FDG-9375 Currency Exchange Rates converter for Published Date Month and Date are displaying outside of the dropdown box

---

src/components/select-control/nest-select-control.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9375

Fdg 9375 scroll issue

---

src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9349
no testing change

FDG-9349 floating label is being cropped by the bounding box

---

env/uat.js

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-8677
All files: 90.88%

FDG-8677 New Dataset Created in UAT - FIP: Daily Principal Outstanding

---

env/qat.js
env/uat.js
src/components/download-wrapper/download-wrapper.jsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9272
all files: 90.89% (no change to coverage)

FDG-9272 remove experimental wrapper and featureId from env files

---

env/uat.js

FDG-8677 remove extra / in FIP endpoints

---

package-lock.json
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8121

FDG-8121 Update dev dependency - node-fetch

---

src/components/dataset-data/chart-table-toggle/chart-table-toggle.jsx
src/components/dataset-data/hide-legend-toggle/hideLegendToggle.jsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9196
all files: 90.89% (no change in coverage)

FDG-9196 Dataset MTS Ensure ARIA role elements contain required child roles in the Data preview tab set

---

src/components/dataset-properties-tabs/dataset-properties-tabs.jsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9195
all files: 90.89% (no coverage change)

FDG-9195 Dataset- TREE Ensure ARIA role elements contain required child roles in the Dataset properties tabs

---

src/components/data-table/data-table-helper.tsx
src/components/data-table/data-table-test-helper.js
src/components/data-table/data-table.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-5015
Test coverage: 90.89

FDG 5015 Dataset Detail Page - Remove additional $NaN values

---

src/helpers/constants.js
src/helpers/published-reports/published-reports.js

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9388
all files: 90.93% (no change in coverage)

FDG-9388 10.5 Whitelist Published Reports for FIP: Principal Outstanding

---

src/components/data-table/data-table-helper.tsx
src/components/data-table/data-table.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9391

FDG-9391 Dataset Detail Page - Remove additional $NaN values, keep *

---

src/layouts/explainer/explainer-test-helper.js
src/layouts/explainer/heros/treasury-savings-bonds/treasury-savings-bonds-hero.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9392

FDG 9392 saving bonds hero section

---

src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.module.scss
src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.tsx
src/components/published-reports/reports-section/reports-section.spec.js
src/components/published-reports/reports-section/reports-section.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9049
Slack discussion: https://data-transparency-bfs.slack.com/archives/CPA4LFGMC/p1721333299685129

FDG-9286 Design review 

---

src/layouts/explainer/sections/government-revenue/sources-of-federal-revenue/sources-of-revenue-circle-chart/sources-of-revenue-circle-chart.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-7711
No change in test coverage.

FDG-7711 Update to remove NaN

---

src/components/site-footer/site-footer.jsx
src/components/site-footer/site-footer.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9368
coverage: 90.9%

FDG-9368 Update Copyright Date

---

src/components/api-documentation/endpoints/endpoints.jsx
src/pages/about-us/about-section/about-section.jsx
src/pages/about-us/contact-section/contact-section.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-7597

FDG-7597 Tabbing Issues on the API Document page

---

src/layouts/currency-exchange-rates-converter/currency-exchange-rates-converter.spec.js
src/layouts/currency-exchange-rates-converter/index.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9225
All events were re-verified. Most already had the correct updated labels so only a few code changes needed to be made.

FDG-9225 GA4 Upgrade: Update Existing Values - Exchange Rate Tool

---

env/uat.js
src/transform/endpointConfig.js
src/transform/static-metadata/datasets.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8679

FDG-8679 Promote New Dataset to Production - FIP: Daily Principal Outstanding

---

package.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9412
Resolution notes attached in ticket

FDG-9412 Troubleshoot Cypress Local Proxy Issues

---

src/components/data-table/data-table-helper.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9361

FDG-9361 Update SLGS Daily Rate Table (Demand Deposit Rate): Display 9 Decimal Digits

---

env/uat.js

Jira: https://federal-spending-transparency.atlassian.net/browse/FDG-8682

FDG-8682 a -> an in dateRangeLockCopy

---

env/uat.js
src/components/data-table/data-table-helper.tsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-8682
**Changes**
Updating published reports to have multiple links in one cell and update default columns displayed
**Slack link**
https://data-transparency-bfs.slack.com/archives/CKM2LCAF6/p1723035237732389

FDG-8682 updates from Data Review

---

env/uat.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8666

FDG-8666 New Dataset Created in UAT - UTF Report Selection

---

src/components/published-reports/month-picker/month-picker-dropdown/month-picker-dropdown.module.scss
src/components/published-reports/month-picker/month-picker-dropdown/month-picker-dropdown.tsx
src/components/published-reports/month-picker/month-picker.module.scss

https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1723057399273459

FDG-9287 Design changes

---

src/layouts/explainer/heros/treasury-savings-bonds/treasury-savings-bonds-hero.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9397

FDG-9397 Savings Bonds - "Compared To" Copy/API Update

---

env/uat.js

Making adjustments per earlier conversation: https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1723125262017299

FDG-8682 add operation_date to hideColumns

---

src/components/published-reports/report-date-picker/report-date-dropdown/report-date-dropdown.module.scss
src/components/published-reports/report-date-picker/report-date-picker.module.scss
src/zIndex.module.scss

https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1723481074725889?thread_ts=1723057399.273459&cid=CRFQA2DM1

FDG-9390 & FDG-9287 Design Changes

---

src/components/data-table/data-table-header/data-table-header.tsx
src/components/data-table/data-table-header/date-range-filter/date-range-filter.jsx
src/components/data-table/data-table-header/date-range-filter/date-range-filter.module.scss
src/components/data-table/data-table.spec.js

https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1723581571147069
Kylon changes
No Change in test

FDG-9389 Kylon Changes

---

src/components/data-table/data-table-header/date-range-filter/date-range-filter.jsx
src/components/data-table/data-table-header/date-range-filter/date-range-filter.module.scss
src/components/data-table/data-table-header/date-range-filter/date-range-filter.spec.js
src/components/data-table/data-table.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9476
accesibility issue resolved

Fdg 9476 Defect accessibility

---

src/components/data-table/data-table-helper.tsx
src/components/data-table/data-table.spec.js
src/components/dataset-data/table-section-container/table-section-container.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9469
Test: no change in coverage

FDG-9469 Updated Date format

---

src/components/data-table/data-table-helper.tsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9318
all files: 90.66%

FDG-9318 Treasury Securities Buybacks - Update File Display Names in Buybacks Operations table

---

src/layouts/explainer/explainer-components/afg-components/afg-topic-card/afg-topic-card.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9421
No change in test coverage.

FDG-9421 EventAction Wording not correct

---

src/components/published-reports/report-date-picker/month-picker/month-picker.module.scss
src/components/published-reports/report-date-picker/month-picker/month-picker.spec.js
src/components/published-reports/report-date-picker/month-picker/month-picker.tsx
src/components/published-reports/report-date-picker/report-date-picker.spec.js
src/components/published-reports/report-date-picker/report-date-picker.tsx
src/components/published-reports/report-date-picker/report-day-picker/report-day-picker.module.scss
src/components/published-reports/report-date-picker/report-day-picker/report-day-picker.spec.js
src/components/published-reports/report-date-picker/report-day-picker/report-day-picker.tsx
src/components/published-reports/reports-section/reports-section.spec.js
src/components/published-reports/reports-section/reports-section.tsx
src/layouts/dataset-detail/dataset-detail.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9288
Coverage: 90.72

FDG-9288 Hook In All Report Data

---

src/components/api-quick-guide/api-quick-guide.jsx
src/components/api-quick-guide/api-quick-guide.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8570
Test: No change in coverage. 
Convo with Kylon: https://data-transparency-bfs.slack.com/archives/CPA4LFGMC/p1724187935412029

FDG 8570 white space at bottom of ddp page

---

src/components/dataset-card/dataset-card.spec.js
src/components/dataset-card/dataset-card.tsx
src/components/dataset-data/chart-table-toggle/chart-table-toggle.jsx
src/components/dataset-data/chart-table-toggle/chart-table-toggle.spec.js
src/components/dataset-data/dataset-data.spec.js
src/components/dataset-data/table-section-container/pivot-options/pivot-options.jsx
src/components/dataset-data/table-section-container/table-section-container.jsx
src/components/dataset-detail-nav/dataset-detail-nav.jsx
src/components/download-wrapper/download-wrapper.jsx
src/components/download-wrapper/download-wrapper.spec.js
src/components/published-reports/preview/preview.jsx
src/components/published-reports/preview/preview.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9220

FDG 9220 GA4 Upgrade: Create Custom Events & Update Existing Values - Dataset Page

---

env/uat.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9488
No Change in Testing

FDG-9488 Update Top Sorting

---

env/uat.js

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-8731
All files (% lines): 90.77%

FDG-8731 New Dataset Created in UAT - FBP: Detailed Prin & Accrued Int

---

src/components/published-reports/report-date-picker/month-picker/month-picker.module.scss

https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1724440271120579

FDG-9288 Design review

---

src/components/published-reports/reports-section/reports-section.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9519

FDG-9519 DTS Published reports when selected for the month of July it is not displaying all the published reports

---

src/components/datasets/topics/topic/topic.jsx
src/components/home-main-content/home-main-content.jsx
src/components/topics-section/homepage-tile/homepage-tile.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9526
No change in test coverage

FDG 9526 GA4 Hover Fix

---

src/components/dataset-data/dataset-data.spec.js
src/components/dataset-data/table-section-container/pivot-options/pivot-options.jsx
src/components/dataset-data/table-section-container/table-section-container.jsx
src/components/dataset-detail-nav/dataset-detail-nav.jsx
src/components/published-reports/preview/preview.jsx
src/components/published-reports/preview/preview.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9520

FDG 9520 Create Custom Events & Update Existing Values - Dataset Page GA4 events are not matching with GA4_Events_Dataset_Page.xlsx

---

src/components/dataset-data/table-section-container/set-no-chart-message.jsx
src/components/dataset-data/table-section-container/set-no-chart-message.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9441

FDG-9441 DDP - Update Data Table and Chart Message when 'All Data Tables' is Selected

---

src/components/site-header/desktop-menu/desktop-menu.spec.js
src/components/site-header/menu-dropdown/menu-dropdown.jsx
src/components/site-header/menu-dropdown/menu-dropdown.spec.js
src/components/site-header/site-header.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9198

FDG-9198 508 Main Nav Nested Element 

---

env/uat.js

Check that UTF is present in UAT and QAT

FDG-9502 Also to UAT

---

env/qat.js
env/uat.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9531

FDG-9531 Update Account Description Filter copy

---

src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/how-savings-bonds-sold-chart.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9201
NO change in test converge.

FDG-9201 labels added Savings bond chart

---

cypress/e2e/dataset-detail-page/dataset-detail-page.cy.ts
env/uat.js
gatsby-node.js
src/components/combo-select/combo-currency-select/combo-currency-select.jsx
src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx
src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.module.scss
src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.spec.js
src/components/combo-select/combo-select-test-helper.js
src/components/data-table/data-table.spec.js
src/components/dataset-data/table-section-container/table-section-container.jsx
src/components/datatable-select/datatable-select.module.scss
src/components/filter-download-container/user-filter/user-filter.spec.tsx
src/components/filter-download-container/user-filter/user-filter.tsx
src/components/search-bar/search-bar-helper.js
src/components/search-bar/search-bar.module.scss
src/components/search-bar/search-bar.spec.js
src/components/search-bar/search-bar.tsx
src/components/select-control/nest-select-control.jsx
src/models/IDatasetApi.ts
src/zIndex.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9532
Coverage: 90.74

FDG-9532 Group federal and state account descriptions in filter dropdown

---

env/uat.js

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9568

FDG-9568 Update FBP Dataset Title

---

env/uat.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9567

FDG-9567 Unhide Capitalized Interest and Amortization from both tables

---

static/data/ga-event-tracking/spendingExplainerEventTracking.csv

https://federal-spending-transparency.atlassian.net/browse/FDG-9491

FDG-9491 MTS udpate

---

src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9584

FDG-9584  Projects FDG  Add parent  FDG-9584   DDP KUI - Raw Data Table Dropdown Doesn't Reappear Once User Closes Out Text Box

---

src/components/dataset-data/dataset-data.jsx
src/components/dataset-detail-nav/dataset-detail-nav.jsx
src/components/published-reports/report-date-picker/date-text-input/date-text-input.spec.js
src/components/published-reports/report-date-picker/date-text-input/date-text-input.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9579
AND
https://federal-spending-transparency.atlassian.net/browse/FDG-9563
Coverage: 90.73%

FDG-9563 Separate Reports Section - Allow lowercase month entry in month picker input field

---

package-lock.json
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8122

FDG-8122 Update dev dependency - sass-loader

---

env/uat.js
src/transform/endpointConfig.js
src/transform/static-metadata/datasets.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8684

FDG-8684 Promote New Dataset to Production - Treasury Securities Buybacks Announcements/Results

---

src/components/filter-download-container/month-year-filter/month-year-filter.module.scss
src/components/filter-download-container/month-year-filter/month-year-filter.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9601

FDG 9601 Update Filter Section Date Heading

---

src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx

Text filter for year dropdown is not working as expected

FDG-9594 Fix text filtering

---

src/components/dataset-data/dataset-data.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9635

FDG-9635 All Data Table Selection - Do Not Retain Acct Selection

---

src/transform/endpointConfig.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8649

FDG-8649 Remove Specific Columns from Default View on the Interest Expense on the Public Debt Dataset

---

src/transform/endpointConfig.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8643

FDG-8643 Remove Specific Columns from Default View on Debt to the Penny Dataset

---

env/qat.js
env/uat.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9603
- No changes in coverage
- Changes only available in UAT at the moment until EDI changes

FDG-9603 FBP: Update Sorting for Data Table

---

src/transform/endpointConfig.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8647

FDG-8647 Remove Specific Columns from Default View on the Gift Contributions Dataset

---

src/transform/endpointConfig.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8646

FDG-8646 Remove Specific Columns from Default View on the Avg Interest Rates Dataset

---

env/qat.js
env/uat.js
src/components/filter-download-container/user-filter/user-filter.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9624

FDG-9624 Add a note to the Filters Section for UTF

---

env/qat.js
env/uat.js
gatsby-node.js
src/components/filter-download-container/month-year-filter/month-year-filter.spec.js
src/components/filter-download-container/month-year-filter/month-year-filter.tsx
src/components/filter-download-container/user-filter/user-filter.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9636
Month Year Filter Coverage: 100%

FDG 9636 Correct Future Dated Transactions Month/Year Filter

---

src/components/dataset-data/dataset-data.jsx
src/components/dataset-data/table-section-container/table-section-container.jsx

**Updates based on Data Review**
https://data-transparency-bfs.slack.com/archives/C01129TNHQU/p1727698597698149
**Test coverage** 
No change to coverage

FDG-9634 Ensure All Filter Fields Are Available/Required as Applicable for All Data Tables Selection... X2 

---

env/qat.js
env/uat.js
src/components/dataset-data/table-section-container/table-section-container.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9662

FDG-9662 FBP: Update Sorting for Data Table

---

src/components/published-reports/report-date-picker/date-text-input/date-text-input.tsx
src/components/published-reports/report-date-picker/report-day-picker/report-day-picker.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9663

FDG-9663 When double clicked on a date in the calendar, it switches the value to read “false” in the box where you type in the date value.

---

src/components/dataset-card/dataset-card.spec.js
src/components/dataset-card/dataset-card.tsx
src/layouts/explainer/explainer-helpers/national-debt/national-debt-helper.js
src/layouts/explainer/sections/national-debt/breaking-down-the-debt/breaking-down-the-debt.jsx
src/layouts/explainer/sections/national-debt/breaking-down-the-debt/breaking-down-the-debt.spec.js
src/layouts/explainer/sections/national-debt/breaking-down-the-debt/intragovernmental-holdings-chart/intragovernmental-holdings-chart.jsx
src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.jsx
src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.spec.js
static/data/ga-event-tracking/revenueExplainerEventTracking.csv

https://federal-spending-transparency.atlassian.net/browse/FDG-9536

FDG-9536 GA4 Upgrade: Update Existing Values - Explainers Citations discrepancies

---

src/components/published-reports/report-date-picker/report-day-picker/report-day-picker.tsx

https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1727884877967049

FDG-9663 Design Review

---

src/components/exchange-rates-converter/currency-exchange-rates-converter/currency-exchange-rates-converter.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9482
Kylon Fix: Spelling mistake

FDG-9482 General Site Update - XR Tool - Add "Base Conversion Rate" and "Data Source" headers Fix typo

---

env/qat.js
env/uat.js
gatsby-node.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9666

FDG-9666 Update Account Filter to Utilize Internal API (Account Summary)

---

src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.module.scss
src/components/exchange-rates-converter/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9485
Test unchanged.

Fdg 9485 General Site Update - XR Tool - Adjust main tool content spacing

---

src/components/banner-callout/banner-callout.module.scss
src/components/exchange-rates-converter/currency-exchange-rates-converter/currency-exchange-rates-converter.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9485
Change request from Kylon 
discussion:
https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1728325532261509

FDG-9485 General Site Update - XR Tool - Adjust main tool content spacing Kylon Fix

---

src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9714
no changes

FDG-9714 UTF dataset when Choose a Federal or State Account drop is open and try to change the Data Table it is displaying an error

---

src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/savings-bonds-sold-by-type-chart/inflation-toogle/inflation-toggle.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9197

FDG-9197 Inflation Toggle Ensure every form element has a label 

---

env/qat.js
env/uat.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9715

FDG-9715 Add a note to the filters section

---

env/qat.js
env/uat.js
gatsby-node.js
src/components/dataset-data/table-section-container/table-section-container.jsx
src/components/filter-download-container/month-year-filter/month-year-filter.module.scss
src/components/filter-download-container/month-year-filter/month-year-filter.tsx
src/components/filter-download-container/user-filter/user-filter.tsx
src/pages/api-documentation/index.jsx
src/utils/api-utils.js
src/utils/api-utils.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9680
coverage: 90.6

FDG-9680 Update Month/Year Filter to include effective date

---

src/components/combo-select/combo-currency-select/combo-currency-select.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9638

FDG 9638 Allow only one of year and month filters to be open at a time

---

src/pages/api-documentation/api.module.scss
src/pages/api-documentation/index.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-8466

FDG-8466 API Documentation Page TOC Blue Indicator Incorrect Placement

---

package-lock.json
package.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8112
Tested large downloads (since they hit the api) in DTS. Query string was compiled correctly.

FDG-8112 Update npm package - query-string

---

cypress/e2e/site-header/site-header.cy.ts

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9095

FDG-9095 Cypress Tests - Site Header - Site header interaction flow

---

cypress/e2e/site-header/site-header.cy.ts
src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx
src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.spec.js

Combo-select-dropdown.jsx: 94.36%
https://federal-spending-transparency.atlassian.net/browse/FDG-8070

FDG-8070 Improve Code Coverage - combo currency select

---

src/components/dataset-data/dataset-data.jsx
src/components/dataset-data/dataset-data.spec.js
src/components/dataset-data/report-data-toggle/report-data-toggle.jsx
src/components/dataset-data/report-data-toggle/report-data-toggle.module.scss
src/components/dataset-data/report-data-toggle/report-data-toggle.spec.js
src/components/dataset-detail-nav/dataset-detail-nav.jsx
src/components/published-reports/download-report/download-report.jsx
src/components/published-reports/download-report/download-report.module.scss
src/components/published-reports/download-report/download.report.spec.js
src/components/published-reports/filter-section/filter-section.jsx
src/components/published-reports/filter-section/filter-section.module.scss
src/components/published-reports/filter-section/filter-section.spec.js
src/components/published-reports/preview/preview.jsx
src/components/published-reports/preview/preview.module.scss
src/components/published-reports/preview/preview.spec.js
src/components/published-reports/published-reports.jsx
src/components/published-reports/published-reports.module.scss
src/components/published-reports/published-reports.spec.js
src/layouts/dataset-detail/dataset-detail.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9772

FDG-9772 Revert New Publish Reports section to UAT

---

env/qat.js
env/uat.js

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9776

FDG-9776 FBP: MVP - Update Dataset Detail Page URL

---

src/transform/endpointConfig.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9548

FDG-9548 Update Sort Order for Transactions Table and Federal Activity Table

---

src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-by-year.jsx
src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-by-year.spec.js
src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/custom-bar/custom-bar.jsx
src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart-helpers.js
src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9211
Coverage: 90.58

FDG-9211 On Deficit page user should be able to navigate to "Federal Deficit Trends Over Time, FY 2001-2023" chart using the keyboard

---

cypress/e2e/dataset-detail-page/ddp-sub-nav.cy.ts

https://federal-spending-transparency.atlassian.net/browse/FDG-9066

FDG 9066 Write Cypress Tests - DDP - Sub nav

---

.github/workflows/main.yml
cypress.config.ts
cypress/e2e/dataset-detail-page/dataset-detail-page.cy.ts
cypress/e2e/site-header/site-header.cy.ts

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9080

FDG-9080 Cypress Tests - DDP - Data table column filters and sorting interaction flow

---

src/components/published-reports/report-date-picker/month-picker/month-picker.spec.js
src/components/published-reports/report-date-picker/month-picker/month-picker.tsx
src/components/published-reports/report-date-picker/report-date-picker.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9581
Coverage: 
- month-picker: 100%
- overall: 90.66%

FDG-9581  Separate Reports Section - Adjust list interaction to always have selected month in view

---

.github/workflows/main.yml
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-9800

FDG-9800 Innovation Day - Add githubAction for PR Specific Test Coverage

---

env/uat.js
src/components/data-preview/data-preview.spec.js
src/components/data-preview/data-preview.tsx
src/layouts/dataset-detail/dataset-detail.jsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9741
data-preview.js: 100%

FDG-9741 Create New (and Experimental) Dataset Detail Table Section

---

package-lock.json
package.json

https://federal-spending-transparency.atlassian.net/browse/FDG-8123
Ran a fun smoke test on most of the stie no issue. No change in test

FDG-8123 Update Dev Dependency Typescript

---

src/layouts/explainer/sections/overview/revenue-chart/revenue-chart.tsx
src/layouts/explainer/sections/overview/spending-chart/spending-chart.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9229

FDG-9229 Overview page keyboard access to line charts

---

src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.tsx

Thread: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1731532959497809

FDG-9798 design review adjustments

---

src/layouts/explainer/sections/overview/deficit-chart/deficit-chart.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9204
Coverage:
- deficit-chart: 95.08%
- overall: 91%

FDG-9204 Overview deficit chart keyboard interactions

---

src/layouts/insight/sections/interest-expense/body-copy/body-copy.tsx
src/layouts/insight/sections/interest-expense/interest-expense.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9793

FDG-9793 Add Body Copy for the Interest Expense Topic Page 

---

src/layouts/explainer/sections/overview/chart-components/custom-tooltip/custom-tooltip.tsx
src/layouts/explainer/sections/overview/debt-chart/debt-chart.spec.js
src/layouts/explainer/sections/overview/debt-chart/debt-chart.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9230
Coverage: 91%

FDG-9230 Overview page keyboard access to "National Debt: Last 5 Years in Trillions of USD"

---

src/helpers/insights/insight-helpers.js
src/layouts/insight/insight.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9784
Test: no change

FDG-9784 Add Social Share Copy and Image for Interest Expense Topic Page

---

src/components/data-preview/data-preview-dropdown-dialog/data-preview-dropdown-dialog.module.scss
src/components/data-preview/data-preview-dropdown-dialog/data-preview-dropdown-dialog.spec.js
src/components/data-preview/data-preview-dropdown-dialog/data-preview-dropdown-dialog.tsx
src/components/data-preview/data-preview-dropdown-dialog/filter-buttons/filter-buttons.spec.js
src/components/data-preview/data-preview-dropdown-dialog/filter-buttons/filter-buttons.tsx
src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.spec.js
src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/zIndex.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9743
Coverage: 89.98%
data-preview-table-select-dropdown.tsx:  100%                            
data-preview-dropdown-dialog.tsx: 100%                                
filter-buttons.tsx: 100%

FDG-9743 Create Data Table Section Search Dialog

---

cypress.config.js
cypress/e2e/release-calendar/release-calendar.cy.ts
cypress/tsconfig.json

https://federal-spending-transparency.atlassian.net/browse/FDG-9097

FDG 9097 Cypress Tests - Release Calendar - Release calendar interaction flow

---

env/uat.js
src/transform/endpointConfig.js
src/transform/static-metadata/datasets.json

https://federal-spending-transparency.atlassian.net/browse/FDG-9042

FDG-9042 GAS Dataset - 11: Promote New Dataset to Prod

---

src/components/site-footer/site-footer.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9541

FDG-9541 FDG Community Site - Add community site link to site footer

---

src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9851

FDG-9851 Federal Revenue Trends Over Time, FY 2015-2024 chart is cutting off.

---

cypress/e2e/dataset-detail-page/dataset-properties.cy.ts
src/components/dataset-properties-tabs/dataset-properties-tabs.jsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9090

FDG-9090 Cypress Tests - DDP - Dataset properties interaction flow

---

src/components/site-header/menu-dropdown/menu-dropdown.jsx
src/components/site-header/menu-dropdown/menu-dropdown.spec.js
src/components/site-header/site-header-helper.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9928
- There should be no console error in the dev console when opening the nav menu dropdown to access the community site link
- The community site link should function correctly

FDG 9928 Console error related to FDG Community Site 

---

gatsby-node.js
src/components/data-table/data-table.spec.js
src/components/data-table/data-table.tsx
src/components/dataset-data/table-section-container/table-section-container.jsx
src/components/download-wrapper/download-item-button/download-item-button.jsx
src/components/download-wrapper/download-item-button/download-item-button.spec.js
src/components/download-wrapper/download-wrapper.jsx
src/components/dtg-table/dtg-table.jsx
src/models/IDatasetConfig.ts
src/transform/metadata-transform.js
src/transform/static-metadata/datasets.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9626
Coverage:
- data-table: 97.05%
- download-item-button: 90.69%

FDG 9626 FBP: Add Report Run Time Stamp to Downloader Files (CSV)

---

src/components/topics-section/homepage-tile/homepage-tile-helper.js

**Ticket:** [FDG-9852](https://federal-spending-transparency.atlassian.net/browse/FDG-9852)
**Coverage:**
> topics-section: 97.8%

FDG-9852-Savings-Bond-Tile

---

src/components/exchange-rates-converter/currency-entry-box/currency-entry-box.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8048
All test %: 90.05
currency-entry-box: 100%

FDG 8048 Improve Code Coverage - currency-entry-box.tsx

---

src/components/data-preview/data-preview-dropdown-search/data-preview-dropdown-dialog-search.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-9744
no change in test

FDG-9744 Styling fix for Create SearchAndScroll Component

---

src/components/nivo/custom-slice/custom-slice.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8049
Coverage:
- custom-slice: 100%
- overall: 89.84%

FDG-8049 Improve Code Coverage - custom-slice.jsx

---

cypress/e2e/api-quick-guide/api-quick-guide.cy.ts

> [FDG-9091](https://federal-spending-transparency.atlassian.net/browse/FDG-9091)
No change in coverage.

FDG-9091 Cypress Tests - DDP - API Quick Guide interaction flow

---

src/components/download-wrapper/download-item-button/download-item-button.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9626

FDG 9626 Minimum two digits for hour and minute number on timestamp

---

src/components/published-reports/reports-section/reports-section.module.scss
src/components/published-reports/reports-section/reports-section.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9966
Testing Note: filter can be tested on Schedules of Federal Debt

FDG-9966 Report Filter Mobile View

---

src/components/site-footer/site-footer.jsx
src/components/site-header/mobile-menu/mobile-menu.jsx
src/components/site-header/site-header-helper.js

https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1734611154298349

FDG-9541 Update community site url

---

src/components/data-preview/data-preview-filter-section/data-preview-download/data-preview-download-button/data-preview-download-button.module.scss
src/components/data-preview/data-preview-filter-section/data-preview-download/data-preview-download-button/data-preview-download-button.tsx
src/components/download-dialog/download-dialog.module.scss
src/components/download-dialog/download-dialog.spec.js
src/components/download-dialog/download-dialog.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9758
Coverage:
- download-dialog: 100%
- Overall: 89.83%

FDG 9758 Create DownloadDialog Component

---

src/components/page-helmet/page-helmet.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9916

FDG-9916 Verify FDG on Google Search Console (USAspending Account)

---

src/components/glossary/glossary-term/glossary-popover-definition.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-7390

FDG-7390 Glossary - Update design for glossary term highlights

---

src/components/glossary/glossary-term/glossary-popover-definition.jsx
src/components/glossary/glossary-term/glossary-popover-definition.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-8078
total coverage: 89.9%
glossary-popover-definition.jsx: 100%

FDG-8078 Improve Code Coverage - glossary-popover-definition.jsx

---

src/components/dataset-introduction/dataset-introduction.tsx
src/components/detail-pills/detail-pills.jsx
src/components/detail-pills/detail-pills.spec.js
src/layouts/dataset-detail/dataset-detail.jsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8509
Coverage: 
- detail-pills: 100%
- overall: 89.91%

FDG 8509 Add data table count pill in Introduction section

---

src/components/glossary/glossary-term/glossary-popover-definition.jsx
src/components/glossary/glossary-term/glossary-popover-definition.module.scss

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-7460

FDG-7460 Site-wide Glossary - Update glossary term popover component

---

src/components/data-table/data-table.module.scss
src/components/dtg-table/dtg-table-row/dtg-table-row.jsx
src/components/dtg-table/dtg-table-row/dtg-table-row.spec.js
src/components/dtg-table/dtg-table.module.scss
src/components/markdown-transform/markdown-transform.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10007
Coverage:
- Overall: 89.91%
- dtg-table-row: 88.67%

FDG 10007 Update Dataset Long Description Field to Include GAS Hyperlink 

---

src/components/dataset-detail-nav/dataset-detail-nav.jsx
src/components/dataset-detail-nav/dataset-detail-nav.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-8782

FDG-8782 DDP KUI - Update secondary nav tab highlighting style

---

src/components/dataset-introduction/dataset-introduction.module.scss
src/components/dataset-introduction/dataset-introduction.tsx

Slack: https://data-transparency-bfs.slack.com/archives/CRFQA2DM1/p1735064130187659

FDG-8509 Design Review

---

src/components/api-documentation/getting-started/getting-started.jsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-8496

FDG-8496 API Documentation - Update "How to Access our API" section with new example request

---

src/components/api-documentation/aggregation/aggregation.jsx
src/components/api-documentation/examples/examples.jsx
src/components/api-documentation/examples/examples.spec.js
src/components/api-documentation/getting-started/getting-started.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9942
no change in test

FDG-9942 Update API Doc Page - Example API Calls / Text

---

cypress/e2e/dataset-detail-page/ddp-related-dataset.cy.ts

[Cypress Tests - DDP - Related Datasets interaction flow](https://federal-spending-transparency.atlassian.net/browse/FDG-9092)

FDG-9092 Cypress Tests - DDP - Related Datasets interaction flow

---

cypress/e2e/about-us/about-us-links.cy.ts
cypress/e2e/about-us/about-us.cy.ts

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9110
**Test Coverage** 

FDG-9110 Cypress Tests - About Us - About Us links

---

src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.spec.js
src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.tsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-10026

FDG-10026 GAS dataset is not displaying Published reports

---

src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.spec.js
src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.tsx

GAS Published Reports hotfix into release branch

GAS Published Reports Hotfix

---

src/components/anchor-text/anchor-text.tsx
src/components/anchor-text/anchor.spec.js
src/components/footnote/footnote.spec.js
src/components/footnote/footnote.tsx
src/components/links/custom-link/custom-link.tsx
src/components/links/page-scroll-link/page-scroll-link.jsx
src/components/links/page-scroll-link/page-scroll-link.module.scss
src/components/links/page-scroll-link/page-scroll-link.spec.js
src/layouts/explainer/sections/treasury-savings-bonds/learn-more/learn-more-helper.js
src/layouts/explainer/sections/treasury-savings-bonds/learn-more/learn-more.spec.js
src/layouts/explainer/sections/treasury-savings-bonds/learn-more/learn-more.tsx
src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/what-influences-purchase-of-savings-bonds.tsx
src/layouts/explainer/sections/treasury-savings-bonds/savings-bonds-overview/savings-bonds-overview.tsx
src/layouts/explainer/sections/treasury-savings-bonds/treasury-savings-bonds.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9175
TEST: 89.85

FDG 9175 General Site Updates - Update footnote tab stop and add back to content links

---

cypress/e2e/currency-exchange-rates/currency-exchange-rates.cy.ts

https://federal-spending-transparency.atlassian.net/browse/FDG-9104

FDG-9104 Cypress Tests - XR Tool - XR Tool interaction flow

---

src/layouts/explainer/sections/treasury-savings-bonds/learn-more/learn-more.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10041
no change in test

FDG-10041 Footnote 1 is placed extra on the content.

---

cypress/e2e/dataset-detail-page/dataset-detail-page.cy.ts
cypress/e2e/explainers/debt.cy.ts
src/layouts/explainer/explainer.tsx

[FDG-9101](https://federal-spending-transparency.atlassian.net/browse/FDG-9101?atlOrigin=eyJpIjoiZThlMDhiNWUwOGZiNDk1NWFhMGJjMjI2OGFiMzI4ZmQiLCJwIjoiaiJ9)

FDG-9101 Created debt explainer cypress test(s)

---

src/components/charts/chart-primary/index.js
src/helpers/simplify-number/simplifyNumber.js
src/helpers/simplify-number/simplifyNumber.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10028
test coverage: 89.91%

FDG-10028 GAS dataset chart is not displaying correctly

---

src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.spec.js
src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/components/data-preview/data-preview-pivot-options/data-preview-pivot-options.tsx
src/components/data-preview/data-preview-pivot-select/data-preview-pivot-select.tsx
src/components/data-preview/data-preview-section-container/data-preview-section-container.tsx
src/components/data-preview/data-preview.spec.js
src/components/data-preview/data-preview.tsx
src/components/dataset-data/test-helper.js
src/layouts/dataset-detail/dataset-detail.jsx
src/pages/datasets/dataset-search-engine.spec.js
src/utils/api-utils.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9941
Coverage: 90.09%

FDG-9941 Apply Table and Pivot Selection

---

src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/components/data-preview/data-preview.tsx
src/layouts/dataset-detail/dataset-detail.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10054

FDG-10054 Apply table and Pivot selection is not loading the data

---

src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/components/data-preview/data-preview.spec.js
src/components/data-preview/data-preview.tsx
src/components/dataset-data/test-helper.js
src/models/data-preview/ITableSelectDropdown.ts

https://federal-spending-transparency.atlassian.net/browse/FDG-10058

FDG-10058 When dataset has only one table and no pivots it is still displaying the data table drop down is still displaying

---

src/components/data-preview/data-preview-dropdown-dialog/filter-buttons/filter-buttons.module.scss

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-9927

FDG-9927 ConfirmationFooter Component Styling

---

src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10016
TEST: 90.09
interest-expense-chart: 100%

FDG-10016 Interest Expense Insight - Add striped pattern to current fiscal year bar in chart

---

src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.tsx
src/layouts/insight/sections/interest-expense/useGetInterestExpenseData.ts

https://federal-spending-transparency.atlassian.net/browse/FDG-10015
We will merge the other two insight tickets first to avoid conflicts. FDG-10016, 10017.
No change in test.

FDG-10015 Interest Expense Insight - Adjust year axis on chart to show every 2/4 years

---

src/layouts/explainer/explainer-components/chart-data-header/chart-data-header.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-10103
No changes that require testing.

FDG-10103 Interest expense page on mobile there is a spacing issue causing a gap on the right side of the screen.

---

env/dev.js
env/prod.js
env/qat.js
src/transform/endpointConfig.js

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-10065
all files: 90.13%

FDG-10065 Exchange Rates Dataset Page Updates in UAT

---

src/components/footnote/footnote.tsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-10057

FDG-10057 Remove footnote number link, inside the actual footnotes

---

src/layouts/explainer/explainer-helpers/national-debt/national-debt-helper.js
src/layouts/explainer/sections/national-debt/dive-deeper-into-the-debt/dive-deeper-into-the-debt.spec.js

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-10129

FDG-10129 Debt Explainer - Update Dive Deeper Section Links

---

src/layouts/explainer/explainer-components/learn-more/learn-more-section.jsx
src/layouts/explainer/explainer-components/learn-more/learn-more-section.spec.js
src/layouts/explainer/explainer-helpers/national-deficit/national-deficit-helper.js

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-10130

FDG-10130 Deficit Explainer - Update Learn More Section Links

---

src/layouts/explainer/explainer-helpers/national-deficit/national-deficit-helper.js

Changes from Kelli's feedback in ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10130

FDG-10130 remove president's budget

---

gatsby-node.js
src/components/banner-callout/banner-callout-helper.js
src/components/banner-callout/banner-callout.jsx
src/components/banner-callout/banner-callout.module.scss
src/components/calendar-entries/calendar-entry-pages/calendar-entry-pages.jsx
src/components/calendar-entries/calendar-entry/calendar-entry.jsx
src/components/dataset-data/dataset-data.jsx
src/components/dataset-data/dataset-data.module.scss
src/components/dataset-data/dataset-data.spec.js
src/components/dataset-data/test-helper.js
src/components/download-wrapper/download-item-button/download-item-button.jsx
src/components/download-wrapper/download-toggle/download-toggle.jsx
src/components/download-wrapper/download-toggle/download-toggle.module.scss
src/components/download-wrapper/download-toggle/download-toggle.spec.js
src/components/download-wrapper/download-wrapper.jsx
src/components/download-wrapper/download-wrapper.spec.js
src/components/filter-download-container/filter-download-container.jsx
src/models/IDatasetApi.ts
src/transform/endpointConfig.js
src/variables.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-10155
Coverage: 90.27

FDG-10155 Create error message for Treasury Offset Program (TOP) download

---

src/transform/insight-pages-config.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10157

FDG-10157 Mark Insight page for prod ready

---

src/components/secondary-nav/secondary-nav.spec.js
src/components/secondary-nav/secondary-nav.tsx

**Jira**
https://federal-spending-transparency.atlassian.net/browse/FDG-8080
Secondary-nav.tsx: Increased coverage: 87.5% -> 98.61%
all files: 90.22%

FDG-8080 Improve Code Coverage - secondary-nav.tsx

---

src/components/dataset-data/dataset-data.jsx
src/components/download-wrapper/download-item-button/download-item-button.jsx
src/components/download-wrapper/download-item-button/download-item-button.spec.js
src/components/download-wrapper/download-wrapper.jsx
src/components/filter-download-container/filter-download-container.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9713
Coverage: 90.12%

FDG-9713 DDP pivot data xml download is displaying an error msg.

---

src/components/data-preview/data-preview-chart-table-toggle/chart-table-toggle.module.scss
src/components/data-preview/data-preview-filter-section/data-preview-download/data-preview-download-button/data-preview-download-button.module.scss
src/components/data-preview/data-preview-filter-section/data-preview-filter-section.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-10179
No changes required to testing.

FDG-10179 With Table / Chart Toggle and Download Buttons screen display is getting messed up when the screen size is reduced in the desktop view.

---

src/components/dtg-table/dtg-table.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10128

FDG-10128 Federal Investments Program: Statement of Account dataset "Transaction Date" filter is not working

---

src/components/dataset-data/table-section-container/table-section-container.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10131

FDG-10131 Continue React 18 Upgrade

---

env/uat.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10199

FDG-10199 Update TRRE Endpoint in UAT

---

src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart-helper.tsx
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.module.scss
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10164
No changes added to testing

FDG 10164 - Create tooltip for Interest Expense chart

---

src/components/data-table/data-table.tsx

[Waiting for ticket information](https://federal-spending-transparency.atlassian.net/browse/FDG-10209)

FDG-10209 Interest Expense on Public Debt Outstanding Table Doesn't Load on Pivot View

---

src/components/dtg-table/dtg-table.jsx
src/components/dtg-table/dtg-table.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10213

FDG-10213 DTS dataset is missing the pagination controls

---

env/dev.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10208
Changes should be tested in dev after merge before moving to QA

FDG-10208 Remove Dev Environment Auth

---

src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.spec.js
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9752
Coverage: 90.1

FDG-9752 Create Data Table Filter Dialog

---

gatsby-node.js
src/components/data-table/data-table-helper.tsx
src/components/data-table/data-table.spec.js
src/transform/endpointConfig.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10167
Coverage: 90.08%

FDG-10167 Treasury Bulletin - Display all Decimal Places for Certain Fields

---

src/components/dtg-table/dtg-table.jsx
src/components/dtg-table/dtg-table.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10213

Datasets are missing the pagination controls

---

src/components/data-preview/data-preview-section-container/data-preview-section-container.tsx
src/components/data-preview/data-preview-table/data-preview-table.tsx
src/utils/api-utils.js

https://federal-spending-transparency.atlassian.net/browse/FDG-9974
No testing changes

FDG-9974 Data Table - API Error Message Pair

---

src/components/published-reports/report-generator/report-table/report-table.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10175
Forgot to add back in width style

FDG-10175 Create Report Generator Component - Fix width

---

env/dev.js
env/prod.js
env/qat.js
env/uat.js
src/transform/endpointConfig.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10066
No changes that will effect testing.

FDG-10066 Exchange Rates Dataset Page Updates to Prod

---

src/components/chart-with-table/chart-table-container/chart-table-container.module.scss
src/components/chart-with-table/chart-table-container/chart-table-container.spec.js
src/components/chart-with-table/chart-table-container/chart-table-container.tsx
src/components/data-preview/data-preview-filter-section/data-preview-download-wrapper/download-button/download-button.tsx
src/components/data-table/data-table.tsx
src/components/download-wrapper/download-helpers.js
src/components/pagination/pagination-controls.module.scss
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart-helper.tsx
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.spec.js
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.tsx
src/layouts/insight/sections/interest-expense/useGetInterestExpenseData.ts

https://federal-spending-transparency.atlassian.net/browse/FDG-10197

FDG 10197 Interest Expense Table Download

---

src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-10196

FDG-10196 Interest Expense Chart / Table Toggle

---

src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.spec.js
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10246

FDG-10246 Interest Expense Table Download not downloading correctly

---

cypress/e2e/explainers/revenue.cy.ts

https://federal-spending-transparency.atlassian.net/browse/FDG-9098

FDG-9098 Cypress Tests - Explainers - Revenue explainer

---

src/components/dropdown-container/dropdown-container.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10252

FDG-10252 On DDP "Reports and Files" section Published Date drop down box month "<" and ">" are not working.

---

src/components/topics-section/homepage-tile/homepage-tile-helper.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10161

FDG-10161 Interest Expense Homepage Tile Copy - Update Site

---

src/components/datasets/search-results/search-results.jsx
src/components/datasets/search-results/search-results.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10117
Coverage: 90.33%

FDG-10117 Dataset Search - Update Default Sort

---

src/layouts/explainer/explainer-components/key-takeaways/key-takeaways-section.jsx
src/layouts/explainer/sections/federal-spending/how-much-does-the-govt-spend/how-much-does-the-govt-spend.jsx
src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/federal-revenue-trends-and-us-economy.jsx
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.jsx
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-line-chart/revenue-trends-line-chart.jsx
src/layouts/explainer/sections/government-revenue/key-takeaways/revenue-key-takeaways.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10234
Note: A few additional updates were made to resolve console errors

FDG-10234 It is not displaying correct Fiscal year on Revenue and Spending pages

---

src/components/banner-callout/banner-callout-helper.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10162

FDG-10162 TOP Dataset - Update Message for Disabled XML Button

---

src/components/api-documentation/aggregation/aggregation.jsx
src/components/api-documentation/aggregation/aggregation.spec.js
src/components/api-documentation/endpoints/endpoints.jsx
src/components/api-documentation/examples/examples.jsx
src/components/api-documentation/fields/fields.jsx
src/components/api-documentation/getting-started/getting-started.jsx
src/components/api-documentation/getting-started/getting-started.spec.js
src/components/api-documentation/parameters/format/format.jsx
src/components/api-documentation/parameters/pagination/pagination.jsx
src/components/api-documentation/parameters/parameters.jsx
src/components/api-documentation/responses/responses.jsx
src/components/api-documentation/responses/responses.spec.js
src/pages/api-documentation/index.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10132
No changes to testing coverage

FDG-10132 API Documentation Page Copy Updates

---

src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx
src/components/dropdown-label-button/dropdown-label-button.module.scss
src/components/dropdown-label-button/dropdown-label-button.tsx
src/components/generative-reports-section/generative-reports-account-filter/generative-reports-account-filter.spec.js
src/components/generative-reports-section/generative-reports-account-filter/generative-reports-account-filter.tsx
src/components/generative-reports-section/generative-reports-footer/generative-reports-footer.spec.js
src/components/generative-reports-section/generative-reports-footer/generative-reports-footer.tsx
src/components/generative-reports-section/generative-reports-section.tsx
src/layouts/dataset-detail/dataset-detail.jsx
src/transform/static-metadata/datasets.json

[FDG 10171](https://federal-spending-transparency.atlassian.net/browse/FDG-10171)

FDG 10171 - G-Create Account Filter

---

src/components/generative-reports-section/generative-reports-section.tsx

[Report Sectoi](https://federal-spending-transparency.atlassian.net/browse/FDG-10172)
no change in test converage

FDG 10172 Add Published Date Filter

---

src/components/data-preview/data-preview-filter-section/data-preview-filter-section.tsx
src/components/data-preview/data-preview-section-container/data-preview-section-container.tsx
src/components/data-preview/data-preview-summary-table/data-preview-summary-table.module.scss
src/components/data-preview/data-preview-summary-table/data-preview-summary-table.spec.js
src/components/data-preview/data-preview-summary-table/data-preview-summary-table.tsx
src/components/data-preview/data-preview.module.scss
src/components/data-preview/data-preview.spec.js
src/components/data-preview/data-preview.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-9866
Coverage: 90.14%

FDG-9866 Dataset Detail Table - Summary Table / Detail Table

---

src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.spec.js
src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/components/data-preview/data-preview-filter-section/data-preview-mobile-filter-list/data-preview-mobile-filter-list.module.scss
src/components/data-preview/data-preview-filter-section/data-preview-mobile-filter-list/data-preview-mobile-filter-list.spec.js
src/components/data-preview/data-preview-filter-section/data-preview-mobile-filter-list/data-preview-mobile-filter-list.tsx
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.tsx
src/components/data-preview/data-preview-mobile-dialog/data-preview-mobile-dialog.module.scss
src/components/data-preview/data-preview-mobile-dialog/data-preview-mobile-dialog.tsx
src/components/data-preview/data-preview.spec.js
src/components/data-preview/data-preview.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9977
Coverage: 90.15%

FDG-9977 Data Table Mobile View - Filter List Component

---

gatsby-node.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9357
No testing changes

FDG-9357 Update Exchange Rate Tool w/ New API

---

gatsby-node.js
src/components/dataset-introduction/dataset-introduction.tsx
src/components/detail-pills/detail-pills.jsx
src/components/detail-pills/detail-pills.spec.js
src/layouts/dataset-detail/dataset-detail.jsx
src/transform/metadata-transform.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10078

FDG-10078 Create New Data Expected pill for DDP

---

__mocks__/react-pdf.js
env/qat.js
gatsby-node.js
src/components/dropdown-label-button/dropdown-label-button.module.scss
src/components/dtg-table/dtg-table-row/dtg-table-row.jsx
src/components/generative-reports-section/generative-report-section-test-helper.js
src/components/generative-reports-section/generative-reports-section.spec.js
src/components/generative-reports-section/generative-reports-section.tsx
src/components/generative-reports-section/reports-config.js
src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.module.scss
src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.spec.js
src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.tsx
src/components/published-reports/download-report-table/download-report-table.spec.js
src/components/published-reports/download-report-table/download-report-table.tsx
src/components/published-reports/report-generator/mockData.js
src/components/published-reports/report-generator/report-generator.spec.js
src/components/published-reports/report-generator/report-generator.tsx
src/components/published-reports/report-generator/report-table/report-table.tsx
src/helpers/report-generator/report-generator-helper.js
src/helpers/text-format/text-format.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10176
Coverage: 90.16

FDG 10176 Add Report Generation to UTF Report Table

---

src/components/data-preview/data-preview-filter-section/data-preview-download-wrapper/data-preview-download-select/data-preview-download-select.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10373

FDG-10373 For Data Table mobile view download options should default to CSV

---

src/components/generative-reports-section/generative-reports-section.spec.js
src/components/generative-reports-section/reports-config.js

Sent back from data review to update sort. Effective date should be descending

FDG-10176 Add Report Generation to UTF Report Table

---

src/helpers/release-calendar/release-calendar-content-helper.ts

https://federal-spending-transparency.atlassian.net/browse/FDG-10266

FDG-10266 Update Release Calendar Copy

---

src/components/calendar-entries/calendar-entries.jsx
src/components/calendar-entries/calendar-entries.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-10217
Reminder to ask for a 16th min about wording on the Legends, they're not in the mac.

FDG-10217 Create Legend for Release Calendar

---

src/transform/endpointConfig.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10357

FDG-10357 Updated MSPD Table 3 Charting Config in Prod

---

src/components/nivo/chart-toggle/chart-toggle.jsx
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/types-of-savings-bonds-table/types-of-savings-bonds-responsive.module.scss
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/types-of-savings-bonds-table/types-of-savings-bonds.module.scss
src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/i-bond-sales-chart/i-bond-sales-chart.module.scss
src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/i-bond-sales-chart/i-bond-sales-chart.tsx
src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/savings-bonds-sold-by-type-chart/chart-header/chart-header.jsx
src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/savings-bonds-sold-by-type-chart/savings-bonds-sold-by-type-chart.module.scss
src/layouts/explainer/sections/treasury-savings-bonds/treasury-savings-bonds.module.scss

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10332
No changes to testing

FDG-10332 508 Scan - Update elements to meet minimum color contrast ratio thresholds

---

src/components/calendar-entries/calendar-entry/calendar-entry.spec.js
src/components/calendar-entries/calender-entry-status/calendar-entry-status.jsx
src/components/calendar-entries/calender-entry-status/calendar-entry-status.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10402

FDG-10402 Change Mobile wording for Release Calendar

---

src/components/detail-pills/detail-pills.jsx
src/transform/endpointConfig.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10308

FDG-10308 MSPD dataset when the user is in the Table or Chart view and changing the table for different chart it is displaying error msg

---

src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/components/data-preview/data-preview-filter-section/data-preview-mobile-filter-list/data-preview-mobile-filter-list.spec.js
src/components/data-preview/data-preview-filter-section/data-preview-mobile-filter-list/data-preview-mobile-filter-list.tsx
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.tsx
src/components/data-preview/data-preview.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-9980
Coverage: 90.14%

FDG-9980 Data Table Mobile View - Table Select Dialog

---

src/components/chart-with-table/chart-table-toggle/charting-table-toggle.tsx
src/components/info-tip/info-tip.jsx
src/layouts/explainer/sections/treasury-savings-bonds/purchase-of-savings-bonds/savings-bonds-sold-by-type-chart/chart-header/chart-header.jsx
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart-helper.tsx
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10333

FDG-10333 508 Scan - Add discernible text to Buttons/Links

---

__mocks__/react-pdf.js
src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.spec.js
src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.tsx
src/components/published-reports/download-report-table/download-report-table.spec.js
src/helpers/dataset-detail/report-helpers.js
src/helpers/dataset-detail/report-helpers.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10392
Coverage:

FDG-10392 UTF Report Generation - File Size

---

src/layouts/currency-exchange-rates-converter/index.tsx

**Ticket:** https://federal-spending-transparency.atlassian.net/browse/FDG-10267
No changes for testing.

FDG-10267 Update Treasury Financial Manual Link on the XR Converter Legal Disclosure

---

src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx

**Ticket:** https://federal-spending-transparency.atlassian.net/browse/FDG-9978
No testing changes needed.

FDG-9978 Data Table Mobile View - Table Data / Pivot Data Filters

---

src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/components/data-preview/data-preview-pivot-select/data-preview-pivot-select.tsx
src/components/data-preview/data-preview-section-container/data-preview-section-container.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10104
No changes required for testing.

FDG-10104 Add the Experimental Charting Functionality

---

src/components/dataset-card/dataset-stats/dataset-stats.jsx
src/components/dataset-card/dataset-stats/dataset-stats.module.scss
src/components/dataset-card/dataset-stats/dataset-stats.spec.js
src/pages/datasets/index.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10451
Test: 90.28

FDG-10451Optionally Hide API Specific Fields on the Dataset Search Page Cards

---

gatsby-node.js
src/components/generative-reports-section/generative-reports-empty-table/generative-reports-empty-table.spec.js
src/components/generative-reports-section/generative-reports-empty-table/generative-reports-empty-table.tsx
src/components/generative-reports-section/generative-reports-section.spec.js
src/components/generative-reports-section/generative-reports-section.tsx
src/components/generative-reports-section/reports-config.js
src/layouts/dataset-detail/dataset-detail.jsx
src/models/IDatasetConfig.ts
src/transform/metadata-transform.js
src/transform/static-metadata/datasets.json

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10178

FDG-10178 Handle Reports with No Matching Data

---

src/components/dataset-properties-tabs/dataset-properties-tabs.jsx
src/components/home-highlight-cards/home-highlight-card/home-highlight-card.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10335

FDG-10335 508 Scan - Provide updates to specific ARIA attributes and roles

---

src/components/dataset-card/dataset-stats/dataset-stats.jsx
src/components/dataset-card/dataset-stats/dataset-stats.module.scss
src/components/dataset-card/dataset-stats/dataset-stats.spec.js
src/pages/datasets/index.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10451

FDG-10451 - Release Branch

---

env/dev.js
src/components/dataset-introduction/dataset-introduction.tsx
src/components/detail-pills/detail-pills.jsx
src/components/detail-pills/detail-pills.spec.js
src/helpers/constants.js
src/helpers/published-reports/published-reports.js
src/layouts/dataset-detail/dataset-detail.jsx
src/layouts/dataset-detail/dataset-detail.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10453

FDG-10453 Whitelist Monthly Treasury Disbursement Report

---

env/uat.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10449

FDG-10449 Create Monthly Treasury Disbursement Page in UAT

---

src/layouts/explainer/sections/national-debt/growing-national-debt/debt-over-last-100y-linechart/debt-over-last-100y-linechart.jsx
src/layouts/explainer/sections/national-debt/growing-national-debt/debt-trends-over-time/debt-trends-over-time-chart.jsx
src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.jsx
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/chart-top-notch/chart-top-notch.tsx

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10331

FDG-10331 508 Scan - Add alternative text to <svg> elements with img roles

---

src/components/generative-reports-section/generative-reports-table-notice/generative-reports-table-notice.module.scss

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10465

FDG-10465 Banner box is displaying out of the table in mobile view

---

src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/components/data-preview/data-preview-pivot-select/data-preview-pivot-select.module.scss
src/components/data-preview/data-preview-pivot-select/data-preview-pivot-select.tsx
src/components/dropdown-label-button/dropdown-label-button.module.scss

https://federal-spending-transparency.atlassian.net/browse/FDG-10467
no change in testing

FDG-10467 Mobile view of "Samsun Galaxy S8+" pivot option boxes are cutting off.

---

src/components/generative-reports-section/generative-report-helper.js
src/components/generative-reports-section/generative-reports-section.spec.js
src/components/generative-reports-section/generative-reports-section.tsx
src/components/generative-reports-section/reports-config.js
src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.tsx
src/components/published-reports/report-generator/report-generator.spec.js
src/components/published-reports/report-generator/report-generator.tsx
src/helpers/report-generator/report-generator-helper.js
src/models/report-generator/IReportGenerator.ts

https://federal-spending-transparency.atlassian.net/browse/FDG-10363

FDG-10363 UTF Report Summary Tables and Values

---

env/uat.js
src/transform/endpointConfig.js
src/transform/static-metadata/datasets.json

https://federal-spending-transparency.atlassian.net/browse/FDG-10456

FDG-10456 Make MTD Page Available in All Environments

---

src/components/links/custom-link/custom-link.spec.js
src/components/links/custom-link/custom-link.tsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10490

FDG-10490 Daily Treasury Statement (DTS) dataset link for " Government Account Series Daily Activity Summary." is opening in a new tab.

---

src/components/data-preview/data-preview-datatable-banner/data-preview-datatable-banner.module.scss
src/components/data-preview/data-preview-datatable-banner/data-preview-datatable-banner.tsx
src/components/generative-reports-section/generative-report-section-test-helper.js
src/components/generative-reports-section/generative-reports-section.spec.js
src/components/generative-reports-section/generative-reports-section.tsx
src/components/published-reports/reports-section/reports-section.tsx
src/layouts/dataset-detail/dataset-detail.jsx
src/transform/metadata-transform.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10484

FDG-10484 UTF Report Summary Table and Values needs note

---

src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.jsx
src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.module.scss
src/components/combo-select/combo-currency-select/combo-select-dropdown/combo-select-dropdown.spec.js
src/components/data-preview/data-preview-dropdown-dialog/data-preview-dropdown-dialog.module.scss
src/components/data-preview/data-preview-dropdown-search/data-preview-dropdown-dialog-search.tsx
src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.spec.js
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.tsx
src/components/data-preview/data-preview-mobile-dialog/data-preview-mobile-dialog.tsx
src/components/dataset-data/dataset-data.spec.js

Ticket: https://federal-spending-transparency.atlassian.net/browse/FDG-10399

FDG-10399 Filters Dialog Column List

---

src/components/data-table/data-table-header/text-filter/text-filter.tsx
src/components/dtg-table/dtg-table.jsx

https://federal-spending-transparency.atlassian.net/browse/FDG-10468

FDG 10468 Filtering is getting disabled on certain data tables.

---

src/html.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10492

FDG-10492 FDG General - Updating Verint Survey Call Code in Prod

---

src/components/dataset-data/__snapshots__/dataset-data.spec.js.snap
src/components/dataset-data/table-section-container/table-section-container.spec.js
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-and-us-economy/government-revenue-and-us-economy-chart/total-revenue-chart/total-revenue-chart.spec.js
src/layouts/explainer/sections/government-revenue/federal-revenue-trends-over-time/revenue-trends-over-time.spec.js
src/layouts/explainer/sections/national-deficit/deficit-by-year/deficit-trends-bar-chart/deficit-trends-bar-chart.spec.js
src/layouts/explainer/sections/national-deficit/understanding/deficit-comparison-bar-chart/deficit-comparison-bar-chart.spec.js

https://federal-spending-transparency.atlassian.net/browse/FDG-10495

FDG-10495 Continue React 18 Upgrade

---

gatsby-node.js
src/components/generative-reports-section/generative-report-section-test-helper.js
src/components/generative-reports-section/generative-reports-section.spec.js
src/components/generative-reports-section/generative-reports-section.tsx
src/components/published-reports/filter-reports-section/filter-reports-section.tsx
src/components/published-reports/published-reports-test-helper.js
src/components/published-reports/published-reports.spec.js
src/components/published-reports/published-reports.tsx
src/components/published-reports/reports-section/reports-section.spec.js
src/layouts/dataset-detail/dataset-detail.jsx
src/transform/metadata-transform.js
src/transform/static-metadata/datasets.json

https://federal-spending-transparency.atlassian.net/browse/FDG-10519

FDG 10519 Establish Pattern to Request Reports at Run Time

---

src/components/data-preview/data-preview-data-table/data-preview-data-table.tsx
src/components/data-preview/data-preview-filter-section/data-preview-column-filter/data-preview-column-filter.spec.js
src/components/data-preview/data-preview-filter-section/data-preview-column-filter/data-preview-column-filter.tsx
src/components/data-preview/data-preview-filter-section/data-preview-filter-section.spec.js
src/components/data-preview/data-preview-filter-section/data-preview-filter-section.tsx
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/column-filter-options/date-column-filter/date-column-filter.tsx
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/column-filter-options/date-column-filter/date-presets/date-presets.tsx
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.spec.js
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.tsx
src/components/data-preview/data-preview-section-container/data-preview-section-container.tsx
src/models/data-preview/IDatePresets.ts
src/transform/endpointConfig.js
src/transform/static-metadata/datasets.json

https://federal-spending-transparency.atlassian.net/browse/FDG-10270

FDG-10270 Update Filters for Nested Data Tables

---

src/transform/static-metadata/datasets.json

[FDG-10557](https://federal-spending-transparency.atlassian.net/browse/FDG-10557)

FDG-10557 Add TSAD Reports Section

---

src/layouts/explainer/sections/national-debt/breaking-down-the-debt/breaking-down-the-debt.jsx

(cherry picked from commit 1d1927d0fd219e3327cfee7149a2233c5e46b0f2)

FDG-10585 Update release branch

---

gatsby-node.js
src/components/published-reports/filter-reports-section/filter-report-section.module.scss
src/components/published-reports/filter-reports-section/filter-report-section.spec.js
src/components/published-reports/filter-reports-section/filter-reports-section.tsx
src/components/published-reports/generative-reports-section/generative-reports-section.tsx
src/components/published-reports/published-reports.tsx
src/components/published-reports/reports-section/reports-section.tsx
src/models/IRunTimeReportConfig.ts
src/transform/static-metadata/datasets.json

[FDG-9500](https://federal-spending-transparency.atlassian.net/browse/FDG-9500)

FDG 9500 Create Account Number Filter for Published Reports

---

src/utils/api-utils-helper.js
src/utils/api-utils-helper.spec.js

[FDG-10629](https://federal-spending-transparency.atlassian.net/browse/FDG-10629)

FDG-10629 Remove "+" from Table Sort API Call

---

env/uat.js

[FDG-10303](https://federal-spending-transparency.atlassian.net/browse/FDG-10303)

FDG-10303 I-Bonds Rates: New Dataset Created in UAT

---

src/helpers/insights/insight-helpers.js

[FDG-10541](https://federal-spending-transparency.atlassian.net/browse/FDG-10541)

FDG-10541 Add Last Updated Date to the SLGS topic page

---

src/components/data-preview/__snapshots__/data-preview.spec.js.snap
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.spec.js
src/components/data-preview/data-preview.spec.js
src/components/dataset-data/__snapshots__/dataset-data.spec.js.snap
src/components/dataset-data/dataset-data.spec.js
src/components/dataset-data/test-helper.js
src/components/filter-download-container/range-presets/range-presets.spec.js

[FDG-10613](https://federal-spending-transparency.atlassian.net/browse/FDG-10613)

FDG-10613 Finalize React 18 Upgrade

---

src/helpers/insights/insight-helpers.js
src/layouts/insight/sections/state-and-local-government-series/state-and-local-government-series.tsx

[FDG-10540](https://federal-spending-transparency.atlassian.net/browse/FDG-10540)

FDG-10540 Add Data Sources & Methodologies Copy to the SLGS Topic Page

---

src/components/chart-with-table/chart-table-container/chart-table-container.tsx
src/components/date-range-month-picker/date-range-month-picker.spec.js
src/components/date-range-month-picker/date-range-month-picker.tsx
src/layouts/insight/sections/state-and-local-government-series/state-and-local-government-series-chart/state-and-local-government-series-chart.module.scss
src/layouts/insight/sections/state-and-local-government-series/state-and-local-government-series-chart/state-and-local-government-series-chart.tsx

[FDG-10543](https://federal-spending-transparency.atlassian.net/browse/FDG-10543)

FDG-10543 Add Loading State to Charts on Date Field Selection

---

src/components/data-table/data-table-helper.tsx
src/components/data-table/data-table.tsx
src/layouts/insight/sections/interest-expense/useGetInterestExpenseData.ts
src/layouts/insight/sections/state-and-local-government-series/useGetStateAndLocalGovernmentSeriesData.ts

[FDG-10691](https://federal-spending-transparency.atlassian.net/browse/FDG-10691)

Fdg 10691 SLGS Formatting Updates( SLGS RELEASE branch)

---

src/components/chart-with-table/chart-table-container/chart-table-container.module.scss
src/components/chart-with-table/chart-table-container/chart-table-container.tsx
src/components/date-range-month-picker/date-range-month-picker.module.scss
src/layouts/insight/sections/state-and-local-government-series/state-and-local-government-series-chart/state-and-local-government-series-chart-helper.tsx
src/layouts/insight/sections/state-and-local-government-series/state-and-local-government-series-chart/state-and-local-government-series-chart.tsx

Fdg 10690 infotip

---

src/components/date-range-month-picker/date-range-month-picker.module.scss
src/components/date-range-month-picker/date-range-month-picker.spec.js
src/components/date-range-month-picker/date-range-month-picker.tsx
src/components/date-range-month-picker/month-picker/month-picker.module.scss
src/components/date-range-month-picker/month-picker/month-picker.tsx

[FDG-10694](https://federal-spending-transparency.atlassian.net/browse/FDG-10694)

FDG-10694 Date Picker Design Updates - SLGS RELEASE

---

gatsby-node.js
src/components/published-reports/published-reports.tsx
src/models/IRunTimeReportConfig.ts
src/transform/static-metadata/datasets.json

[FDG-10650](https://federal-spending-transparency.atlassian.net/browse/FDG-10650)

FDG-10650 Whitelist Published Reports

---

jest.config.js
package-lock.json
package.json
src/layouts/explainer/sections/overview/debt-chart/debt-chart.spec.js

React Upgrade Test Config

---

src/layouts/explainer/sections/federal-spending/spending-trends/total-spending-chart/total-spending-chart.jsx

[FDG-10720](https://federal-spending-transparency.atlassian.net/browse/FDG-10720)

FDG-10720 Spending chart is not sizing correctly

---

src/components/data-table/data-table-helper.tsx
src/components/data-table/data-table.tsx
src/layouts/insight/sections/state-and-local-government-series/slgs-test-helper.js
src/layouts/insight/sections/state-and-local-government-series/state-and-local-government-series-chart/state-and-local-government-series-chart-helper.tsx
src/layouts/insight/sections/state-and-local-government-series/state-and-local-government-series-chart/state-and-local-government-series-chart.tsx
src/layouts/insight/sections/state-and-local-government-series/useGetStateAndLocalGovernmentSeriesData.spec.js
src/layouts/insight/sections/state-and-local-government-series/useGetStateAndLocalGovernmentSeriesData.ts

[FDG-10722](https://federal-spending-transparency.atlassian.net/browse/FDG-10722)

FDG-10722 Address MVP SLGS Feedback

---

package-lock.json
package.json
src/layouts/explainer/explainer-components/afg-components/afg-topic-card/afg-topic-card.jsx
src/layouts/explainer/sections/overview/revenue-chart/revenue-chart.tsx
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/chart-tooltip/custom-tooltip.tsx
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/chart-top-notch/chart-top-notch.tsx
src/layouts/explainer/sections/treasury-savings-bonds/how-savings-bonds-finance-government/how-savings-bonds-finance-chart/how-savings-bonds-sold-chart.tsx
src/pages/americas-finance-guide/index.jsx

Revert Recharts Upgrade

---

src/components/chart-with-table/chart-table-container/chart-table-container.tsx
src/components/date-range-month-picker/month-picker/month-picker.tsx
src/layouts/insight/sections/state-and-local-government-series/state-and-local-government-series-chart/state-and-local-government-series-chart.tsx

[FDG-10734 ](https://federal-spending-transparency.atlassian.net/browse/FDG-10734)

FDG-10734 SLGS Chart is not letting me choose July2025 date. Where as in the chart it is display data for that date

---

src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/components/data-preview/data-preview-filter-section/data-preview-column-filter/data-preview-column-filter.tsx
src/components/data-preview/data-preview-filter-section/data-preview-filter-section.module.scss
src/components/data-preview/data-preview-filter-section/data-preview-filter-section.tsx
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.tsx
src/components/data-preview/data-preview.module.scss
src/components/data-preview/data-preview.tsx
src/components/dropdown-label-button/dropdown-label-button.module.scss

[FDG-1051](https://federal-spending-transparency.atlassian.net/browse/FDG-10501)

FDG-10501 Filters Button Mobile Style

---

src/components/published-reports/generative-reports-section/generative-report-helper.js
src/components/published-reports/generative-reports-section/reports-config.js

This branch includes changes from FDG-10667, that pr will need to be done first
[FDG-10668](https://federal-spending-transparency.atlassian.net/browse/FDG-10668)

FDG-10668 Add Ending Balance Summary Table to Federal Activity Statement Report

---

src/components/published-reports/generative-reports-section/generative-reports-section.spec.js
src/components/published-reports/generative-reports-section/generative-reports-section.tsx

[FDG-10669](https://federal-spending-transparency.atlassian.net/browse/FDG-10669)

FDG-10669 Unemployment Trust Funds Report Selection - Account Statement published report data is not matching with the raw data in table.

---

src/components/published-reports/generative-reports-section/generative-report-helper.js
src/components/published-reports/generative-reports-section/reports-config.js

PRs for FDG-10667 and FDG-10668 should be done first
[FDG-10721](https://federal-spending-transparency.atlassian.net/browse/FDG-10721)

FDG-10721 Update Subtotal Table on Federal Activity Statement

---

src/layouts/insight/insight.module.scss
src/layouts/insight/insight.spec.js
src/layouts/insight/insight.tsx
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.tsx

[FDG-10695](https://federal-spending-transparency.atlassian.net/browse/FDG-10695)

FDG-10695 Initial Page Load Delay

---

src/components/chart-with-table/chart-table-container/chart-table-container.spec.js
src/components/chart-with-table/chart-table-container/chart-table-container.tsx
src/components/chart-with-table/chart-table-toggle/charting-table-toggle.spec.js
src/components/chart-with-table/chart-table-toggle/charting-table-toggle.tsx
src/components/data-preview/data-preview-filter-section/data-preview-download-wrapper/download-button/download-button.tsx
src/layouts/insight/sections/interest-expense/interest-expense-chart/interest-expense-chart.spec.js
src/layouts/insight/sections/state-and-local-government-series/body-copy/body-copy.tsx
src/layouts/insight/sections/state-and-local-government-series/state-and-local-government-series-chart/state-and-local-government-series-chart.spec.js
src/layouts/insight/sections/state-and-local-government-series/state-and-local-government-series-chart/state-and-local-government-series-chart.tsx

[FDG-10612](https://federal-spending-transparency.atlassian.net/browse/FDG-10612)

FDG-10612 SLGS Insight Page - GA4 Events

---

src/components/data-preview/data-preview-context.jsx
src/components/data-preview/data-preview-data-table/data-preview-data-table-body/data-preview-data-table-body.tsx
src/components/data-preview/data-preview-data-table/data-preview-data-table-header/data-preview-data-table-header.tsx
src/components/data-preview/data-preview-dropdown/data-preview-table-select-dropdown.tsx
src/components/data-preview/data-preview-filter-section/data-preview-filter-section.spec.js
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.spec.js
src/components/data-preview/data-preview-filter-section/data-preview-table-filters/data-preview-table-filters.tsx
src/components/data-table/data-table-helper.tsx
src/components/dropdown-label-button/dropdown-label-button.module.scss
src/components/dropdown-label-button/dropdown-label-button.tsx

[FDG-10635](https://federal-spending-transparency.atlassian.net/browse/FDG-10635)

FDG-10635 Applied Filter Design Updates

---

src/layouts/explainer/explainer-test-helper.js
src/layouts/insight/sections/state-and-local-government-series/body-copy/body-copy.spec.js
src/layouts/insight/sections/state-and-local-government-series/body-copy/body-copy.tsx

[FDG-10764](https://federal-spending-transparency.atlassian.net/browse/FDG-10764)

FDG-10764 Update Percent Copy

---

pull_request_template.md

PR template addition

---

gatsby-node.js
package-lock.json
package.json
src/components/published-reports/download-report-table/download-report-table-row/download-report-table-row.tsx
src/components/published-reports/download-report-table/download-report-table-row/gen-report-download-button.tsx
src/components/published-reports/download-report-table/download-report-table-row/getTheReport.js
src/components/published-reports/download-report-table/download-report-table-row/useRenderPDF.ts
src/components/published-reports/report-generator/report-generator.tsx
src/components/published-reports/report-generator/report-table/report-table.tsx
src/layouts/experimental/experimental.jsx
src/workers/pdf.worker.js
src/workers/pdfWorker.js

Web worker poc

---

src/components/markdown-transform/markdown-transform.tsx
src/components/site-header/site-header.jsx

Govt shutdown banner is missing ","

---

src/components/markdown-transform/markdown-transform.tsx
src/components/site-header/site-header.jsx

[FDG-10877](https://federal-spending-transparency.atlassian.net/browse/FDG-10877)

FDG-10877 Govt shutdown banner is missing ","
